(function(){
'use strict';
var HL='https://api.hyperliquid.xyz/info',DEXES=['','xyz','km','vntl'],POLL=4000,PAGE=20;
function validWallet(v){return /^0x[a-fA-F0-9]{40}$/.test(String(v||'').trim());}
function wallet(){var v=String(window._hlAccountWallet||window._userWallet||'').toLowerCase();return validWallet(v)?v:'';}
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function iso(v){var m=typeof v==='number'?v:Date.parse(v||'');return Number.isFinite(m)&&m>0?new Date(m).toISOString():'';}
function clone(a){try{return JSON.parse(JSON.stringify(a||[]));}catch(e){return Array.isArray(a)?a.slice():[];}}
async function post(body,ms){var c=new AbortController(),t=setTimeout(function(){c.abort();},ms||9000);try{var r=await fetch(HL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HL '+r.status+' '+body.type);var d=await r.json();if(d&&d.error)throw new Error(String(d.error));return d;}finally{clearTimeout(t);}}
function isOpenDir(v){return /^open\b/i.test(String(v||'').trim());}
function normFill(f,acct){if(!f)return null;var tm=n(f.time,0)||Date.parse(f.timestamp||'')||0,dir=String(f.dir||'').trim(),open=isOpenDir(dir),side=String(f.side||'').toUpperCase(),buy=side==='B'||side==='BUY',c=coin(f.coin||f.symbol),p=n(f.px!=null?f.px:f.price,0),sz=n(f.sz!=null?f.sz:f.volume,0),pnl=open?null:n(f.closedPnl!=null?f.closedPnl:f.pnl,0);return{trade_id:f.tid||f.trade_id||f.oid||f.order_id||(acct+'-'+c+'-'+tm),timestamp:tm?new Date(tm).toISOString():iso(f.timestamp),symbol:c+'/USD',coin:c,type:buy?'BUY':'SELL',direction:dir||((buy?'BUY':'SELL')+(open?' OPEN':' FILL')),volume:sz,lot:sz,price:p,entry_price:p,pnl:pnl,is_entry:open,_hlDir:dir,_crossed:!!f.crossed,_hlAccount:acct,_hlOid:f.oid||null,_raw:f};}
function normOrder(o,acct,dex){if(!o)return null;var c=coin(o.coin||o.symbol),s=String(o.side||'').toUpperCase(),sell=s==='A'||s==='SELL',px=n(o.triggerPx,0)||n(o.limitPx!=null?o.limitPx:o.px,0),tm=n(o.timestamp,0)||n(o.time,0)||Date.now();return{order_id:o.oid||o.order_id||o.cloid||('hl-'+c+'-'+tm),oid:o.oid||o.order_id||null,timestamp:new Date(tm).toISOString(),created_at:new Date(tm).toISOString(),symbol:c+'/USD',coin:c,type:sell?'SELL':'BUY',side:sell?'SELL':'BUY',direction:sell?'SHORT':'LONG',volume:n(o.sz!=null?o.sz:o.origSz,0),lot:n(o.sz!=null?o.sz:o.origSz,0),price:px,trigger_price:px,pnl:null,_logKind:'pending',_pendingSource:'HL_OPEN',_hlAccount:acct,_hlDex:dex||'main',_reduceOnly:!!o.reduceOnly,_raw:o};}
async function accounts(master){var out=[master],d;try{d=await post({type:'subAccounts',user:master},8000);}catch(e){d=[];}if(Array.isArray(d))d.forEach(function(x){var a=String(x&&x.subAccountUser||'').toLowerCase();if(validWallet(a)&&out.indexOf(a)<0)out.push(a);});return out;}
async function fetchFills(accts){var rs=await Promise.allSettled(accts.map(function(a){return post({type:'userFills',user:a,aggregateByTime:true},9500);})),all=[];rs.forEach(function(r,i){if(r.status==='fulfilled'&&Array.isArray(r.value))r.value.forEach(function(f){var x=normFill(f,accts[i]);if(x)all.push(x);});});if(!all.length&&rs.every(function(r){return r.status==='rejected';}))throw new Error('Semua userFills gagal');var seen={},out=[];all.forEach(function(x){var k=[x._hlAccount,x.trade_id,x.timestamp,x.symbol,x.price,x.volume].join('|');if(seen[k])return;seen[k]=1;out.push(x);});out.sort(function(a,b){return Date.parse(b.timestamp||0)-Date.parse(a.timestamp||0);});return out;}
async function fetchOpen(accts){var tasks=[];accts.forEach(function(a){DEXES.forEach(function(d){var b={type:'frontendOpenOrders',user:a};if(d)b.dex=d;tasks.push({a:a,d:d,p:post(b,8500)});});});var rs=await Promise.allSettled(tasks.map(function(x){return x.p;})),all=[],ok=0;rs.forEach(function(r,i){if(r.status==='fulfilled'&&Array.isArray(r.value)){ok++;r.value.forEach(function(o){var x=normOrder(o,tasks[i].a,tasks[i].d);if(x)all.push(x);});}});if(!ok)throw new Error('Semua frontendOpenOrders gagal');var seen={},out=[];all.forEach(function(x){var k=[x._hlAccount,x._hlDex,x.oid||x.order_id,x.symbol,x.price,x.volume].join('|');if(seen[k])return;seen[k]=1;out.push(x);});out.sort(function(a,b){return Date.parse(b.timestamp||0)-Date.parse(a.timestamp||0);});return out;}
function enginePending(){var a=Array.isArray(window._allPending)?window._allPending:[];return a.filter(function(o){return o&&!o._pendingSource&&!o._hlAccount;});}
function side(o){var s=String(o.side||o.direction||o.type||'').toUpperCase();return s.indexOf('SELL')>=0||s.indexOf('SHORT')>=0?'SELL':'BUY';}
function px(o){return n(o.trigger_price!=null?o.trigger_price:(o.entry_price!=null?o.entry_price:o.price),0);}
function sz(o){return n(o.lot!=null?o.lot:(o.size!=null?o.size:o.volume),0);}
function match(e,h){if(coin(e.symbol||e.coin)!==coin(h.symbol||h.coin)||side(e)!==side(h))return false;var eo=String(e.order_id||e.oid||''),ho=String(h.order_id||h.oid||'');if(eo&&ho&&eo===ho)return true;var ep=px(e),hp=px(h),es=sz(e),hs=sz(h),po=ep&&hp?Math.abs(ep-hp)/Math.max(ep,hp)<=.003:true,so=es&&hs?Math.abs(es-hs)/Math.max(es,hs)<=.12:true;return po&&so;}
function reconcile(engine,hl){var used={},rows=[],matched=0;engine.forEach(function(e){var c=clone([e])[0]||{},mi=-1;for(var i=0;i<hl.length;i++)if(!used[i]&&match(c,hl[i])){mi=i;break;}c.timestamp=iso(c.created_at||c.timestamp||c.time)||new Date().toISOString();c.symbol=(coin(c.symbol||c.coin))+'/USD';c.type=side(c);c.direction=side(c)==='SELL'?'SHORT':'LONG';c.volume=sz(c);c.price=px(c);c.pnl=null;c._logKind='pending';if(mi>=0){used[mi]=1;matched++;c._pendingSource='ENGINE+HL';c.direction+=' · HL OPEN';c._hlMatch=hl[mi];}else{c._pendingSource='ENGINE';c.direction+=' · ENGINE';}rows.push(c);});hl.forEach(function(h,i){if(!used[i]){var c=clone([h])[0];c.direction=(c.direction||'')+' · HL OPEN';rows.push(c);}});return{rows:rows,matched:matched};}
function fmtTime(v){if(!v)return'-';var d=new Date(v);if(isNaN(d))return String(v).replace('T',' ').slice(0,19);return d.getFullYear()+'.'+String(d.getMonth()+1).padStart(2,'0')+'.'+String(d.getDate()).padStart(2,'0')+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')+':'+String(d.getSeconds()).padStart(2,'0');}
function fmtPx(v){v=n(v,0);if(!v)return'—';if(v>=1000)return v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});if(v>=1)return v.toFixed(5).replace(/0+$/,'').replace(/\.$/,'');return v.toFixed(7).replace(/0+$/,'').replace(/\.$/,'');}
function install(){var d=document,oldCtl=window.__CTL_HISTORY_STABLE__;try{if(oldCtl&&oldCtl.timer)clearInterval(oldCtl.timer);if(oldCtl&&oldCtl.observer)oldCtl.observer.disconnect();}catch(e){}
var old=d.getElementById('historyTypeFilters'),tbody=d.getElementById('historyTableBody');if(!old||!tbody)return false;var filters=old.cloneNode(true);old.parentNode.replaceChild(filters,old);filters.querySelectorAll('.history-type-filter').forEach(function(b){b.removeAttribute('onclick');b.style.pointerEvents='auto';b.style.cursor='pointer';});
var ctl={ready:true,version:5,source:'hyperliquid-userfills+frontendOpenOrders+engine-reconcile',mode:'all',fills:[],hlOpen:[],engine:[],accounts:[],matched:0,shown:0,polling:false,lastGood:0,lastError:'',page:PAGE};window.__CTL_HISTORY_STABLE__=ctl;
function selected(){if(ctl.mode==='direct')return ctl.fills.filter(function(x){return x.is_entry;});if(ctl.mode==='pending'){var r=reconcile(ctl.engine,ctl.hlOpen);ctl.matched=r.matched;return r.rows;}return ctl.fills;}
function active(){filters.querySelectorAll('.history-type-filter').forEach(function(b){var a=b.dataset.historyType===ctl.mode;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a?'true':'false');});}
function info(rows){var el=d.getElementById('tradeLogInfo');if(!el)return;if(ctl.mode==='all')el.textContent='Hyperliquid fills · '+ctl.fills.length+' fills · menampilkan '+Math.min(rows.length,ctl.shown);else if(ctl.mode==='direct')el.textContent='LANGSUNG ENTRY · '+rows.length+' open fills · Hyperliquid'+(ctl.accounts.length>1?' · '+ctl.accounts.length+' accounts':'');else el.textContent='PENDING ORDER · Engine '+ctl.engine.length+' · HL open '+ctl.hlOpen.length+' · matched '+ctl.matched;el.style.color=ctl.lastError?'var(--gold)':'var(--green)';el.title='Wallet source: Hyperliquid userFills + frontendOpenOrders. Engine pending direkonsiliasi dengan order aktif Hyperliquid Main/xyz/km/vntl.';}
function empty(rows){var e=d.getElementById('emptyHistory'),t=d.getElementById('historyTable');if(rows.length){if(e)e.style.display='none';if(t)t.style.display='';return;}if(t)t.style.display='none';if(!e)return;e.style.display='';var a=e.querySelector('.text'),b=e.querySelector('.sub');if(ctl.mode==='pending'){if(a)a.textContent='Tidak ada Pending Order aktif';if(b)b.textContent='Engine pending dan frontendOpenOrders Hyperliquid sama-sama kosong untuk account aktif.';}else if(ctl.mode==='direct'){if(a)a.textContent='Tidak ada open fill pada history Hyperliquid';if(b)b.textContent='LANGSUNG ENTRY hanya menampilkan fill dengan dir Open Long / Open Short.';}else{if(a)a.textContent='Belum ada fill Hyperliquid';if(b)b.textContent='Data akan muncul langsung dari userFills account aktif.';}}
function openChart(x){try{if(typeof window.openPendingChart==='function')window.openPendingChart(x.symbol,x.price||x.entry_price,0,0,x.direction||x.type,ctl.mode==='pending'?'PENDING':'HL',String(x.trade_id||x.order_id||''));}catch(e){}}
function render(){active();var rows=selected(),max=Math.min(rows.length,ctl.shown||PAGE);tbody.innerHTML='';for(var i=0;i<max;i++){(function(x,idx){var tr=d.createElement('tr'),entry=!!x.is_entry,pnl=x.pnl==null?'—':((n(x.pnl)>=0?'+$':'-$')+Math.abs(n(x.pnl)).toFixed(4)),kind=ctl.mode==='pending'?'PENDING':(entry?'ENTRY':'CLOSE'),dir=ctl.mode==='pending'?(x.direction||side(x)):(x._hlDir||x.direction||kind),color=x.pnl==null?'var(--text-muted)':(n(x.pnl)>=0?'var(--green)':'var(--red)');tr.style.cursor='pointer';tr.title='Klik: lihat chart';tr.innerHTML='<td style="color:var(--text-muted);font-size:11px">'+fmtTime(x.timestamp||x.created_at)+'</td><td>'+(idx+1)+'</td><td style="font-weight:700">'+String(x.symbol||'-')+'</td><td class="'+(side(x)==='BUY'?'side-long':'side-short')+'" style="font-weight:800">'+side(x)+'</td><td title="'+String(dir).replace(/"/g,'&quot;')+'">'+kind+'</td><td>'+String(x.volume!=null?x.volume:(x.lot||0))+'</td><td>'+fmtPx(x.price||x.trigger_price||x.entry_price)+'</td><td style="color:'+color+';font-weight:800">'+pnl+'</td><td style="font-weight:700;color:var(--text-muted)">HL</td>';tr.addEventListener('click',function(){openChart(x);});tbody.appendChild(tr);})(rows[i],i);}ctl.shown=max;var wrap=d.getElementById('loadMoreDealsWrap'),btn=d.getElementById('loadMoreDealsBtn');if(wrap){if(max<rows.length){wrap.style.display='';if(btn)btn.textContent='📋 Load More +'+Math.min(PAGE,rows.length-max)+' ('+(rows.length-max)+' remaining)';}else wrap.style.display='none';}empty(rows);info(rows);}
ctl.setMode=function(m){ctl.mode=['all','pending','direct'].indexOf(m)>=0?m:'all';window._historyTypeFilter=ctl.mode;ctl.shown=PAGE;render();};ctl.loadMore=function(){ctl.shown=Math.min(selected().length,(ctl.shown||PAGE)+PAGE);render();};window._loadMoreDeals=ctl.loadMore;window.setHistoryTypeFilter=ctl.setMode;
filters.addEventListener('click',function(ev){var b=ev.target.closest&&ev.target.closest('.history-type-filter');if(!b||!filters.contains(b))return;ev.preventDefault();ev.stopPropagation();ctl.setMode(b.dataset.historyType||'all');},true);
async function poll(){if(ctl.polling)return;var master=wallet();if(!master){ctl.lastError='wallet belum tersedia';info(selected());return;}ctl.polling=true;try{var ac=await accounts(master),r=await Promise.allSettled([fetchFills(ac),fetchOpen(ac)]);ctl.accounts=ac;ctl.engine=clone(enginePending());if(r[0].status==='fulfilled')ctl.fills=r[0].value;if(r[1].status==='fulfilled')ctl.hlOpen=r[1].value;if(r[0].status==='rejected'&&r[1].status==='rejected')throw r[0].reason;ctl.lastGood=Date.now();ctl.lastError='';window._allFillsForLog=clone(ctl.fills);window._tradeLogAllFills=clone(ctl.fills);render();}catch(e){ctl.lastError=String(e&&e.message||e);ctl.engine=clone(enginePending());render();}finally{ctl.polling=false;}}
ctl.poll=poll;ctl.timer=setInterval(poll,POLL);ctl.setMode(window._historyTypeFilter||'all');poll();return true;}
window.__ctlInstallHlHistoryV5=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
