(function(){
'use strict';
function install(){
  var d=document,old=window.__CTL_HISTORY_V7_GUARD__;
  if(old&&old.timer)try{clearInterval(old.timer);}catch(e){}
  if(old&&old.retiredObserver)try{old.retiredObserver.disconnect();}catch(e){}
  ['__CTL_HL_PENDING_V13__','__CTL_HL_PENDING_BRIDGE_V14__','__CTL_HL_LIVE_PENDING_V16__','__CTL_HL_PENDING_V17__','__CTL_HL_PENDING_V18__','__CTL_HL_PENDING_V19__','__CTL_HL_SUMMARY_V16__','__CTL_HL_SUMMARY_V17__','__CTL_HL_SUMMARY_V18__','__CTL_HL_SUMMARY_V19__','__CTL_HL_MARKET_ONLY_V18__'].forEach(function(k){var x=window[k];if(x&&x.timer)try{clearInterval(x.timer);}catch(e){}if(x&&x.refreshTimer)try{clearInterval(x.refreshTimer);}catch(e){}if(x&&x.balanceTimer)try{clearInterval(x.balanceTimer);}catch(e){}});
  ['__CTL_UI_CLEANUP_V24__','__CTL_UI_RESTORE_V25__','__CTL_PANEL_RESTORE_V25__'].forEach(function(k){var x=window[k];if(!x)return;try{if(x.timer)clearInterval(x.timer);}catch(e){}try{if(x.observer)x.observer.disconnect();}catch(e){}x.disabledBy='v35-preserve';});
  var legacy=window.__CTL_HL_PORTFOLIO_V21__;if(legacy){try{if(legacy.timer)clearInterval(legacy.timer);}catch(e){}try{if(legacy.observer)legacy.observer.disconnect();}catch(e){}legacy.disabledBy='v22';}
  function installRetiredStyle(){var s=d.getElementById('ctlV30RetiredWidgetsStyle');if(!s){s=d.createElement('style');s.id='ctlV30RetiredWidgetsStyle';s.textContent='html body #rrMonitorBox,html body #renkoSmaHistoryPanel,html body .trading-workspace .workspace-renko-history{display:none!important;visibility:hidden!important;opacity:0!important;height:0!important;min-height:0!important;max-height:0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}';(d.head||d.documentElement).appendChild(s);}}
  function retireExact(){installRetiredStyle();var rr=d.getElementById('rrMonitorBox');if(rr)try{rr.remove();}catch(e){}var panel=d.getElementById('renkoSmaHistoryPanel');if(panel)try{panel.remove();}catch(e){}var rs=d.querySelectorAll('.workspace-renko-history');for(var i=0;i<rs.length;i++)try{rs[i].remove();}catch(e){}}
  retireExact();setTimeout(retireExact,0);setTimeout(retireExact,250);setTimeout(retireExact,900);
  function inject(id,src,onload){try{var prev=d.getElementById(id);if(prev){if(prev.dataset&&prev.dataset.loading==='1')return true;try{prev.remove();}catch(e){}}var s=d.createElement('script');s.id=id;s.src=src;s.async=false;if(s.dataset)s.dataset.loading='1';s.onload=function(){if(s.dataset)s.dataset.loading='0';if(onload)onload();};s.onerror=function(){try{s.remove();}catch(e){}};(d.head||d.documentElement).appendChild(s);return true;}catch(e){return false;}}
  function loadV10(){if(window.__CTL_HISTORY_STABLE__&&window.__CTL_HISTORY_STABLE__.version>=10)return true;if(typeof window.__ctlInstallHlHistoryV10==='function'){try{window.__ctlInstallHlHistoryV10();}catch(e){}return !!(window.__CTL_HISTORY_STABLE__&&window.__CTL_HISTORY_STABLE__.version>=10);}inject('ctlHlHistoryV10Script','history_hl_runtime_v10.js?v=20260827-2',function(){try{window.__ctlInstallHlHistoryV10&&window.__ctlInstallHlHistoryV10();}catch(e){}});return false;}
  function mode20Ok(){var m=window.__CTL_HISTORY_MODE_V20__;return !!(m&&m.ready&&m.renderOwnerAware===true);}
  function loadMode20(){if(!(window.__CTL_HISTORY_STABLE__&&window.__CTL_HISTORY_STABLE__.version>=10))return false;if(mode20Ok())return true;inject('ctlHlModeV20Script','history_hl_mode_v20.js?v=20260827-owner-aware-5',function(){try{window.__ctlInstallHlModeV20&&window.__ctlInstallHlModeV20();}catch(e){}});return false;}
  function loadInfer20(){if(!mode20Ok())return false;if(window.__CTL_HISTORY_MODE_V20_INFER__&&window.__CTL_HISTORY_MODE_V20_INFER__.ready)return true;if(typeof window.__ctlInstallHlModeV20Infer==='function'){try{window.__ctlInstallHlModeV20Infer();}catch(e){}return !!(window.__CTL_HISTORY_MODE_V20_INFER__&&window.__CTL_HISTORY_MODE_V20_INFER__.ready);}inject('ctlHlModeV20InferScript','history_hl_mode_v20_infer.js?v=20260827-real-1',function(){try{window.__ctlInstallHlModeV20Infer&&window.__ctlInstallHlModeV20Infer();}catch(e){}});return false;}
  function loadUi22(){if(!(window.__CTL_HISTORY_STABLE__&&window.__CTL_HISTORY_STABLE__.version>=10))return false;if(window.__CTL_HL_UI_ARBITER_V22__&&window.__CTL_HL_UI_ARBITER_V22__.ready)return true;if(typeof window.__ctlInstallHlUiArbiterV22==='function'){try{window.__ctlInstallHlUiArbiterV22();}catch(e){}return !!(window.__CTL_HL_UI_ARBITER_V22__&&window.__CTL_HL_UI_ARBITER_V22__.ready);}inject('ctlHlUiArbiterV22Script','history_hl_ui_arbiter_v22.js?v=20260827-single-writer-1',function(){try{window.__ctlInstallHlUiArbiterV22&&window.__ctlInstallHlUiArbiterV22();}catch(e){}});return false;}
  function fix23Ok(){var f=window.__CTL_HL_FIX_V23__,st=window.__CTL_HISTORY_STABLE__;return !!(mode20Ok()&&f&&f.ready&&String(f.source||'').indexOf('pending-history-hybrid')>=0&&st&&st.render&&st.render.__ctlV23===true);}
  function loadFix23(){if(!mode20Ok())return false;if(fix23Ok())return true;if(typeof window.__ctlInstallHlFixV23==='function'){try{window.__ctlInstallHlFixV23();}catch(e){}if(fix23Ok())return true;}inject('ctlHlFixV23Script','history_hl_fix_v23.js?v=20260827-hybrid-single-owner-7',function(){try{window.__ctlInstallHlFixV23&&window.__ctlInstallHlFixV23();}catch(e){}});return false;}
  function firstPaintOk(){var x=window.__CTL_FIRSTPAINT_V28__;return !!(x&&x.ready&&x.version>=28&&String(x.source||'').indexOf('no-dom-writer')>=0);}
  function loadFirstPaint(){if(!fix23Ok())return false;if(firstPaintOk())return true;if(typeof window.__ctlInstallFirstPaintV28==='function'){try{window.__ctlInstallFirstPaintV28();}catch(e){}if(firstPaintOk())return true;}inject('ctlFirstPaintV28Script','history_firstpaint_v28.js?v=20260827-first-second-1',function(){try{window.__ctlInstallFirstPaintV28&&window.__ctlInstallFirstPaintV28();}catch(e){}});return false;}
  function all29Ok(){var x=window.__CTL_ALL_SUMMARY_V29__,st=window.__CTL_HISTORY_STABLE__;return !!(x&&x.ready&&x.version>=29&&st&&st.render&&st.render.__ctlV29===true&&st.render.__ctlV23===true);}
  function loadAll29(){if(!fix23Ok()||!firstPaintOk())return false;if(all29Ok())return true;if(typeof window.__ctlInstallAllSummaryV29==='function'){try{window.__ctlInstallAllSummaryV29();}catch(e){}if(all29Ok())return true;}inject('ctlAllSummaryV29Script','history_all_summary_v29.js?v=20260827-all-summary-1',function(){try{window.__ctlInstallAllSummaryV29&&window.__ctlInstallAllSummaryV29();}catch(e){}});return false;}
  function real35Ok(){var x=window.__CTL_REAL_METRICS_V30__,z=window.__CTL_ZERO_FLICKER_V35__,st=window.__CTL_HISTORY_STABLE__;return !!(x&&x.ready&&x.version>=35&&z&&z.ready&&z.version>=35&&st&&st.render&&st.render.__ctlV35===true&&st.render.__ctlV33===true&&st.render.__ctlV29===true&&st.render.__ctlV23===true);}
  function loadReal35(){if(!all29Ok())return false;if(real35Ok())return true;if(typeof window.__ctlInstallRealMetricsV30==='function'){try{window.__ctlInstallRealMetricsV30();}catch(e){}if(real35Ok())return true;}inject('ctlRealMetricsV30Script','history_real_metrics_v30.js?v=20260827-v35-zero-flicker-2',function(){try{window.__ctlInstallRealMetricsV30&&window.__ctlInstallRealMetricsV30();}catch(e){}});return false;}
  var state={ready:true,version:35,source:'persistent-v10+owner-aware-v20+ui-v22+hybrid-v23+firstpaint-v28+all-summary-v29+p0-p2-v33+zero-flicker-v35+surgical-retire',timer:null,retiredObserver:null};window.__CTL_HISTORY_V7_GUARD__=state;
  loadV10();loadMode20();loadInfer20();loadUi22();loadFix23();loadFirstPaint();loadAll29();loadReal35();
  state.timer=setInterval(function(){retireExact();var a=loadV10(),b=loadMode20(),c=loadInfer20(),u=loadUi22(),f=loadFix23(),p=loadFirstPaint(),q=loadAll29(),r=loadReal35();if(a&&b&&c&&u&&f&&p&&q&&r){clearInterval(state.timer);state.timer=null;}},250);
  if(window.MutationObserver&&d.body){state.retiredObserver=new MutationObserver(function(ms){for(var i=0;i<ms.length;i++){var added=ms[i].addedNodes||[];for(var j=0;j<added.length;j++){var n=added[j];if(n&&n.nodeType===1&&(n.id==='rrMonitorBox'||n.id==='renkoSmaHistoryPanel'||(n.matches&&n.matches('.workspace-renko-history'))||(n.querySelector&&n.querySelector('#rrMonitorBox,#renkoSmaHistoryPanel,.workspace-renko-history')))){retireExact();return;}}}});state.retiredObserver.observe(d.body,{childList:true,subtree:true});}
  return true;
}
window.__ctlInstallHlHistoryV7Guard=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
