(function(){
'use strict';
var HL='https://api.hyperliquid.xyz/info',POLL=2500,DIRECT_SCAN_MS=12000,CACHE_KEY='ctl_hl_pending_real_v19';
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function validWallet(v){return /^0x[a-fA-F0-9]{40}$/.test(String(v||'').trim());}
function lower(v){return validWallet(v)?String(v).trim().toLowerCase():'';}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function rawDex(v){v=String(v||'').trim();return v.indexOf(':')>0?v.split(':')[0]:'';}
function tm(v){if(typeof v==='number'&&Number.isFinite(v))return v;var x=Date.parse(v||'');return Number.isFinite(x)?x:0;}
function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return Array.isArray(v)?v.slice():v;}}
function load(k){var x=null;try{x=JSON.parse(localStorage.getItem(k)||'null');}catch(e){}if(!x)try{x=JSON.parse(sessionStorage.getItem(k)||'null');}catch(e){}return x;}
function save(k,x){try{localStorage.setItem(k,JSON.stringify(x));}catch(e){try{sessionStorage.setItem(k,JSON.stringify(x));}catch(_){}}}
function add(a,v){v=lower(v);if(v&&a.indexOf(v)<0)a.push(v);}
function sideFrom(o){var s=String(o&&(o.side||o.type||o.direction)||'').toUpperCase();return s.indexOf('SELL')>=0||s.indexOf('SHORT')>=0||s==='A'?'SELL':'BUY';}
function kindFrom(o){var t=(String(o&&o._pendingKind||'')+' '+String(o&&o.pool_status||'')+' '+String(o&&o.order_type||'')+' '+String(o&&o.orderType||'')+' '+String(o&&o.triggerCondition||'')+' '+String(o&&o.tpsl||'')).toUpperCase();if(t.indexOf('TAKE PROFIT')>=0||/(^|\W)TP(\W|$)/.test(t))return'TP';if(t.indexOf('STOP')>=0||/(^|\W)SL(\W|$)/.test(t))return'SL';if(o&&(o.isPositionTpsl||o.isPositionTpSl))return'TP/SL';if(o&&(o.isTrigger||n(o.triggerPx,0)>0))return'TRIGGER';return'';}
function entryPx(o){return n(o&&((o.entry!=null?o.entry:(o.entryPx!=null?o.entryPx:o.entry_price))),0);}
function qty(o){return Math.abs(n(o&&((o.szi!=null?o.szi:(o.volume!=null?o.volume:(o.lot!=null?o.lot:o.sz)))),0));}
function px(o){return n(o&&((o.trigger_price!=null?o.trigger_price:(o.triggerPx!=null?o.triggerPx:(o.price!=null?o.price:(o.limitPx!=null?o.limitPx:o.trigger_price))))),0);}
async function post(body,ms){var c=new AbortController(),t=setTimeout(function(){c.abort();},ms||7000);try{var r=await fetch(HL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HL '+r.status+' '+body.type);var d=await r.json();if(d&&d.error)throw new Error(String(d.error));return d;}finally{clearTimeout(t);}}
function currentWallets(){var a=[];try{if(typeof window.activeHyperliquidWallet==='function')add(a,window.activeHyperliquidWallet());}catch(e){}add(a,window._hlAccountWallet);add(a,window._userWallet);add(a,window._hlActiveWallet);add(a,window._hlSelectedWallet);add(a,window._pagesHlActiveWallet);var st=window.__CTL_HISTORY_STABLE__;if(st&&Array.isArray(st.accounts))st.accounts.forEach(function(x){add(a,x);});if(st&&Array.isArray(st.fills)){var cnt={};st.fills.forEach(function(x){var w=lower(x&&x._hlAccount);if(w)cnt[w]=(cnt[w]||0)+1;});Object.keys(cnt).sort(function(x,y){return cnt[y]-cnt[x];}).slice(0,3).forEach(function(w){add(a,w);});}return a.slice(0,6);}
async function resolveWallets(base){var out=base.slice(),masters=[];await Promise.all(base.slice(0,4).map(async function(a){try{var r=await post({type:'userRole',user:a},5000),role=String(r&&r.role||'').toLowerCase();if(role==='agent'&&validWallet(r&&r.data&&r.data.user)){add(out,r.data.user);add(masters,r.data.user);}else if(role==='subaccount'&&validWallet(r&&r.data&&r.data.master)){add(out,r.data.master);add(masters,r.data.master);}else if(role==='user')add(masters,a);}catch(e){}}));for(var i=0;i<masters.length&&i<3;i++){try{var s=await post({type:'subAccounts',user:masters[i]},5500);if(Array.isArray(s))s.forEach(function(x){add(out,x&&x.subAccountUser);});}catch(e){}}return out.slice(0,8);}
var dexCache={at:0,list:['','xyz','km','vntl']};
async function dexes(){if(Date.now()-dexCache.at<300000)return dexCache.list.slice();var out=['','xyz','km','vntl'];try{var d=await post({type:'perpDexs'},6000);if(Array.isArray(d))d.forEach(function(x){var nm=typeof x==='string'?x:(x&&x.name)||'';nm=String(nm||'').trim();if(nm&&out.indexOf(nm)<0)out.push(nm);});}catch(e){}dexCache={at:Date.now(),list:out.slice(0,12)};return dexCache.list.slice();}
function normExchange(o,acct,dex,parent){if(!o)return null;parent=parent||{};var k=kindFrom(o),raw=String(o.coin||parent.coin||o.symbol||''),c=coin(raw),tr=n(o.triggerPx,0),lp=n(o.limitPx!=null?o.limitPx:o.px,0),p=tr||lp,q=Math.abs(n(o.sz!=null?o.sz:(o.origSz!=null?o.origSz:parent.sz),0));if(!k||!(p>0&&q>0)||c==='-')return null;var s=String(o.side||parent.side||'').toUpperCase(),sell=s==='A'||s==='SELL',t=n(o.timestamp,0)||n(o.time,0)||n(parent.timestamp,0)||Date.now(),dx=String(dex||rawDex(raw)||'');return{order_id:o.oid||o.order_id||o.cloid||('v19-'+acct+'-'+c+'-'+k+'-'+p+'-'+q),oid:o.oid||o.order_id||null,timestamp:new Date(t).toISOString(),symbol:c+'/USD',coin:c,type:sell?'SELL':'BUY',side:sell?'SELL':'BUY',direction:k+' · REDUCE',volume:q,lot:q,price:p,trigger_price:p,pnl:null,_pendingKind:k,_pendingSource:'HL_OPEN_ACTIVE',_hlAccount:lower(acct),_hlDex:dx||'main',_reduceOnly:true,_orderType:String(o.orderType||''),_triggerCondition:String(o.triggerCondition||'')};}
function flattenExchange(o,acct,dex,parent,out){out=out||[];if(!o)return out;var x=normExchange(o,acct,dex,parent);if(x)out.push(x);(Array.isArray(o.children)?o.children:[]).forEach(function(ch){flattenExchange(ch,acct,dex,o,out);});return out;}
function normDashboard(p){if(!p)return null;var k=kindFrom(p);if(!k&&p._reduceOnly)k=String(p._exitKind||p.pool_status||'').toUpperCase();if(!/^(TP|SL|TP\/SL|TRIGGER)$/.test(k))return null;var c=coin(p.symbol||p.coin||p._coinRaw),q=qty(p),pp=n(p.trigger_price!=null?p.trigger_price:(p.price!=null?p.price:p.triggerPx),0);if(c==='-'||!(q>0&&pp>0))return null;var raw=String(p._coinRaw||p.coin||''),s=String(p.side||p.type||'').toUpperCase();if(!s){var dir=String(p.direction||'').toUpperCase();s=dir.indexOf('LONG')>=0?'BUY':dir.indexOf('SHORT')>=0?'SELL':'';}return{order_id:p.order_id||p.oid||p.strategy_id||('dash-'+c+'-'+k+'-'+pp+'-'+q),oid:p.oid||p.order_id||null,timestamp:p.timestamp||p.created_at||new Date().toISOString(),symbol:c+'/USD',coin:c,type:s==='BUY'||s==='B'?'BUY':'SELL',side:s==='BUY'||s==='B'?'BUY':'SELL',direction:k+' · REDUCE',volume:q,lot:q,price:pp,trigger_price:pp,pnl:null,_pendingKind:k,_pendingSource:'HL_OPEN_ACTIVE',_hlAccount:lower(p._hlAccount||window._hlAccountWallet||window._userWallet),_hlDex:String(p._hlDex||rawDex(raw)||'main'),_reduceOnly:true,_orderType:String(p.order_type||p.orderType||'')};}
function livePositions(){var out=[];(Array.isArray(window._hlPosLive)?window._hlPosLive:[]).forEach(function(p){if(!p)return;var raw=String(p.coin||p.displayCoin||p.symbolKey||''),c=coin(raw),q=Math.abs(n(p.szi,0)),e=n(p.entry,0);if(c==='-'||!(q>0&&e>0))return;out.push({coin:c,raw:raw,dex:rawDex(raw)||'',szi:n(p.szi,0),qty:q,entry:e,current:n(p.current,0),upnl:n(p.upnl,0),account:lower(p._hlAccount||window._hlAccountWallet||window._userWallet)});});return out;}
function sourceTargets(){var a=[];function pushRows(src){if(Array.isArray(src))src.forEach(function(x){if(x)a.push(x);});}pushRows(window._enginePositions);pushRows(window._allPending);pushRows(window._sortedPending);return a;}
function matchSym(o,c){return coin(o&& (o.symbol||o.coin||o._coinRaw))===c;}
function validatedTargets(pos){var src=sourceTargets(),rows=[];pos.forEach(function(p){var candidates=src.filter(function(x){return matchSym(x,p.coin);}),sl=0,tp=0;var real=(window._hlSlTpByCoin||{})[p.raw]||(window._hlSlTpByCoin||{})[p.coin]||null;if(real){sl=n(real.sl,0);tp=n(real.tp,0);}candidates.forEach(function(x){if(!(sl>0))sl=n(x.stop_loss!=null?x.stop_loss:(x.sl!=null?x.sl:x.stopLoss),0);if(!(tp>0))tp=n(x.take_profit!=null?x.take_profit:(x.tp!=null?x.tp:x.takeProfit),0);});function addTarget(k,v,source){if(!(v>0))return;var sell=p.szi>0;rows.push({order_id:'live-'+source+'-'+p.coin+'-'+k+'-'+v,timestamp:new Date().toISOString(),symbol:p.coin+'/USD',coin:p.coin,type:sell?'SELL':'BUY',side:sell?'SELL':'BUY',direction:k+' · REDUCE',volume:p.qty,lot:p.qty,price:v,trigger_price:v,pnl:null,_pendingKind:k,_pendingSource:source==='HL'?'HL_OPEN_ACTIVE':'ENGINE_TARGET',_hlAccount:p.account,_hlDex:p.dex||'main',_reduceOnly:true,_livePosition:true});}addTarget('SL',sl,real&&n(real.sl,0)>0?'HL':'TARGET');addTarget('TP',tp,real&&n(real.tp,0)>0?'HL':'TARGET');});return rows;}
function rowKey(x){return [coin(x.symbol),String(x._pendingKind||''),n(x.trigger_price||x.price,0).toPrecision(12),Math.abs(n(x.volume||x.lot,0)).toPrecision(12)].join('|');}
function dedupe(rows){var map={},out=[];(rows||[]).forEach(function(x){if(!x)return;var k=rowKey(x),old=map[k];if(!old){map[k]=x;out.push(x);return;}if(old._pendingSource==='ENGINE_TARGET'&&x._pendingSource==='HL_OPEN_ACTIVE'){var i=out.indexOf(old);if(i>=0)out[i]=x;map[k]=x;}});out.sort(function(a,b){return tm(b.timestamp)-tm(a.timestamp);});return out;}
function metrics(rows,pos,st){var groups={},reward=0,risk=0,pnl=0,symbols={};rows.forEach(function(o){var c=coin(o.symbol),p=pos.find(function(z){return z.coin===c;});if(!p)return;var g=groups[c]||(groups[c]={p:p,tp:[],sl:[]}),pp=n(o.trigger_price||o.price,0),k=String(o._pendingKind||'').toUpperCase();symbols[c]=1;if(k==='TP')g.tp.push(pp);else if(k==='SL')g.sl.push(pp);else{var favorable=p.szi>0?pp>p.entry:pp<p.entry;(favorable?g.tp:g.sl).push(pp);}});Object.keys(groups).forEach(function(c){var g=groups[c],p=g.p,bestR=0,bestL=0;g.tp.forEach(function(v){var x=p.szi>0?(v-p.entry)*p.qty:(p.entry-v)*p.qty;if(x>bestR)bestR=x;});g.sl.forEach(function(v){var x=p.szi>0?(p.entry-v)*p.qty:(v-p.entry)*p.qty;if(x>bestL)bestL=x;});reward+=Math.max(0,bestR);risk+=Math.max(0,bestL);pnl+=n(p.upnl,0);});var closed=(st&&Array.isArray(st.fills)?st.fills:[]).filter(function(x){return x&&!x.is_entry&&x.pnl!=null&&symbols[coin(x.symbol)]&&Math.abs(n(x.pnl,0))>1e-12;}),wins=closed.filter(function(x){return n(x.pnl,0)>0;}).length,prob=closed.length?wins*100/closed.length:null;return{pnl:Object.keys(groups).length?pnl:null,entries:Object.keys(groups).length,prob:prob,rr:risk>1e-12?reward/risk:null,reward:reward,risk:risk,orders:rows.length,at:Date.now(),source:'active-hl-or-live-position-target-v19'};}
async function directScan(){var base=currentWallets();if(!base.length)return{rows:[],ok:0};var ac=await resolveWallets(base),dx=await dexes(),tasks=[];ac.slice(0,4).forEach(function(a){dx.forEach(function(d){tasks.push({a:a,d:d});});});var rows=[],ok=0,idx=0,workers=[];async function worker(){while(idx<tasks.length){var t=tasks[idx++];try{var r=await post({type:'frontendOpenOrders',user:t.a,dex:t.d||''},6500);if(Array.isArray(r)){ok++;r.forEach(function(o){flattenExchange(o,t.a,t.d,null,rows);});}}catch(e){}}}for(var i=0;i<Math.min(6,tasks.length);i++)workers.push(worker());await Promise.all(workers);return{rows:dedupe(rows),ok:ok,accounts:ac};}
function dashboardRows(){var out=[];(Array.isArray(window._hlRealPending)?window._hlRealPending:[]).forEach(function(p){var x=normDashboard(p);if(x)out.push(x);});return dedupe(out);}
function fingerprint(){var a=currentWallets();return a.length?a[0]:'';}
function install(){var old=window.__CTL_HL_PENDING_V19__;if(old&&old.timer)try{clearInterval(old.timer);}catch(e){}var v18=window.__CTL_HL_PENDING_V18__;if(v18&&v18.timer)try{clearInterval(v18.timer);}catch(e){}var state={ready:true,version:19,timer:null,scanAt:0,scan:null,emptyConfirm:0};window.__CTL_HL_PENDING_V19__=state;
  async function tick(){var st=window.__CTL_HISTORY_STABLE__;if(!st||st.version<10)return false;var pos=livePositions(),dash=dashboardRows(),targets=validatedTargets(pos),fp=fingerprint();var exchange=dash.slice(),scanOk=0;if(Date.now()-state.scanAt>DIRECT_SCAN_MS||(!exchange.length&&!state.scan)){state.scanAt=Date.now();state.scan=directScan().catch(function(){return{rows:[],ok:0};});}if(state.scan){try{var sc=await state.scan;state.scan=null;scanOk=n(sc.ok,0);exchange=dedupe(exchange.concat(sc.rows||[]));}catch(e){state.scan=null;}}var rows=dedupe(exchange.concat(targets));var cache=load(CACHE_KEY);if(rows.length){state.emptyConfirm=0;save(CACHE_KEY,{at:Date.now(),wallet:fp,rows:clone(rows)});}else{var authoritative=Boolean(window._walletHlReady)&&scanOk>0;if(authoritative)state.emptyConfirm++;else state.emptyConfirm=0;if(cache&&cache.wallet===fp&&Date.now()-n(cache.at,0)<120000&&Array.isArray(cache.rows)&&cache.rows.length&&state.emptyConfirm<2)rows=dedupe(clone(cache.rows));}
    st.exchange=rows.slice();st.engine=[];st.pending=rows.slice();window.__CTL_HL_PENDING_REAL_V19__=metrics(rows,pos,st);if(st.mode==='pending'&&typeof st.render==='function'&&!st.rendering){var aa=window._allPending,bb=window._sortedPending,cc=window._enginePositions;try{window._allPending=[];window._sortedPending=[];window._enginePositions=[];st.render();}catch(e){}finally{window._allPending=aa;window._sortedPending=bb;window._enginePositions=cc;}}return true;}
  state.tick=tick;tick();state.timer=setInterval(tick,POLL);return true;}
window.__ctlInstallHlPendingV19=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
