(function(){
'use strict';
var COMPAT='p0-p2-fee-aware+exact-child-oid+paginated-history+funding-separated';
var SELF=(document.currentScript&&document.currentScript.src)||location.href;
function src(name,q){try{return new URL(name+'?v='+q,SELF).href;}catch(e){return name+'?v='+q;}}
function add(id,name,q,onload){var old=document.getElementById(id);if(old)return false;var s=document.createElement('script');s.id=id;s.src=src(name,q);s.async=false;s.onload=function(){try{onload&&onload();}catch(e){}};s.onerror=function(){try{s.remove();}catch(e){}};(document.head||document.documentElement).appendChild(s);return true;}
function v31(){var st=window.__CTL_HISTORY_STABLE__,v=window.__CTL_REAL_METRICS_V31__;if(st&&v&&v.ready&&st.render&&st.render.__ctlV31)return true;if(typeof window.__ctlInstallRealMetricsV31==='function'){try{window.__ctlInstallRealMetricsV31();}catch(e){}v=window.__CTL_REAL_METRICS_V31__;if(st&&v&&v.ready&&st.render&&st.render.__ctlV31)return true;}add('ctlRealMetricsV31Script','history_real_metrics_v31.js','20260827-ledger-single-writer-3',function(){window.__ctlInstallRealMetricsV31&&window.__ctlInstallRealMetricsV31();});return false;}
function v32(){var x=window.__CTL_HL_LEDGER_V32__;if(x&&x.version>=32)return true;if(typeof window.__ctlInstallHlLedgerV32==='function'){try{window.__ctlInstallHlLedgerV32();}catch(e){}x=window.__CTL_HL_LEDGER_V32__;if(x&&x.version>=32)return true;}add('ctlHlLedgerV32Script','history_hl_ledger_v32.js','20260827-p0-p2-4',function(){window.__ctlInstallHlLedgerV32&&window.__ctlInstallHlLedgerV32();});return false;}
function v33(){var st=window.__CTL_HISTORY_STABLE__,x=window.__CTL_REAL_METRICS_V33__;if(st&&x&&x.ready&&st.render&&st.render.__ctlV33)return true;if(typeof window.__ctlInstallRealMetricsV33==='function'){try{window.__ctlInstallRealMetricsV33();}catch(e){}x=window.__CTL_REAL_METRICS_V33__;if(st&&x&&x.ready&&st.render&&st.render.__ctlV33)return true;}add('ctlRealMetricsV33Script','history_real_metrics_v33.js','20260827-p0-p2-5',function(){window.__ctlInstallRealMetricsV33&&window.__ctlInstallRealMetricsV33();});return false;}
function ready(){var st=window.__CTL_HISTORY_STABLE__,x=window.__CTL_REAL_METRICS_V33__;if(!(st&&x&&x.ready&&st.render&&st.render.__ctlV33))return false;st.render.__ctlV30=true;st.render.__ctlV29=true;st.render.__ctlV23=true;window.__CTL_REAL_METRICS_V30__={ready:true,version:34,source:COMPAT+'+v32-producer+v33-single-writer',delegate:x,lastLedger:x.lastLedger};return true;}
function step(){v31();v32();v33();return ready();}
function install(){var st=window.__CTL_HISTORY_STABLE__;if(!st||st.version<10||typeof st.render!=='function'){setTimeout(install,80);return false;}if(step())return true;var tries=0,t=setInterval(function(){tries++;if(step()||tries>120)clearInterval(t);},100);return false;}
window.__ctlInstallRealMetricsV30=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
