(function(){
'use strict';
var VERSION=33,EPS=1e-12,INNER=Object.getOwnPropertyDescriptor(Element.prototype,'innerHTML');
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function tm(v){if(typeof v==='number'&&Number.isFinite(v))return v;var x=Date.parse(v||'');return Number.isFinite(x)?x:0;}
function oid(v){return v==null?'':String(v);}
function acct(v){return String(v||'').toLowerCase();}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function money(v){if(v==null||!Number.isFinite(Number(v)))return'—';v=Number(v);return(v>=0?'+$':'-$')+Math.abs(v).toFixed(4);}
function pct(v){return v!=null&&Number.isFinite(Number(v))?Number(v).toFixed(2)+'%':'—';}
function rr(v){return v!=null&&Number.isFinite(Number(v))&&Number(v)>=0?Number(v).toFixed(2):'—';}
function state(){return window.__CTL_REAL_METRICS_V33__;}
function producer(){var p=window.__CTL_HL_LEDGER_V32__;return p&&p.ready?p:null;}
function entryCategory(f,p){var k=oid(f&&f._hlOid);if(k&&p.parentPending[k])return'pending';var cv=p.coverage&&p.coverage[acct(f&&f._hlAccount)]||{};if(cv.orderComplete===true)return'direct';var t=n(f&&f.time,0)||tm(f&&f.timestamp);if(n(cv.orderOldest,0)>0&&t>=n(cv.orderOldest))return'direct';return'unknown';}
function orderKey(f,idx){var a=acct(f&&f._hlAccount),k=oid(f&&f._hlOid);return k?a+'|OID|'+k:a+'|FALLBACK|'+coin(f&&f.symbol)+'|'+tm(f&&f.timestamp)+'|'+idx;}
function bucketKey(f){return acct(f&&f._hlAccount)+'|'+coin(f&&f.symbol);}
function build(p){var fills=(p.fills||[]).slice().sort(function(a,b){return(n(a.time,0)||tm(a.timestamp))-(n(b.time,0)||tm(b.timestamp));}),orders={},buckets={},fallback={pending:0,direct:0,unknown:0},rawNet=0,rawClosed=0,fees=0,unknownFee=0,exactChildCloses=0,fifoCloses=0,orphanCloses=0;
 function bucket(f){var k=bucketKey(f);return buckets[k]||(buckets[k]=[]);}
 function addEntry(f,q,idx){q=Math.abs(n(q,0));if(!(q>EPS))return;var k=orderKey(f,idx),cat=entryCategory(f,p),o=orders[k];if(!o){o=orders[k]={key:k,category:cat,initial:0,remaining:0,realized:0,first:n(f.time)||tm(f.timestamp),symbol:coin(f.symbol),account:acct(f._hlAccount),oid:oid(f._hlOid)};bucket(f).push(o);}else if(o.category==='unknown'&&cat!=='unknown')o.category=cat;o.initial+=q;o.remaining+=q;o.realized+=n(f._hlNetPnl,0);}
 function allocateTo(o,q,net){if(!o)return 0;var take=Math.min(Math.max(0,q),Math.max(0,o.remaining));if(!(take>EPS))return 0;o.realized+=net;o.remaining=Math.max(0,o.remaining-take);return take;}
 function allocClose(f,q,net){q=Math.abs(n(q,0));var parent=oid(f&&f._hlOid)&&p.childToParent[oid(f._hlOid)];if(parent){var exact=orders[acct(f._hlAccount)+'|OID|'+String(parent)];if(exact&&exact.remaining>EPS){var take=Math.min(q||exact.remaining,exact.remaining),share=(q>EPS?take/q:1);allocateTo(exact,take,net*share);if(share<1)fallback.pending+=net*(1-share);exactChildCloses++;return;}}
 var arr=bucket(f).filter(function(o){return o.remaining>EPS;}).sort(function(a,b){return a.first-b.first;}),left=q,usedNet=0;if(!arr.length){var c=parent?'pending':'unknown';fallback[c]+=net;orphanCloses++;return;}var totalQty=q>EPS?q:arr.reduce(function(s,o){return s+o.remaining;},0);for(var i=0;i<arr.length&&left>EPS;i++){var take=Math.min(left,arr[i].remaining),part=totalQty>EPS?net*(take/totalQty):0;allocateTo(arr[i],take,part);usedNet+=part;left-=take;}if(Math.abs(net-usedNet)>1e-10){var c2=parent?'pending':'unknown';fallback[c2]+=net-usedNet;}fifoCloses++;}
 fills.forEach(function(f,idx){if(!f)return;var cls=String(f._fillClass||'').toUpperCase(),q=Math.abs(n(f.volume,0)),net=n(f._hlNetPnl,0);rawNet+=net;rawClosed+=n(f._hlClosedPnl,0);fees+=n(f._hlFeeUsd,0);if(f._hlFeeKnown===false&&n(f._hlFee,0)>0)unknownFee++;if(cls==='ENTRY'||f.is_entry===true){addEntry(f,q,idx);return;}if(cls==='FLIP'){var arr=bucket(f),active=arr.reduce(function(s,o){return s+(o.remaining>EPS?o.remaining:0);},0),cq=Math.min(q,active),ratio=q>EPS?cq/q:0;if(cq>EPS)allocClose(f,cq,net*ratio);var oq=Math.max(0,q-cq);if(oq>EPS){var clone=Object.assign({},f,{_fillClass:'ENTRY',is_entry:true,_hlNetPnl:net*(1-ratio)});addEntry(clone,oq,idx);}return;}allocClose(f,q,net);});
 function metric(cat){var os=Object.keys(orders).map(function(k){return orders[k];}).filter(function(o){return cat==='all'||o.category===cat;}),fb=cat==='all'?fallback.pending+fallback.direct+fallback.unknown:fallback[cat],pnl=os.reduce(function(s,o){return s+n(o.realized);},0)+fb,closed=os.filter(function(o){return o.initial>EPS&&o.remaining<=Math.max(EPS,o.initial*1e-9);}),wins=closed.filter(function(o){return o.realized>EPS;}),losses=closed.filter(function(o){return o.realized<-EPS;}),gp=wins.reduce(function(s,o){return s+o.realized;},0),gl=Math.abs(losses.reduce(function(s,o){return s+o.realized;},0)),avgW=wins.length?gp/wins.length:0,avgL=losses.length?gl/losses.length:0,dec=wins.length+losses.length;return{pnl:pnl,entries:os.length,prob:dec?wins.length*100/dec:null,rr:avgL>EPS?avgW/avgL:null,closed:closed.length,wins:wins.length,losses:losses.length};}
 var pending=metric('pending'),direct=metric('direct'),unknown=metric('unknown'),all=metric('all');all.pnl=rawNet;all.entries=pending.entries+direct.entries+unknown.entries;var split=n(pending.pnl)+n(direct.pnl)+n(unknown.pnl),delta=all.pnl-split;return{all:all,pending:pending,direct:direct,unknown:unknown,rawNet:rawNet,rawClosedPnl:rawClosed,feesUsd:fees,fundingPnl:n(p.fundingPnl),accountPnl:rawNet+n(p.fundingPnl),feeUnknown:unknownFee,exactChildCloses:exactChildCloses,fifoCloses:fifoCloses,orphanCloses:orphanCloses,allocationDelta:delta,invariantPnl:Math.abs(delta)<1e-8,invariantEntries:all.entries===pending.entries+direct.entries+unknown.entries,classificationComplete:unknown.entries===0,coverage:p.coverage,fillCount:fills.length};}
function ensureBar(){var f=document.getElementById('historyTypeFilters');if(!f)return null;var b=document.getElementById('ctlHistoryPnlSummaryV11');if(!b){b=document.createElement('div');b.id='ctlHistoryPnlSummaryV11';f.parentNode.insertBefore(b,f);}b.style.cssText='display:flex;align-items:center;gap:32px;flex-wrap:wrap;margin:0 0 10px 0;padding:13px 16px;border:1px solid var(--border);border-radius:10px;background:rgba(5,14,26,.78);font-family:JetBrains Mono,monospace;font-size:12px;line-height:1.4;';if(!b.__ctlV33Lock&&INNER){try{Object.defineProperty(b,'innerHTML',{configurable:true,enumerable:true,get:function(){return INNER.get.call(this);},set:function(v){var s=state();if(!s||s.allow>0){INNER.set.call(this,String(v));return;}s.blocked++;}});b.__ctlV33Lock=true;}catch(e){}}return b;}
function span(l,v,c){return'<span><span style="color:var(--text-muted);font-weight:700">'+l+'</span> <b style="color:'+c+'">'+v+'</b></span>';}
function paint(){var p=producer(),st=window.__CTL_HISTORY_STABLE__,s=state();if(!p||!st||!s)return false;var l=build(p),mode=['all','pending','direct'].indexOf(st.mode)>=0?st.mode:'all',m=l[mode],b=ensureBar();if(!b)return false;var html=span('PNL',money(m.pnl),m.pnl>=0?'var(--green)':'var(--red)')+span('TOTAL ENTRY',String(m.entries),'var(--accent)')+span('PROBABILITAS',pct(m.prob),m.prob!=null&&m.prob>=50?'var(--green)':'var(--gold)')+span('RISK/REWARD',rr(m.rr),m.rr!=null&&m.rr>=1?'var(--green)':'var(--gold)');s.allow++;try{INNER.set.call(b,html);b.dataset.metricVersion=String(VERSION);b.dataset.metricMode=mode;b.dataset.feeAware=String(l.feeUnknown===0);b.dataset.classificationComplete=String(l.classificationComplete);b.dataset.invariantPnl=String(l.invariantPnl);b.dataset.realizedRr='avg-winner/avg-absolute-loser';b.title='V33 Hyperliquid Trading PNL after USDC fees. Funding is separate. Trading PNL '+money(l.all.pnl)+'; fees -$'+l.feesUsd.toFixed(4)+'; funding '+money(l.fundingPnl)+'; account PNL '+money(l.accountPnl)+'; fills '+l.fillCount+'; exact TP/SL child closes '+l.exactChildCloses+'; classification unknown '+l.unknown.entries+'. RISK/REWARD = realized average winner / average absolute loser.';}finally{s.allow--;}s.lastLedger=l;s.lastMode=mode;return true;}
function install(){var st=window.__CTL_HISTORY_STABLE__;if(!st||typeof st.render!=='function'){setTimeout(install,100);return false;}var old=state();if(old&&old.ready&&st.render.__ctlV33){paint();return true;}var v31=window.__CTL_REAL_METRICS_V31__;if(v31&&v31.timer)try{clearInterval(v31.timer);}catch(e){}if(v31)v31.disabledBy='v33-p0-p2';var base=v31&&typeof v31.baseRender==='function'?v31.baseRender:st.render,s={ready:true,version:VERSION,source:'fee-aware+exact-child-oid+paginated-ledger+funding-separated+single-summary-writer',baseRender:base,lastLedger:null,lastMode:'',allow:0,blocked:0,timer:null,lastError:''};window.__CTL_REAL_METRICS_V33__=s;function render(){var r=base.apply(st,arguments);paint();return r;}render.__ctlV33=true;render.__ctlV31=true;render.__ctlV30=true;render.__ctlV29=true;render.__ctlV23=base.__ctlV23===true||true;st.render=render;try{st.render();}catch(e){s.lastError=String(e&&e.message||e);paint();}window.addEventListener('ctl-hl-ledger-v32',paint);s.timer=setInterval(function(){try{paint();}catch(e){s.lastError=String(e&&e.message||e);}},1500);return true;}
window.__ctlInstallRealMetricsV33=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
