(function(){
'use strict';
var TICK=700;
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function fmtMoney(v){if(v==null||!Number.isFinite(Number(v)))return'—';v=Number(v);return(v>=0?'+$':'-$')+Math.abs(v).toFixed(4);}
function fmtPct(v){return v!=null&&Number.isFinite(Number(v))?Number(v).toFixed(2)+'%':'—';}
function fmtRR(v){return v!=null&&Number.isFinite(Number(v))&&Number(v)>=0?Number(v).toFixed(2):'—';}
function directMetrics(fills){var closed=(fills||[]).filter(function(x){return x&&!x.is_entry&&x.pnl!=null&&Math.abs(n(x.pnl,0))>1e-12;}),vals=closed.map(function(x){return n(x.pnl,0);}),wins=vals.filter(function(v){return v>0;}),loss=vals.filter(function(v){return v<0;}),pnl=vals.reduce(function(a,b){return a+b;},0),avgW=wins.length?wins.reduce(function(a,b){return a+b;},0)/wins.length:0,avgL=loss.length?Math.abs(loss.reduce(function(a,b){return a+b;},0)/loss.length):0,totalEntry=(fills||[]).filter(function(x){return x&&x.is_entry;}).length,prob=vals.length?wins.length*100/vals.length:null,rr=avgL>1e-12?avgW/avgL:null;return{pnl:pnl,entries:totalEntry,prob:prob,rr:rr,source:'userFills-realized'};}
function pendingMetrics(){var p=window.__CTL_HL_PENDING_REAL_V19__;if(p&&Date.now()-n(p.at,0)<180000)return p;return{pnl:null,entries:0,prob:null,rr:null,source:'no-active-pending'};}
function ensureBar(){var f=document.getElementById('historyTypeFilters');if(!f)return null;var b=document.getElementById('ctlHistoryPnlSummaryV11');if(!b){b=document.createElement('div');b.id='ctlHistoryPnlSummaryV11';f.parentNode.insertBefore(b,f);}b.style.cssText='display:none;align-items:center;gap:32px;flex-wrap:wrap;margin:0 0 10px 0;padding:13px 16px;border:1px solid var(--border);border-radius:10px;background:rgba(5,14,26,.78);font-family:JetBrains Mono,monospace;font-size:12px;line-height:1.4;';return b;}
function span(l,v,c,title){return'<span'+(title?' title="'+String(title).replace(/"/g,'&quot;')+'"':'')+'><span style="color:var(--text-muted);font-weight:700">'+l+'</span> <b style="color:'+c+'">'+v+'</b></span>';}
function paint(){var st=window.__CTL_HISTORY_STABLE__,bar=ensureBar();if(!st||st.version<10||!bar)return false;var mode=st.mode||window._historyTypeFilter||'all',info=document.getElementById('tradeLogInfo');if(mode!=='pending'&&mode!=='direct'){bar.style.display='none';if(info)info.style.display='';return true;}if(info)info.style.display='none';var m=mode==='pending'?pendingMetrics():directMetrics(Array.isArray(st.fills)?st.fills:[]),html='';html+=span('PNL',fmtMoney(m.pnl),m.pnl==null?'var(--text-muted)':(n(m.pnl)>=0?'var(--green)':'var(--red)'),mode==='pending'?'Floating PNL posisi Hyperliquid yang saat ini mempunyai SL/TP aktif atau target live terpasang.':'Realized PNL dari close/reduce fills Hyperliquid.');html+=span('TOTAL ENTRY',String(n(m.entries,0)),'var(--accent)',mode==='pending'?'Jumlah posisi Hyperliquid aktif yang mempunyai SL/TP/target pending.':'Jumlah open/add fills Hyperliquid.');html+=span('PROBABILITAS',fmtPct(m.prob),m.prob!=null&&n(m.prob)>=50?'var(--green)':'var(--gold)',mode==='pending'?'Win rate realized fills untuk pair yang saat ini mempunyai pending SL/TP.':'Win rate realized fills.');html+=span('RISK/REWARD',fmtRR(m.rr),m.rr!=null&&n(m.rr)>=1?'var(--green)':'var(--gold)',mode==='pending'?'Potensi TP dibagi risiko SL dari posisi pending aktif.':'Rata-rata realized win dibagi rata-rata realized loss.');bar.innerHTML=html;bar.style.display='flex';return true;}
function install(){['__CTL_HL_SUMMARY_V11__','__CTL_HL_SUMMARY_V12__','__CTL_HL_SUMMARY_V15__','__CTL_HL_SUMMARY_V16__','__CTL_HL_SUMMARY_V17__','__CTL_HL_SUMMARY_V18__','__CTL_HL_SUMMARY_V19__'].forEach(function(k){var x=window[k];if(x&&x.timer)try{clearInterval(x.timer);}catch(e){}if(x&&x.balanceTimer)try{clearInterval(x.balanceTimer);}catch(e){}});var s={ready:true,version:19,timer:setInterval(paint,TICK),paint:paint};window.__CTL_HL_SUMMARY_V19__=s;paint();return true;}
window.__ctlInstallHlSummaryV19=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
