(function(){
'use strict';
var HL='https://api.hyperliquid.xyz/info',POLL=6000,PAGE=20,DEX_CACHE_MS=300000;
function validWallet(v){return /^0x[a-fA-F0-9]{40}$/.test(String(v||'').trim());}
function uniq(a){var s={},o=[];(a||[]).forEach(function(v){v=String(v||'').trim().toLowerCase();if(validWallet(v)&&!s[v]){s[v]=1;o.push(v);}});return o;}
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function iso(v){var m=typeof v==='number'?v:Date.parse(v||'');return Number.isFinite(m)&&m>0?new Date(m).toISOString():'';}
function clone(a){try{return JSON.parse(JSON.stringify(a||[]));}catch(e){return Array.isArray(a)?a.slice():[];}}
function candidateWallet(){
  var c=[];
  try{if(typeof window.activeHyperliquidWallet==='function')c.push(window.activeHyperliquidWallet());}catch(e){}
  c.push(window._pagesHlActiveWallet,window._hlActiveWallet,window._hlSelectedWallet,window._hlAccountWallet,window._userWallet,window._userAddress);
  try{var u=JSON.parse(localStorage.getItem('session_user')||'null');if(u&&u.email)c.push(localStorage.getItem('ot_wallet_'+u.email));}catch(e){}
  for(var i=0;i<c.length;i++){var v=String(c[i]||'').trim().toLowerCase();if(validWallet(v))return v;}
  return '';
}
async function post(body,ms){var c=new AbortController(),t=setTimeout(function(){c.abort();},ms||10000);try{var r=await fetch(HL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HL '+r.status+' '+body.type);var d=await r.json();if(d&&d.error)throw new Error(String(d.error));return d;}finally{clearTimeout(t);}}
async function resolveAccounts(seed){
  var role=null,master=seed,active=seed;
  try{role=await post({type:'userRole',user:seed},7000);}catch(e){}
  var rn=String(role&&role.role||'').toLowerCase();
  if(rn==='agent'&&validWallet(role&&role.data&&role.data.user)){master=String(role.data.user).toLowerCase();active=master;}
  else if(rn==='subaccount'&&validWallet(role&&role.data&&role.data.master)){master=String(role.data.master).toLowerCase();active=seed;}
  var out=[active];
  if(rn!=='subaccount'){
    try{var subs=await post({type:'subAccounts',user:master},8000);if(Array.isArray(subs))subs.forEach(function(x){var a=String(x&&x.subAccountUser||'').toLowerCase();if(validWallet(a))out.push(a);});}catch(e){}
  }
  return {seed:seed,active:active,master:master,role:rn||'unknown',accounts:uniq(out)};
}
var dexCache={at:0,list:['']};
async function dexes(){
  if(Date.now()-dexCache.at<DEX_CACHE_MS&&dexCache.list.length)return dexCache.list.slice();
  var list=[''];
  try{var d=await post({type:'perpDexs'},9000);if(Array.isArray(d))d.forEach(function(x){var nm=String(x&&x.name||'').trim();if(nm&&list.indexOf(nm)<0)list.push(nm);});}catch(e){['xyz','km','vntl'].forEach(function(x){if(list.indexOf(x)<0)list.push(x);});}
  dexCache={at:Date.now(),list:list};return list.slice();
}
function isOpenDir(v){return /^open\b/i.test(String(v||'').trim());}
function normFill(f,acct){if(!f)return null;var tm=n(f.time,0)||Date.parse(f.timestamp||'')||0,dir=String(f.dir||'').trim(),open=isOpenDir(dir),side=String(f.side||'').toUpperCase(),buy=side==='B'||side==='BUY',c=coin(f.coin||f.symbol),p=n(f.px!=null?f.px:f.price,0),sz=n(f.sz!=null?f.sz:f.volume,0),pnl=open?null:n(f.closedPnl!=null?f.closedPnl:f.pnl,0);return{trade_id:f.tid||f.trade_id||f.oid||f.order_id||(acct+'-'+c+'-'+tm),timestamp:tm?new Date(tm).toISOString():iso(f.timestamp),symbol:c+'/USD',coin:c,type:buy?'BUY':'SELL',direction:dir||((buy?'BUY':'SELL')+(open?' OPEN':' FILL')),volume:sz,lot:sz,price:p,entry_price:p,pnl:pnl,is_entry:open,_hlDir:dir,_crossed:!!f.crossed,_hlAccount:acct,_hlOid:f.oid||null,_raw:f};}
function pendingKind(o){var txt=String((o&&o.orderType)||'')+' '+String((o&&o.triggerCondition)||'');txt=txt.toUpperCase();if(txt.indexOf('TAKE PROFIT')>=0||/(^|\W)TP(\W|$)/.test(txt))return'TP';if(txt.indexOf('STOP')>=0||/(^|\W)SL(\W|$)/.test(txt))return'SL';if(o&&(o.isTrigger||n(o.triggerPx,0)>0))return'TRIGGER';if(o&&o.isPositionTpsl)return'TP/SL';return'LIMIT';}
function normOrder(o,acct,dex,parent){if(!o)return null;parent=parent||{};var c=coin(o.coin||parent.coin||o.symbol),s=String(o.side||parent.side||'').toUpperCase(),sell=s==='A'||s==='SELL',trigger=n(o.triggerPx,0),limit=n(o.limitPx!=null?o.limitPx:o.px,0),tm=n(o.timestamp,0)||n(o.time,0)||n(parent.timestamp,0)||Date.now(),kind=pendingKind(o);return{order_id:o.oid||o.order_id||o.cloid||('hl-'+c+'-'+tm+'-'+kind),oid:o.oid||o.order_id||null,timestamp:new Date(tm).toISOString(),created_at:new Date(tm).toISOString(),symbol:c+'/USD',coin:c,type:sell?'SELL':'BUY',side:sell?'SELL':'BUY',direction:(sell?'SHORT':'LONG')+' · '+kind,volume:n(o.sz!=null?o.sz:(o.origSz!=null?o.origSz:parent.sz),0),lot:n(o.sz!=null?o.sz:(o.origSz!=null?o.origSz:parent.sz),0),price:trigger||limit,limit_price:limit,trigger_price:trigger,pnl:null,_logKind:'pending',_pendingKind:kind,_pendingSource:'HL_OPEN',_hlAccount:acct,_hlDex:dex||'main',_reduceOnly:!!o.reduceOnly,_isTrigger:!!o.isTrigger||trigger>0,_isPositionTpsl:!!o.isPositionTpsl,_orderType:String(o.orderType||''),_triggerCondition:String(o.triggerCondition||''),_raw:o};}
function flattenFrontendOrder(o,acct,dex,parent,out){out=out||[];if(!o)return out;var x=normOrder(o,acct,dex,parent);if(x)out.push(x);var kids=Array.isArray(o.children)?o.children:[];kids.forEach(function(ch){flattenFrontendOrder(ch,acct,dex,o,out);});return out;}
async function fetchFills(accts){var rs=await Promise.allSettled(accts.map(function(a){return post({type:'userFills',user:a,aggregateByTime:true},9500);})),all=[],ok=0;rs.forEach(function(r,i){if(r.status==='fulfilled'&&Array.isArray(r.value)){ok++;r.value.forEach(function(f){var x=normFill(f,accts[i]);if(x)all.push(x);});}});if(!ok)throw new Error('Semua userFills gagal');var seen={},out=[];all.forEach(function(x){var k=[x._hlAccount,x.trade_id,x.timestamp,x.symbol,x.price,x.volume].join('|');if(seen[k])return;seen[k]=1;out.push(x);});out.sort(function(a,b){return Date.parse(b.timestamp||0)-Date.parse(a.timestamp||0);});return out;}
async function fetchFrontend(accts,dxs){var tasks=[];accts.forEach(function(a){dxs.forEach(function(d){var b={type:'frontendOpenOrders',user:a};if(d)b.dex=d;tasks.push({a:a,d:d,p:post(b,9000)});});});var rs=await Promise.allSettled(tasks.map(function(x){return x.p;})),all=[],ok=0;rs.forEach(function(r,i){if(r.status==='fulfilled'&&Array.isArray(r.value)){ok++;r.value.forEach(function(o){flattenFrontendOrder(o,tasks[i].a,tasks[i].d,null,all);});}});return{ok:ok,attempted:tasks.length,rows:all};}
async function fetchBasic(accts,dxs){var tasks=[];accts.forEach(function(a){dxs.forEach(function(d){var b={type:'openOrders',user:a};if(d)b.dex=d;tasks.push({a:a,d:d,p:post(b,8500)});});});var rs=await Promise.allSettled(tasks.map(function(x){return x.p;})),all=[],ok=0;rs.forEach(function(r,i){if(r.status==='fulfilled'&&Array.isArray(r.value)){ok++;r.value.forEach(function(o){var x=normOrder(o,tasks[i].a,tasks[i].d);if(x)all.push(x);});}});return{ok:ok,attempted:tasks.length,rows:all};}
async function fetchHistoricalOpen(accts){var rs=await Promise.allSettled(accts.map(function(a){return post({type:'historicalOrders',user:a},10000);})),all=[],ok=0;rs.forEach(function(r,i){if(r.status==='fulfilled'&&Array.isArray(r.value)){ok++;r.value.forEach(function(row){if(String(row&&row.status||'').toLowerCase()!=='open')return;var o=row&&row.order?row.order:row;flattenFrontendOrder(o,accts[i],'historical',null,all);});}});return{ok:ok,attempted:accts.length,rows:all};}
function dedupeOrders(all){var seen={},out=[];(all||[]).forEach(function(x){if(!x)return;var k=[x._hlAccount,x.oid||x.order_id,x.symbol,x._pendingKind,x.trigger_price,x.limit_price,x.volume].join('|');if(seen[k])return;seen[k]=1;out.push(x);});out.sort(function(a,b){var ak=/^(TP|SL|TP\/SL|TRIGGER)$/.test(a._pendingKind)?0:1,bk=/^(TP|SL|TP\/SL|TRIGGER)$/.test(b._pendingKind)?0:1;if(ak!==bk)return ak-bk;return Date.parse(b.timestamp||0)-Date.parse(a.timestamp||0);});return out;}
async function fetchOpen(accts,dxs){
  var f=await fetchFrontend(accts,dxs),rows=f.rows.slice(),source='frontendOpenOrders';
  if(!rows.length){var b=await fetchBasic(accts,dxs);rows=rows.concat(b.rows);if(b.rows.length)source='openOrders';
    var h=await fetchHistoricalOpen(accts);if(h.rows.length){rows=rows.concat(h.rows);source=rows.length>h.rows.length?'openOrders+historicalOrders':'historicalOrders';}
    if(!f.ok&&!b.ok&&!h.ok)throw new Error('Semua open-order source Hyperliquid gagal');
  }
  return{rows:dedupeOrders(rows),source:source,frontendOk:f.ok,frontendAttempted:f.attempted};
}
function side(o){var s=String(o.side||o.direction||o.type||'').toUpperCase();return s.indexOf('SELL')>=0||s.indexOf('SHORT')>=0?'SELL':'BUY';}
function fmtTime(v){if(!v)return'-';var d=new Date(v);if(isNaN(d))return String(v).replace('T',' ').slice(0,19);return d.getFullYear()+'.'+String(d.getMonth()+1).padStart(2,'0')+'.'+String(d.getDate()).padStart(2,'0')+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')+':'+String(d.getSeconds()).padStart(2,'0');}
function fmtPx(v){v=n(v,0);if(!v)return'—';if(v>=1000)return v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});if(v>=1)return v.toFixed(5).replace(/0+$/,'').replace(/\.$/,'');return v.toFixed(7).replace(/0+$/,'').replace(/\.$/,'');}
function shortWallet(v){v=String(v||'');return v.length>12?v.slice(0,6)+'…'+v.slice(-4):v;}
function applyCanonicalPerf(){if(window._historySymbolFilter)return false;var p=window._hlPortfolio;if(!p)return false;var net=Number(p.netPnl),end=Number(p.endEquity),dd=Number(p.maxDDpct);if(!Number.isFinite(net)||!Number.isFinite(end))return false;var basis=end-net;function set(id,v,c){var e=document.getElementById(id);if(!e)return;if(e.textContent!==v)e.textContent=v;if(c&&e.style.color!==c)e.style.color=c;}set('statNetPnl',(net>=0?'+':'-')+'$'+Math.abs(net).toFixed(4),net>=0?'var(--green)':'var(--red)');if(basis>0.01){var g=net/basis*100;set('statGrowth',(g>=0?'+':'')+g.toFixed(2)+'%',g>=0?'var(--green)':'var(--red)');set('dInitDeposit','$'+basis.toFixed(2));}if(Number.isFinite(dd))set('statMaxDD',dd.toFixed(2)+'%','var(--red)');return true;}
function installPerfStability(){var old=window.__CTL_PERF_STABLE__;if(old&&old.version>=2){try{old.apply();}catch(e){}return old;}if(old&&old.timer)try{clearInterval(old.timer);}catch(e){}if(old&&old.observer)try{old.observer.disconnect();}catch(e){}var ctl={ready:true,version:2,source:'hyperliquid-portfolio-single-writer',observer:null,timer:null,wrapped:false,apply:applyCanonicalPerf};function wrapHistory(){var f=window.renderHistory;if(typeof f!=='function'||f.__ctlPerfStable)return;var wrapped=function(){var r=f.apply(this,arguments);applyCanonicalPerf();return r;};wrapped.__ctlPerfStable=true;wrapped.__ctlPerfOriginal=f;window.renderHistory=wrapped;ctl.wrapped=true;}wrapHistory();try{var obs=new MutationObserver(function(){applyCanonicalPerf();});['statNetPnl','statGrowth','statMaxDD','dInitDeposit'].forEach(function(id){var e=document.getElementById(id);if(e)obs.observe(e,{childList:true,subtree:true,characterData:true});});ctl.observer=obs;}catch(e){}ctl.timer=setInterval(function(){wrapHistory();applyCanonicalPerf();},1000);window.__CTL_PERF_STABLE__=ctl;applyCanonicalPerf();return ctl;}
function install(){
  var d=document,oldCtl=window.__CTL_HISTORY_STABLE__;try{if(oldCtl&&oldCtl.timer)clearInterval(oldCtl.timer);if(oldCtl&&oldCtl.observer)oldCtl.observer.disconnect();}catch(e){}
  var old=d.getElementById('historyTypeFilters'),tbody=d.getElementById('historyTableBody');if(!old||!tbody)return false;
  var filters=old.cloneNode(true);old.parentNode.replaceChild(filters,old);filters.querySelectorAll('.history-type-filter').forEach(function(b){b.removeAttribute('onclick');b.style.pointerEvents='auto';b.style.cursor='pointer';});
  var ctl={ready:true,version:6,source:'hyperliquid-userfills+real-open-orders-v6',mode:'all',fills:[],hlOpen:[],accounts:[],dexes:[],accountInfo:null,openSource:'',shown:0,polling:false,lastGood:0,lastOpenGood:0,lastError:'',emptyOpenConfirmations:0,page:PAGE};window.__CTL_HISTORY_STABLE__=ctl;installPerfStability();
  function selected(){if(ctl.mode==='direct')return ctl.fills.filter(function(x){return x.is_entry;});if(ctl.mode==='pending')return ctl.hlOpen;return ctl.fills;}
  function active(){filters.querySelectorAll('.history-type-filter').forEach(function(b){var a=b.dataset.historyType===ctl.mode;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a?'true':'false');});}
  function info(rows){var el=d.getElementById('tradeLogInfo');if(!el)return;var stamp=ctl.lastGood?new Date(ctl.lastGood).toLocaleTimeString('id-ID',{hour12:false}):'—';if(ctl.mode==='all')el.textContent='Hyperliquid fills · '+ctl.fills.length+' fills · menampilkan '+Math.min(rows.length,ctl.shown)+' · sync '+stamp;else if(ctl.mode==='direct')el.textContent='LANGSUNG ENTRY · '+rows.length+' open fills · Hyperliquid · sync '+stamp;else{var tpsl=ctl.hlOpen.filter(function(x){return /^(TP|SL|TP\/SL|TRIGGER)$/.test(String(x._pendingKind||''));}).length;el.textContent='PENDING ORDER · HL open '+ctl.hlOpen.length+' · TP/SL '+tpsl+' · '+(ctl.openSource||'Hyperliquid')+' · sync '+stamp;}el.style.color=ctl.lastError?'var(--gold)':'var(--green)';var ai=ctl.accountInfo||{};el.title='Hyperliquid actual account '+shortWallet(ai.active||'')+' · role '+String(ai.role||'unknown')+' · accounts '+ctl.accounts.length+' · dex '+ctl.dexes.length+(ctl.lastError?' · '+ctl.lastError:'');}
  function empty(rows){var e=d.getElementById('emptyHistory'),t=d.getElementById('historyTable');if(rows.length){if(e)e.style.display='none';if(t)t.style.display='';return;}if(t)t.style.display='none';if(!e)return;e.style.display='';var a=e.querySelector('.text'),b=e.querySelector('.sub');if(ctl.mode==='pending'){if(a)a.textContent='Tidak ada Pending Order aktif';if(b)b.textContent='Hyperliquid mengembalikan 0 open order untuk account aktif setelah verifikasi frontendOpenOrders/openOrders/historicalOrders.';}else if(ctl.mode==='direct'){if(a)a.textContent='Tidak ada open fill pada history Hyperliquid';if(b)b.textContent='LANGSUNG ENTRY hanya menampilkan fill dengan dir Open Long / Open Short.';}else{if(a)a.textContent='Belum ada fill Hyperliquid';if(b)b.textContent='Data akan muncul langsung dari userFills account aktif.';}}
  function openChart(x){try{if(typeof window.openPendingChart==='function')window.openPendingChart(x.symbol,x.price||x.entry_price,0,0,x.direction||x.type,ctl.mode==='pending'?(x._pendingKind||'PENDING'):'HL',String(x.trade_id||x.order_id||''));}catch(e){}}
  function render(){active();var rows=selected(),max=Math.min(rows.length,ctl.shown||PAGE);tbody.innerHTML='';for(var i=0;i<max;i++){(function(x,idx){var tr=d.createElement('tr'),entry=!!x.is_entry,pnl=x.pnl==null?'—':((n(x.pnl)>=0?'+$':'-$')+Math.abs(n(x.pnl)).toFixed(4)),kind=ctl.mode==='pending'?(x._pendingKind||'PENDING'):(entry?'ENTRY':'CLOSE'),dir=ctl.mode==='pending'?(x._triggerCondition||x._orderType||x.direction||side(x)):(x._hlDir||x.direction||kind),color=x.pnl==null?'var(--text-muted)':(n(x.pnl)>=0?'var(--green)':'var(--red)');tr.style.cursor='pointer';tr.title=ctl.mode==='pending'?((x._orderType||kind)+' · '+(x._triggerCondition||'HL open order')):'Klik: lihat chart';tr.innerHTML='<td style="color:var(--text-muted);font-size:11px">'+fmtTime(x.timestamp||x.created_at)+'</td><td>'+(idx+1)+'</td><td style="font-weight:700">'+String(x.symbol||'-')+'</td><td class="'+(side(x)==='BUY'?'side-long':'side-short')+'" style="font-weight:800">'+side(x)+'</td><td title="'+String(dir).replace(/"/g,'&quot;')+'" style="font-weight:800">'+kind+'</td><td>'+String(x.volume!=null?x.volume:(x.lot||0))+'</td><td>'+fmtPx(x.trigger_price||x.price||x.entry_price)+'</td><td style="color:'+color+';font-weight:800">'+pnl+'</td><td style="font-weight:700;color:var(--text-muted)">HL</td>';tr.addEventListener('click',function(){openChart(x);});tbody.appendChild(tr);})(rows[i],i);}ctl.shown=max;var wrap=d.getElementById('loadMoreDealsWrap'),btn=d.getElementById('loadMoreDealsBtn');if(wrap){if(max<rows.length){wrap.style.display='';if(btn)btn.textContent='📋 Load More +'+Math.min(PAGE,rows.length-max)+' ('+(rows.length-max)+' remaining)';}else wrap.style.display='none';}empty(rows);info(rows);}
  ctl.setMode=function(m){ctl.mode=['all','pending','direct'].indexOf(m)>=0?m:'all';window._historyTypeFilter=ctl.mode;ctl.shown=PAGE;render();};ctl.loadMore=function(){ctl.shown=Math.min(selected().length,(ctl.shown||PAGE)+PAGE);render();};window._loadMoreDeals=ctl.loadMore;window.setHistoryTypeFilter=ctl.setMode;
  filters.addEventListener('click',function(ev){var b=ev.target.closest&&ev.target.closest('.history-type-filter');if(!b||!filters.contains(b))return;ev.preventDefault();ev.stopPropagation();ctl.setMode(b.dataset.historyType||'all');},true);
  async function poll(){if(ctl.polling)return;var seed=candidateWallet();if(!seed){ctl.lastError='wallet Hyperliquid aktif belum tersedia';info(selected());return;}ctl.polling=true;try{var ai=await resolveAccounts(seed),dxs=await dexes();ctl.accountInfo=ai;ctl.accounts=ai.accounts;ctl.dexes=dxs;var r=await Promise.allSettled([fetchFills(ai.accounts),fetchOpen(ai.accounts,dxs)]);if(r[0].status==='fulfilled'){var nf=r[0].value;if(nf.length||!ctl.fills.length)ctl.fills=nf;window._allFillsForLog=clone(ctl.fills);window._tradeLogAllFills=clone(ctl.fills);}if(r[1].status==='fulfilled'){var o=r[1].value,rows=o.rows||[];ctl.openSource=o.source||'Hyperliquid';if(rows.length){ctl.hlOpen=rows;ctl.emptyOpenConfirmations=0;ctl.lastOpenGood=Date.now();}else{ctl.emptyOpenConfirmations++;if(ctl.emptyOpenConfirmations>=2)ctl.hlOpen=[];}}
    if(r[0].status==='rejected'&&r[1].status==='rejected')throw r[0].reason||r[1].reason;ctl.lastGood=Date.now();ctl.lastError='';render();
  }catch(e){ctl.lastError=String(e&&e.message||e);render();}finally{ctl.polling=false;}}
  ctl.poll=poll;ctl.timer=setInterval(poll,POLL);ctl.setMode(window._historyTypeFilter||'all');poll();return true;
}
window.__ctlInstallHlHistoryV5=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
