(function(){
'use strict';
var HL='https://api.hyperliquid.xyz/info',POLL=10000,CACHE='ctl_hl_pending_active_v18',HIST_CACHE='ctl_hl_pending_hist_v18';
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function valid(v){return /^0x[a-fA-F0-9]{40}$/.test(String(v||'').trim());}
function lower(v){return valid(v)?String(v).trim().toLowerCase():'';}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function uniq(a){var s={},o=[];(a||[]).forEach(function(v){v=lower(v);if(v&&!s[v]){s[v]=1;o.push(v);}});return o;}
function add(a,v){v=lower(v);if(v&&a.indexOf(v)<0)a.push(v);}
function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
function tm(v){if(typeof v==='number'&&Number.isFinite(v))return v;var x=Date.parse(v||'');return Number.isFinite(x)?x:0;}
function save(k,x){try{localStorage.setItem(k,JSON.stringify(x));}catch(e){try{sessionStorage.setItem(k,JSON.stringify(x));}catch(_){}}}
function load(k){var x=null;try{x=JSON.parse(localStorage.getItem(k)||'null');}catch(e){}if(!x)try{x=JSON.parse(sessionStorage.getItem(k)||'null');}catch(e){}return x;}
async function post(body,ms){var c=new AbortController(),t=setTimeout(function(){c.abort();},ms||8500);try{var r=await fetch(HL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HL '+r.status+' '+body.type);var d=await r.json();if(d&&d.error)throw new Error(String(d.error));return d;}finally{clearTimeout(t);}}
function seeds(){var a=[],st=window.__CTL_HISTORY_STABLE__;if(st&&Array.isArray(st.fills))st.fills.slice(0,500).forEach(function(x){add(a,x&&x._hlAccount);});add(a,window._hlAccountWallet);add(a,window._userWallet);add(a,window._hlActiveWallet);add(a,window._hlSelectedWallet);add(a,window._pagesHlActiveWallet);var c=load(CACHE);if(c&&Array.isArray(c.accounts))c.accounts.forEach(function(x){add(a,x);});return uniq(a).slice(0,10);}
async function family(base){var out=uniq(base),masters=[];await Promise.all(out.slice(0,6).map(async function(a){try{var r=await post({type:'userRole',user:a},5000),role=String(r&&r.role||'').toLowerCase();if(role==='agent'&&valid(r&&r.data&&r.data.user)){add(out,r.data.user);add(masters,r.data.user);}else if(role==='subaccount'&&valid(r&&r.data&&r.data.master)){add(out,r.data.master);add(masters,r.data.master);}else if(role==='user')add(masters,a);}catch(e){}}));for(var i=0;i<masters.length&&i<4;i++){try{var s=await post({type:'subAccounts',user:masters[i]},6000);if(Array.isArray(s))s.forEach(function(x){add(out,x&&x.subAccountUser);});}catch(e){}}return uniq(out).slice(0,12);}
var dexCache={at:0,list:['']};
async function dexes(){if(Date.now()-dexCache.at<300000)return dexCache.list.slice();var o=[''];try{var d=await post({type:'perpDexs'},6000);if(Array.isArray(d))d.forEach(function(x){var nm=typeof x==='string'?x:(x&&x.name)||'';nm=String(nm||'').trim();if(nm&&o.indexOf(nm)<0)o.push(nm);});}catch(e){}dexCache={at:Date.now(),list:o.slice(0,10)};return dexCache.list.slice();}
function kind(o){var t=(String(o&&o.orderType||'')+' '+String(o&&o.triggerCondition||'')+' '+String(o&&o.tpsl||'')).toUpperCase();if(t.indexOf('TAKE PROFIT')>=0||/(^|\W)TP(\W|$)/.test(t))return'TP';if(t.indexOf('STOP')>=0||/(^|\W)SL(\W|$)/.test(t))return'SL';if(o&&(o.isPositionTpsl||o.isPositionTpSl))return'TPSL';if(o&&(o.isTrigger||n(o.triggerPx,0)>0))return'TRIGGER';return'OTHER';}
function normOrder(o,a,d,parent,source){if(!o)return null;parent=parent||{};var k=kind(o),px=n(o.triggerPx,0)||n(o.limitPx!=null?o.limitPx:o.px,0),sz=Math.abs(n(o.sz!=null?o.sz:(o.origSz!=null?o.origSz:parent.sz),0));if(k==='OTHER'||!(px>0&&sz>0))return null;var c=coin(o.coin||parent.coin||o.symbol),s=String(o.side||parent.side||'').toUpperCase(),sell=s==='A'||s==='SELL',t=n(o.timestamp,0)||n(o.time,0)||n(parent.timestamp,0)||Date.now();return{order_id:o.oid||o.order_id||o.cloid||('v18-'+a+'-'+c+'-'+k+'-'+px+'-'+sz),oid:o.oid||o.order_id||null,timestamp:new Date(t).toISOString(),symbol:c+'/USD',coin:c,type:sell?'SELL':'BUY',side:sell?'SELL':'BUY',direction:k+' · REDUCE',volume:sz,lot:sz,price:px,trigger_price:px,pnl:null,_pendingKind:k,_pendingSource:source||'HL_OPEN_ACTIVE',_hlAccount:a,_hlDex:d||'main',_reduceOnly:o.reduceOnly!==false,_orderType:String(o.orderType||''),_triggerCondition:String(o.triggerCondition||'')};}
function flatten(o,a,d,parent,out,source){out=out||[];if(!o)return out;var x=normOrder(o,a,d,parent,source);if(x)out.push(x);(Array.isArray(o.children)?o.children:[]).forEach(function(ch){flatten(ch,a,d,o,out,source);});return out;}
function key(x){return [x._hlAccount||'',x.symbol||'',x.side||'',x._pendingKind||'',n(x.trigger_price||x.price).toPrecision(12),Math.abs(n(x.volume)).toPrecision(12)].join('|');}
function dedupe(rows){var s={},o=[];(rows||[]).forEach(function(x){if(!x)return;var k=key(x);if(!s[k]){s[k]=1;o.push(x);}});o.sort(function(a,b){return tm(b.timestamp)-tm(a.timestamp);});return o;}
function posKey(a,c,d){return lower(a)+'|'+String(d||'main')+'|'+coin(c);}
function historicalStatusOpen(w){var s=String(w&&w.status||'').toLowerCase();return s==='open'||s==='pending'||s==='resting'||s==='scheduled';}
function historicalStatusHit(w){var s=String(w&&w.status||'').toLowerCase();return s==='filled'||s==='triggered'||s==='executed';}
async function fetchCurrent(ac,dx){var tasks=[];ac.forEach(function(a){dx.forEach(function(d){['frontendOpenOrders','openOrders','clearinghouseState'].forEach(function(type){var b={type:type,user:a};if(d)b.dex=d;tasks.push({a:a,d:d,type:type,p:post(b,7500)});});});});var rs=await Promise.allSettled(tasks.map(function(x){return x.p;})),orders=[],positions={},okOrders=0,okPos=0;rs.forEach(function(r,i){if(r.status!=='fulfilled')return;var t=tasks[i];if((t.type==='frontendOpenOrders'||t.type==='openOrders')&&Array.isArray(r.value)){okOrders++;r.value.forEach(function(o){flatten(o,t.a,t.d,null,orders,'HL_OPEN_ACTIVE');});}else if(t.type==='clearinghouseState'&&r.value&&typeof r.value==='object'){okPos++;(Array.isArray(r.value.assetPositions)?r.value.assetPositions:[]).forEach(function(w){var p=w&&w.position;if(!p)return;var q=Math.abs(n(p.szi,0));if(!(q>0))return;positions[posKey(t.a,p.coin,t.d)]={account:t.a,dex:t.d||'main',coin:coin(p.coin),szi:n(p.szi,0),qty:q,entry:n(p.entryPx,0),upnl:n(p.unrealizedPnl,0)};});}});return{orders:dedupe(orders),positions:positions,okOrders:okOrders,okPos:okPos};}
async function fetchHistory(ac){var tasks=ac.map(function(a){return{a:a,p:post({type:'historicalOrders',user:a},9000)};}),rs=await Promise.allSettled(tasks.map(function(x){return x.p;})),openRows=[],tpHit=0,slHit=0,ok=0;rs.forEach(function(r,i){if(r.status!=='fulfilled'||!Array.isArray(r.value))return;ok++;r.value.forEach(function(w){var raw=w&&w.order?w.order:w,k=kind(raw);if(k==='OTHER')return;if(historicalStatusOpen(w)){var x=normOrder(raw,tasks[i].a,'',null,'HL_HISTORY_OPEN');if(x)openRows.push(x);}if(historicalStatusHit(w)){if(k==='TP')tpHit++;else if(k==='SL')slHit++;}});});return{open:dedupe(openRows),tpHit:tpHit,slHit:slHit,ok:ok};}
function matchPosition(o,positions){var exact=positions[posKey(o._hlAccount,o.coin,o._hlDex)],fallback=null;if(exact)return exact;Object.keys(positions).some(function(k){var p=positions[k];if(p.account===o._hlAccount&&p.coin===coin(o.coin)){fallback=p;return true;}return false;});return fallback;}
function metrics(active,positions,hist){var groups={},pnl=0,reward=0,risk=0;active.forEach(function(o){var p=matchPosition(o,positions);if(!p||!(p.entry>0&&p.qty>0))return;var gk=[p.account,p.dex,p.coin].join('|'),g=groups[gk]||(groups[gk]={p:p,tp:[],sl:[]}),px=n(o.trigger_price||o.price,0),k=String(o._pendingKind||'').toUpperCase();if(k==='TP')g.tp.push(px);else if(k==='SL')g.sl.push(px);else if(k==='TRIGGER'||k==='TPSL'){var favorable=p.szi>0?px>p.entry:px<p.entry;(favorable?g.tp:g.sl).push(px);}});Object.keys(groups).forEach(function(k){var g=groups[k],p=g.p;var bestReward=0,bestRisk=0;g.tp.forEach(function(px){var v=p.szi>0?(px-p.entry)*p.qty:(p.entry-px)*p.qty;if(v>bestReward)bestReward=v;});g.sl.forEach(function(px){var v=p.szi>0?(p.entry-px)*p.qty:(px-p.entry)*p.qty;if(v>bestRisk)bestRisk=v;});pnl+=p.upnl;reward+=Math.max(0,bestReward);risk+=Math.max(0,bestRisk);});var decisions=n(hist.tpHit)+n(hist.slHit),prob=decisions?hist.tpHit*100/decisions:null;return{pnl:Object.keys(groups).length?pnl:null,entries:Object.keys(groups).length,prob:prob,rr:risk>1e-12?reward/risk:null,reward:reward,risk:risk,tpHits:hist.tpHit,slHits:hist.slHit,orders:active.length,at:Date.now(),source:'active-open-orders-v18'};}
async function poll(){var st=window.__CTL_HISTORY_STABLE__;if(!st||st.version<10)return false;var ac=await family(seeds());if(!ac.length)return false;var dx=await dexes(),r=await Promise.allSettled([fetchCurrent(ac,dx),fetchHistory(ac)]),cur=r[0].status==='fulfilled'?r[0].value:{orders:[],positions:{},okOrders:0,okPos:0},hist=r[1].status==='fulfilled'?r[1].value:{open:[],tpHit:0,slHit:0,ok:0};var active=dedupe(cur.orders.concat(hist.open));var m=metrics(active,cur.positions,hist);if(cur.okOrders>0||hist.ok>0){st.exchange=active;st.engine=[];st.pending=active.slice();window.__CTL_HL_PENDING_REAL_V18__=m;save(HIST_CACHE,{at:Date.now(),tpHit:hist.tpHit,slHit:hist.slHit});if(active.length||m.entries>0){save(CACHE,{at:Date.now(),accounts:ac,orders:active,metrics:m});}else{save(CACHE,{at:Date.now(),accounts:ac,orders:[],metrics:m});}if(st.mode==='pending'&&typeof st.render==='function'&&!st.rendering)try{st.render();}catch(e){}return true;}var c=load(CACHE);if(c&&Date.now()-n(c.at,0)<120000&&Array.isArray(c.orders)){st.exchange=clone(c.orders);st.pending=clone(c.orders);window.__CTL_HL_PENDING_REAL_V18__=c.metrics||null;if(st.mode==='pending'&&typeof st.render==='function'&&!st.rendering)try{st.render();}catch(e){}}return false;}
function install(){var old=window.__CTL_HL_PENDING_V18__;if(old&&old.timer)try{clearInterval(old.timer);}catch(e){}var s={ready:true,version:18,timer:null,poll:poll};window.__CTL_HL_PENDING_V18__=s;poll();s.timer=setInterval(poll,POLL);return true;}
window.__ctlInstallHlPendingV18=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();