(function(){
'use strict';
var VERSION=23,POLL=600;
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function tm(v){if(typeof v==='number'&&Number.isFinite(v))return v;var x=Date.parse(v||'');return Number.isFinite(x)?x:0;}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function px(o){return n(o&&((o.trigger_price!=null?o.trigger_price:(o.triggerPx!=null?o.triggerPx:(o.price!=null?o.price:(o.limitPx!=null?o.limitPx:0))))),0);}
function qty(o){return Math.abs(n(o&&((o.volume!=null?o.volume:(o.lot!=null?o.lot:(o.sz!=null?o.sz:(o.origSz!=null?o.origSz:o.szi))))),0));}
function rawKind(o){return (String(o&&o._pendingKind||'')+' '+String(o&&o.direction||'')+' '+String(o&&o.pool_status||'')+' '+String(o&&o.order_type||'')+' '+String(o&&o.orderType||'')+' '+String(o&&o.triggerCondition||'')+' '+String(o&&o.tpsl||'')).toUpperCase();}
function kind(o){var t=rawKind(o);if(t.indexOf('TAKE PROFIT')>=0||/(^|\W)TP(\W|$)/.test(t))return'TP';if(t.indexOf('STOP LOSS')>=0||t.indexOf('STOP')>=0||/(^|\W)SL(\W|$)/.test(t))return'SL';return'';}
function livePositions(){var out=[];(Array.isArray(window._hlPosLive)?window._hlPosLive:[]).forEach(function(p){if(!p)return;var c=coin(p.coin||p.displayCoin||p.symbolKey||p.symbol),q=Math.abs(n(p.szi!=null?p.szi:(p.volume!=null?p.volume:p.lot),0)),e=n(p.entry!=null?p.entry:(p.entryPx!=null?p.entryPx:p.entry_price),0);if(c==='-'||!(q>0&&e>0))return;out.push({coin:c,raw:String(p.coin||p.displayCoin||p.symbolKey||p.symbol||''),szi:n(p.szi!=null?p.szi:(String(p.side||'').toUpperCase()==='SHORT'?-q:q),0),qty:q,entry:e,upnl:n(p.upnl,0),account:String(p._hlAccount||window._hlAccountWallet||window._userWallet||'')});});return out;}
function posFor(c){var p=livePositions();for(var i=0;i<p.length;i++)if(p[i].coin===c)return p[i];return null;}
function inferredKind(o){var k=kind(o);if(k)return k;var c=coin(o&& (o.symbol||o.coin||o._coinRaw)),p=posFor(c),v=px(o);if(!p||!(v>0))return'';if(p.szi>=0)return v>p.entry?'TP':(v<p.entry?'SL':'');return v<p.entry?'TP':(v>p.entry?'SL':'');}
function normalize(o,source){if(!o)return null;var c=coin(o.symbol||o.coin||o._coinRaw),v=px(o),q=qty(o),k=inferredKind(o);if(c==='-'||!(v>0&&q>0)||!k)return null;var p=posFor(c),s=String(o.side||o.type||'').toUpperCase(),sell=s==='A'||s==='SELL'||s.indexOf('SHORT')>=0;if(!s&&p)sell=p.szi>=0;return Object.assign({},o,{trade_id:o.trade_id||o.order_id||o.oid||('v23-'+c+'-'+k+'-'+v+'-'+q),timestamp:o.timestamp||o.created_at||new Date().toISOString(),symbol:c+'/USD',coin:c,type:sell?'SELL':'BUY',side:sell?'SELL':'BUY',direction:k+' · ACTIVE',volume:q,lot:q,price:v,trigger_price:v,pnl:o.pnl==null?null:n(o.pnl),_pendingKind:k,_status:'OPEN',_source:source||o._source||o._pendingSource||'HL_ACTIVE_TPSL'});}
function fallbackRows(){var out=[],pos=livePositions(),map=window._hlSlTpByCoin||{};pos.forEach(function(p){var real=map[p.raw]||map[p.coin]||{},cands=(Array.isArray(window._enginePositions)?window._enginePositions:[]).concat(Array.isArray(window._allPending)?window._allPending:[]).concat(Array.isArray(window._sortedPending)?window._sortedPending:[]).filter(function(x){return coin(x&&(x.symbol||x.coin||x._coinRaw))===p.coin;});var sl=n(real.sl,0),tp=n(real.tp,0);cands.forEach(function(x){if(!(sl>0))sl=n(x&&(x.stop_loss!=null?x.stop_loss:(x.sl!=null?x.sl:x.stopLoss)),0);if(!(tp>0))tp=n(x&&(x.take_profit!=null?x.take_profit:(x.tp!=null?x.tp:x.takeProfit)),0);});function add(k,v){if(!(v>0))return;var sell=p.szi>=0;out.push(normalize({order_id:'fallback-'+p.coin+'-'+k+'-'+v,timestamp:new Date().toISOString(),symbol:p.coin+'/USD',side:sell?'SELL':'BUY',volume:p.qty,trigger_price:v,_pendingKind:k,_hlAccount:p.account},'POSITION_TPSL'));}add('SL',sl);add('TP',tp);});return out;}
function dedupe(rows){var seen={},out=[];(rows||[]).forEach(function(o){var x=normalize(o,o&&o._pendingSource);if(!x)return;var k=[coin(x.symbol),x._pendingKind,n(x.trigger_price||x.price).toPrecision(12),qty(x).toPrecision(12)].join('|');if(seen[k])return;seen[k]=1;out.push(x);});out.sort(function(a,b){return tm(b.timestamp)-tm(a.timestamp);});return out;}
function activeRows(st){var src=[];function add(a){if(Array.isArray(a))src=src.concat(a);}add(st&&st.pending);add(window._hlRealPending);add(window._allPending);add(window._sortedPending);add(fallbackRows());return dedupe(src);}
function fingerprint(rows){return(rows||[]).map(function(x){return[coin(x.symbol),x._pendingKind,n(x.trigger_price||x.price),qty(x)].join(':');}).join('|');}
function fmtMoney(v){if(v==null||!Number.isFinite(Number(v)))return'—';v=Number(v);return(v>=0?'+$':'-$')+Math.abs(v).toFixed(4);}
function fmtPct(v){return v!=null&&Number.isFinite(Number(v))?Number(v).toFixed(2)+'%':'—';}
function fmtRR(v){return v!=null&&Number.isFinite(Number(v))&&Number(v)>=0?Number(v).toFixed(2):'—';}
function paintSummary(rows){var b=document.getElementById('ctlHistoryPnlSummaryV11');if(!b)return;var m=window.__CTL_HL_PENDING_REAL_V19__||{},symbols={};rows.forEach(function(r){symbols[coin(r.symbol)]=1;});var entries=n(m.entries,0)>0?n(m.entries,0):Object.keys(symbols).length,pnl=m.pnl==null?null:n(m.pnl),prob=m.prob==null?null:n(m.prob),rr=m.rr==null?null:n(m.rr);function sp(l,v,c){return'<span><span style="color:var(--text-muted);font-weight:700">'+l+'</span> <b style="color:'+c+'">'+v+'</b></span>';}b.style.display='flex';b.innerHTML=sp('PNL',fmtMoney(pnl),pnl==null?'var(--text-muted)':(pnl>=0?'var(--green)':'var(--red)'))+sp('TOTAL ENTRY',String(entries),'var(--accent)')+sp('PROBABILITAS',fmtPct(prob),prob!=null&&prob>=50?'var(--green)':'var(--gold)')+sp('RISK/REWARD',fmtRR(rr),rr!=null&&rr>=1?'var(--green)':'var(--gold)');}
function paintEmpty(rows){if(rows.length)return;var e=document.getElementById('emptyHistory');if(!e)return;var a=e.querySelector('.text'),b=e.querySelector('.sub');if(a)a.textContent='Belum ada TP/SL aktif Hyperliquid';if(b)b.textContent='PENDING ORDER hanya menampilkan order/posisi yang memiliki Stop Loss atau Take Profit aktif.';}
function ensureChartSingleWriter(){var base=document.getElementById('equityChart'),overlay=document.getElementById('ctlEquityChartV22');if(!base)return false;var style=document.getElementById('ctlV23ChartSingleWriterStyle');if(!style){style=document.createElement('style');style.id='ctlV23ChartSingleWriterStyle';style.textContent='#equityChart{visibility:hidden!important;opacity:0!important}#ctlEquityChartV22{visibility:visible!important;opacity:1!important}';(document.head||document.documentElement).appendChild(style);}base.style.setProperty('visibility','hidden','important');base.style.setProperty('opacity','0','important');if(overlay){overlay.style.setProperty('visibility','visible','important');overlay.style.setProperty('opacity','1','important');overlay.style.setProperty('z-index','20','important');}return !!overlay;}
function ensureV19(){if(window.__CTL_HL_PENDING_V19__&&window.__CTL_HL_PENDING_V19__.ready)return true;if(typeof window.__ctlInstallHlPendingV19==='function'){try{window.__ctlInstallHlPendingV19();}catch(e){}return !!(window.__CTL_HL_PENDING_V19__&&window.__CTL_HL_PENDING_V19__.ready);}if(document.getElementById('ctlHlPendingV19ForV23'))return false;var s=document.createElement('script');s.id='ctlHlPendingV19ForV23';s.src='history_hl_pending_v19.js?v=20260827-v23-active';s.async=false;s.onload=function(){try{window.__ctlInstallHlPendingV19&&window.__ctlInstallHlPendingV19();}catch(e){}};(document.head||document.documentElement).appendChild(s);return false;}
function install(){var st=window.__CTL_HISTORY_STABLE__,m=window.__CTL_HISTORY_MODE_V20__;if(!st||st.version<10||!m||!m.ready){setTimeout(install,120);return false;}var old=window.__CTL_HL_FIX_V23__;if(old&&old.timer)try{clearInterval(old.timer);}catch(e){}var baseRender=(st.render&&st.render.__ctlV23Base)?st.render.__ctlV23Base:st.render,state={ready:true,version:VERSION,timer:null,lastFp:'',baseRender:baseRender,source:'active-tpsl+chart-single-writer'};window.__CTL_HL_FIX_V23__=state;
  function render(){var rows=null;if(st.mode==='pending'){rows=activeRows(st);m.triggerRows=rows;}var r=state.baseRender.apply(st,arguments);if(st.mode==='pending'){paintSummary(rows||[]);paintEmpty(rows||[]);}ensureChartSingleWriter();return r;}render.__ctlV23=true;render.__ctlV23Base=baseRender;st.render=render;
  function tick(){ensureV19();ensureChartSingleWriter();if(st.mode==='pending'){var rows=activeRows(st),fp=fingerprint(rows);if(fp!==state.lastFp){state.lastFp=fp;m.triggerRows=rows;try{st.render();}catch(e){state.lastError=String(e&&e.message||e);}}else{paintSummary(rows);paintEmpty(rows);}}}
  tick();state.timer=setInterval(tick,POLL);if(window.MutationObserver&&document.body){state.observer=new MutationObserver(function(){ensureChartSingleWriter();});state.observer.observe(document.body,{childList:true,subtree:true});}return true;
}
window.__ctlInstallHlFixV23=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
