(function(){
'use strict';
var HL='https://api.hyperliquid.xyz/info', META_POLL=15000, DATA_POLL=7000, PAGE=20;
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function tm(v){if(typeof v==='number'&&Number.isFinite(v))return v;var x=Date.parse(v||'');return Number.isFinite(x)?x:0;}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function valid(v){return /^0x[a-fA-F0-9]{40}$/.test(String(v||'').trim());}
function lower(v){return valid(v)?String(v).trim().toLowerCase():'';}
function add(a,v){v=lower(v);if(v&&a.indexOf(v)<0)a.push(v);}
function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return Array.isArray(v)?v.slice():v;}}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');}
function fmtTime(v){var x=tm(v);if(!x)return String(v||'-').replace('T',' ').slice(0,19);var d=new Date(x);return d.getFullYear()+'.'+String(d.getMonth()+1).padStart(2,'0')+'.'+String(d.getDate()).padStart(2,'0')+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')+':'+String(d.getSeconds()).padStart(2,'0');}
function fmtPx(v){v=n(v,0);if(!v)return'—';if(v>=1000)return v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});if(v>=1)return v.toFixed(5).replace(/0+$/,'').replace(/\.$/,'');return v.toFixed(7).replace(/0+$/,'').replace(/\.$/,'');}
function fmtMoney(v){if(v==null||!Number.isFinite(Number(v)))return'—';v=Number(v);return(v>=0?'+$':'-$')+Math.abs(v).toFixed(4);}
function fmtPct(v){return v!=null&&Number.isFinite(Number(v))?Number(v).toFixed(2)+'%':'—';}
function fmtRR(v){return v!=null&&Number.isFinite(Number(v))&&Number(v)>=0?Number(v).toFixed(2):'—';}
function side(x){var s=String(x&&(x.side||x.type||x.direction)||'').toUpperCase();return s.indexOf('SELL')>=0||s==='A'||s.indexOf('SHORT')>=0?'SELL':'BUY';}
async function post(body,ms){var c=new AbortController(),t=setTimeout(function(){c.abort();},ms||9000);try{var r=await fetch(HL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HL '+r.status+' '+body.type);var d=await r.json();if(d&&d.error)throw new Error(String(d.error));return d;}finally{clearTimeout(t);}}
function oidKey(v){return v==null?'':String(v);}
function isTriggerOrder(o){if(!o)return false;var t=(String(o.orderType||'')+' '+String(o.triggerCondition||'')+' '+String(o.tpsl||'')).toUpperCase();return !!o.isTrigger||n(o.triggerPx,0)>0||t.indexOf('TAKE PROFIT')>=0||t.indexOf('STOP')>=0||/(^|\W)(TP|SL)(\W|$)/.test(t);}
function triggerKind(o){var t=(String(o&&o.orderType||'')+' '+String(o&&o.triggerCondition||'')+' '+String(o&&o.tpsl||'')).toUpperCase();if(t.indexOf('TAKE PROFIT')>=0||/(^|\W)TP(\W|$)/.test(t))return'TP';if(t.indexOf('STOP')>=0||/(^|\W)SL(\W|$)/.test(t))return'SL';return'TRIGGER';}
function statusText(w){return String(w&&w.status||'unknown').toUpperCase();}
function accounts(st){var a=[];(Array.isArray(st&&st.fills)?st.fills:[]).slice(0,800).forEach(function(x){add(a,x&&x._hlAccount);});add(a,window._hlAccountWallet);add(a,window._userWallet);add(a,window._hlActiveWallet);add(a,window._hlSelectedWallet);add(a,window._pagesHlActiveWallet);return a.slice(0,12);}
function fillMapByOid(fills){var m={};(fills||[]).forEach(function(f){var k=oidKey(f&&f._hlOid);if(!k)return;(m[k]||(m[k]=[])).push(f);});return m;}
function histFlatten(acct,rows){
  var byOid={},parentBracket={},triggers=[];
  function put(o,w,parentOid){
    if(!o)return;var oid=oidKey(o.oid||o.order_id||o.cloid);if(oid&&!byOid[oid])byOid[oid]={account:acct,order:o,wrap:w,parentOid:parentOid||''};
    var children=Array.isArray(o.children)?o.children:[];
    var childHasTrigger=children.some(isTriggerOrder);
    if(oid&&!o.reduceOnly&&childHasTrigger)parentBracket[oid]=1;
    if(isTriggerOrder(o))triggers.push({account:acct,order:o,wrap:w,parentOid:parentOid||''});
    children.forEach(function(ch){put(ch,w,oid||parentOid||'');});
  }
  (rows||[]).forEach(function(w){var o=w&&w.order?w.order:w;put(o,w,'');});
  return{byOid:byOid,parentBracket:parentBracket,triggers:triggers};
}
function mergeMeta(parts){var out={byOid:{},parentBracket:{},triggers:[]};parts.forEach(function(p){Object.keys(p.byOid||{}).forEach(function(k){if(!out.byOid[k])out.byOid[k]=p.byOid[k];});Object.keys(p.parentBracket||{}).forEach(function(k){out.parentBracket[k]=1;});out.triggers=out.triggers.concat(p.triggers||[]);});var seen={},t=[];out.triggers.forEach(function(x){var o=x.order||{},k=[x.account,oidKey(o.oid||o.order_id||o.cloid),triggerKind(o),n(o.triggerPx||o.limitPx||o.px,0),n(o.sz||o.origSz,0)].join('|');if(seen[k])return;seen[k]=1;t.push(x);});out.triggers=t;return out;}
function directEntries(st,meta){return (st.fills||[]).filter(function(f){if(!f||!f.is_entry)return false;var oid=oidKey(f._hlOid);return !(oid&&meta.parentBracket[oid]);});}
function bracketEntries(st,meta){return (st.fills||[]).filter(function(f){if(!f||!f.is_entry)return false;var oid=oidKey(f._hlOid);return !!(oid&&meta.parentBracket[oid]);});}
function triggerRows(st,meta){var fm=fillMapByOid(st.fills||[]),rows=[];meta.triggers.forEach(function(x){var o=x.order||{},oid=oidKey(o.oid||o.order_id||o.cloid),fills=fm[oid]||[],pnl=null;if(fills.length){var vals=fills.filter(function(f){return f&&f.pnl!=null;}).map(function(f){return n(f.pnl,0);});if(vals.length)pnl=vals.reduce(function(a,b){return a+b;},0);}var px=n(o.triggerPx,0)||n(o.limitPx!=null?o.limitPx:o.px,0),sz=Math.abs(n(o.sz!=null?o.sz:o.origSz,0)),s=String(o.side||'').toUpperCase(),sell=s==='A'||s==='SELL',kind=triggerKind(o),status=statusText(x.wrap);rows.push({trade_id:oid||('trg-'+rows.length),timestamp:new Date(n(x.wrap&&x.wrap.statusTimestamp,0)||n(o.timestamp,0)||Date.now()).toISOString(),symbol:coin(o.coin||o.symbol)+'/USD',type:sell?'SELL':'BUY',side:sell?'SELL':'BUY',direction:kind+' · '+status,volume:sz,lot:sz,price:px,trigger_price:px,pnl:pnl,_pendingKind:kind,_status:status,_hlAccount:x.account,_hlOid:oid,_parentOid:x.parentOid,_source:'HL_HISTORY_TRIGGER'});});rows.sort(function(a,b){return tm(b.timestamp)-tm(a.timestamp);});return rows;}
function dirEntry(x){var d=String(x&&(x._hlDir||x.direction)||'').toUpperCase();if(d.indexOf('LONG')>=0)return'LONG';if(d.indexOf('SHORT')>=0)return'SHORT';return side(x)==='SELL'?'SHORT':'LONG';}
function dirClose(x){var d=String(x&&(x._hlDir||x.direction)||'').toUpperCase();if(d.indexOf('CLOSE LONG')>=0||d.indexOf('LONG')>=0)return'LONG';if(d.indexOf('CLOSE SHORT')>=0||d.indexOf('SHORT')>=0)return'SHORT';return side(x)==='SELL'?'LONG':'SHORT';}
function fillKey(x){return [x&&x._hlAccount||'',coin(x&&x.symbol),x&&x.trade_id||'',x&&x.timestamp||'',n(x&&x.price),n(x&&x.volume)].join('|');}
function entryPnlMap(fills){var ordered=(fills||[]).slice().sort(function(a,b){return tm(a.timestamp)-tm(b.timestamp);}),buckets={},map={};function bucket(x,d){var k=[x._hlAccount||'',coin(x.symbol),d].join('|');return buckets[k]||(buckets[k]=[]);}ordered.forEach(function(x){if(!x)return;var q=Math.abs(n(x.volume||x.lot,0));if(!(q>0))return;if(x.is_entry){var d=dirEntry(x),lot={key:fillKey(x),remaining:q,realized:0,matched:false,dir:d};bucket(x,d).push(lot);map[lot.key]=lot;return;}if(x.pnl==null)return;var b=bucket(x,dirClose(x)),left=q,matched=[];for(var i=0;i<b.length&&left>1e-12;i++){if(!(b[i].remaining>1e-12))continue;var use=Math.min(b[i].remaining,left);matched.push([b[i],use]);left-=use;}var mq=matched.reduce(function(s,m){return s+m[1];},0);if(!(mq>0))return;matched.forEach(function(m){m[0].realized+=n(x.pnl)*(m[1]/mq);m[0].remaining=Math.max(0,m[0].remaining-m[1]);m[0].matched=true;});});return map;}
function directSummary(st,meta){var entries=directEntries(st,meta),map=entryPnlMap(st.fills||[]),vals=[];entries.forEach(function(e){var x=map[fillKey(e)];if(x&&x.matched)vals.push(n(x.realized,0));});var wins=vals.filter(function(v){return v>1e-12;}),loss=vals.filter(function(v){return v<-1e-12;}),pnl=vals.reduce(function(a,b){return a+b;},0),avgW=wins.length?wins.reduce(function(a,b){return a+b;},0)/wins.length:0,avgL=loss.length?Math.abs(loss.reduce(function(a,b){return a+b;},0)/loss.length):0;return{pnl:pnl,entries:entries.length,prob:(wins.length+loss.length)?wins.length*100/(wins.length+loss.length):null,rr:avgL>1e-12?avgW/avgL:null};}
function pendingSummary(st,meta,rows){var parents={},b=bracketEntries(st,meta);b.forEach(function(f){var k=oidKey(f._hlOid)||f.trade_id;if(k)parents[k]=1;});var filled=rows.filter(function(r){return r.pnl!=null&&/FILLED|TRIGGERED|EXECUTED/.test(r._status);}),wins=filled.filter(function(r){return n(r.pnl)>1e-12;}),loss=filled.filter(function(r){return n(r.pnl)<-1e-12;}),tp=filled.filter(function(r){return r._pendingKind==='TP';}),sl=filled.filter(function(r){return r._pendingKind==='SL';}),pnl=filled.reduce(function(a,r){return a+n(r.pnl,0);},0),avgW=wins.length?wins.reduce(function(a,r){return a+n(r.pnl,0);},0)/wins.length:0,avgL=loss.length?Math.abs(loss.reduce(function(a,r){return a+n(r.pnl,0);},0)/loss.length):0,dec=tp.length+sl.length;return{pnl:pnl,entries:Object.keys(parents).length,prob:dec?tp.length*100/dec:null,rr:avgL>1e-12?avgW/avgL:null};}
function ensureBar(filters){var b=document.getElementById('ctlHistoryPnlSummaryV11');if(!b){b=document.createElement('div');b.id='ctlHistoryPnlSummaryV11';filters.parentNode.insertBefore(b,filters);}b.style.cssText='display:flex;align-items:center;gap:32px;flex-wrap:wrap;margin:0 0 10px 0;padding:13px 16px;border:1px solid var(--border);border-radius:10px;background:rgba(5,14,26,.78);font-family:JetBrains Mono,monospace;font-size:12px;line-height:1.4;';return b;}
function span(l,v,c){return'<span><span style="color:var(--text-muted);font-weight:700">'+l+'</span> <b style="color:'+c+'">'+v+'</b></span>';}
function paintSummary(filters,mode,m){var b=ensureBar(filters);if(mode==='all'){b.style.display='none';return;}b.style.display='flex';b.innerHTML=span('PNL',fmtMoney(m.pnl),m.pnl==null?'var(--text-muted)':(n(m.pnl)>=0?'var(--green)':'var(--red)'))+span('TOTAL ENTRY',String(n(m.entries,0)),'var(--accent)')+span('PROBABILITAS',fmtPct(m.prob),m.prob!=null&&n(m.prob)>=50?'var(--green)':'var(--gold)')+span('RISK/REWARD',fmtRR(m.rr),m.rr!=null&&n(m.rr)>=1?'var(--green)':'var(--gold)');}
function install(){
  var st=window.__CTL_HISTORY_STABLE__,d=document,tbody=d.getElementById('historyTableBody'),filters=d.getElementById('historyTypeFilters');if(!st||st.version<10||!tbody||!filters){setTimeout(install,150);return false;}
  var old=window.__CTL_HISTORY_MODE_V20__;if(old){try{if(old.metaTimer)clearInterval(old.metaTimer);}catch(e){}try{if(old.dataTimer)clearInterval(old.dataTimer);}catch(e){}}
  ['__CTL_HL_PENDING_V19__','__CTL_HL_PENDING_V18__','__CTL_HL_SUMMARY_V19__','__CTL_HL_SUMMARY_V18__','__CTL_HL_MARKET_ONLY_V18__'].forEach(function(k){var x=window[k];if(x&&x.timer)try{clearInterval(x.timer);}catch(e){}});
  var baseRender=st.render,basePoll=st.poll;if(st.timer)try{clearInterval(st.timer);}catch(e){}st.timer=null;if(st.observer)try{st.observer.disconnect();}catch(e){}st.observer=null;
  var state={ready:true,version:20,renderOwnerAware:true,source:'historical-meta+owner-render-v20',meta:{byOid:{},parentBracket:{},triggers:[]},shown:PAGE,metaBusy:false,dataBusy:false,lastMetaAt:0,lastError:'',metaTimer:null,dataTimer:null,triggerRows:[]};window.__CTL_HISTORY_MODE_V20__=state;
  function active(){filters.querySelectorAll('.history-type-filter').forEach(function(b){var a=b.dataset.historyType===st.mode;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a?'true':'false');});}
  function currentRows(){if(st.mode==='pending')return state.triggerRows;if(st.mode==='direct')return directEntries(st,state.meta);return st.fills||[];}
  function empty(rows){var e=d.getElementById('emptyHistory'),t=d.getElementById('historyTable');if(rows.length){if(e)e.style.display='none';if(t)t.style.display='';return;}if(t)t.style.display='none';if(e){e.style.display='';var a=e.querySelector('.text'),b=e.querySelector('.sub');if(st.mode==='pending'){if(a)a.textContent='Belum ada riwayat TP/SL Hyperliquid yang cocok';if(b)b.textContent='Menunggu historicalOrders dan pencocokan OID terhadap userFills.';}else if(st.mode==='direct'){if(a)a.textContent='Belum ada Langsung Entry';if(b)b.textContent='Entry yang punya bracket TP/SL dikeluarkan dari mode ini.';}}}
  function renderCustom(){active();if(st.mode==='all'){ensureBar(filters).style.display='none';var info=d.getElementById('tradeLogInfo');if(info)info.style.display='';if(typeof baseRender==='function')return baseRender();return;}
    var rows=currentRows(),max=Math.min(rows.length,state.shown||PAGE),entryMap=st.mode==='direct'?entryPnlMap(st.fills||[]):null;tbody.innerHTML='';
    for(var i=0;i<max;i++){var x=rows[i],sd=side(x),kind,pnl,pv;if(st.mode==='pending'){kind=x.direction||((x._pendingKind||'TRIGGER')+' · '+(x._status||''));pnl=x.pnl==null?'—':fmtMoney(x.pnl);pv=x.pnl==null?null:n(x.pnl);}else{kind='ENTRY';var m=entryMap[fillKey(x)];pnl=m&&m.matched?('REAL '+fmtMoney(m.realized)):'—';pv=m&&m.matched?n(m.realized):null;}var pc=pv==null?'var(--text-muted)':(pv>1e-12?'var(--green)':(pv<-1e-12?'var(--red)':'var(--text-muted)')),tr=d.createElement('tr');tr.innerHTML='<td style="color:var(--text-muted);font-size:11px">'+fmtTime(x.timestamp)+'</td><td>'+(i+1)+'</td><td style="font-weight:700">'+esc(x.symbol||'-')+'</td><td class="'+(sd==='BUY'?'side-long':'side-short')+'" style="font-weight:800">'+sd+'</td><td style="font-weight:800">'+esc(kind)+'</td><td>'+esc(x.volume!=null?x.volume:(x.lot||0))+'</td><td>'+fmtPx(x.trigger_price||x.price||x.entry_price)+'</td><td style="color:'+pc+';font-weight:800">'+pnl+'</td><td style="font-weight:800;color:var(--green)">HL</td>';tbody.appendChild(tr);}
    var wrap=d.getElementById('loadMoreDealsWrap'),btn=d.getElementById('loadMoreDealsBtn');if(wrap){if(max<rows.length){wrap.style.display='';if(btn)btn.textContent='📋 Load More +'+Math.min(PAGE,rows.length-max)+' ('+(rows.length-max)+' remaining)';}else wrap.style.display='none';}
    empty(rows);var info=d.getElementById('tradeLogInfo');if(info)info.style.display='none';var sum=st.mode==='pending'?pendingSummary(st,state.meta,state.triggerRows):directSummary(st,state.meta);paintSummary(filters,st.mode,sum);
  }
  function ownerRender(){var r=st.render;if(typeof r==='function'&&r!==renderCustom)return r();return renderCustom();}
  async function refreshMeta(){if(state.metaBusy)return;state.metaBusy=true;try{var ac=accounts(st);if(!ac.length){state.lastError='account belum tersedia';ownerRender();return;}var rs=await Promise.allSettled(ac.map(function(a){return post({type:'historicalOrders',user:a},10000);})),parts=[];rs.forEach(function(r,i){if(r.status==='fulfilled'&&Array.isArray(r.value))parts.push(histFlatten(ac[i],r.value));});if(parts.length){state.meta=mergeMeta(parts);state.triggerRows=triggerRows(st,state.meta);state.lastMetaAt=Date.now();state.lastError='';}else state.lastError='historicalOrders gagal';ownerRender();}catch(e){state.lastError=String(e&&e.message||e);ownerRender();}finally{state.metaBusy=false;}}
  async function refreshData(){if(state.dataBusy)return;state.dataBusy=true;try{if(typeof basePoll==='function')await basePoll();}catch(e){}finally{state.dataBusy=false;}if(Date.now()-state.lastMetaAt>5000)refreshMeta();else ownerRender();}
  st.setMode=function(m){m=['all','pending','direct'].indexOf(m)>=0?m:'all';st.mode=m;window._historyTypeFilter=m;state.shown=PAGE;try{sessionStorage.setItem('copy_history_type_filter',m);}catch(e){}ownerRender();if(m!=='all'&&Date.now()-state.lastMetaAt>3000)refreshMeta();};window.setHistoryTypeFilter=st.setMode;
  st.render=renderCustom;st.loadMore=function(){state.shown=Math.min(currentRows().length,(state.shown||PAGE)+PAGE);ownerRender();};window._loadMoreDeals=st.loadMore;
  state.metaTimer=setInterval(refreshMeta,META_POLL);state.dataTimer=setInterval(refreshData,DATA_POLL);renderCustom();refreshMeta();return true;
}
window.__ctlInstallHlModeV20=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();