(function(){
'use strict';
var VERSION=32,HL='https://api.hyperliquid.xyz/info',MAX_FILLS=10000,RECENT_LIMIT=2000,CACHE_MS=300000,POLL_MS=60000;
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function tm(v){if(typeof v==='number'&&Number.isFinite(v))return v;var x=Date.parse(v||'');return Number.isFinite(x)?x:0;}
function validWallet(v){return /^0x[a-fA-F0-9]{40}$/.test(String(v||'').trim());}
function lower(v){return validWallet(v)?String(v).trim().toLowerCase():'';}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function uniq(a){var s={},o=[];(a||[]).forEach(function(x){x=lower(x);if(x&&!s[x]){s[x]=1;o.push(x);}});return o;}
function classifyFill(f){var d=String(f&&f.dir||'').toLowerCase();if(/^open\b/.test(d))return'ENTRY';if(/^close\b/.test(d))return'CLOSE';var sp=Number(f&&f.startPosition),sz=Math.abs(Number(f&&f.sz)),side=String(f&&f.side||'').toUpperCase();if(Number.isFinite(sp)&&Number.isFinite(sz)&&sz>0){var delta=(side==='B'||side==='BUY')?sz:-sz,end=sp+delta;if(Math.abs(sp)<1e-12&&Math.abs(end)>1e-12)return'ENTRY';if(sp*end>0&&Math.abs(end)>Math.abs(sp)+1e-12)return'ENTRY';if(sp*end>0&&Math.abs(end)<Math.abs(sp)-1e-12)return'CLOSE';if(sp*end<0)return'FLIP';}return Math.abs(n(f&&f.closedPnl,0))>1e-12?'CLOSE':'UNKNOWN';}
function feeUsd(f){var fee=Math.abs(n(f&&f.fee,0)),t=String(f&&f.feeToken||'USDC').toUpperCase();return{usd:(t==='USDC'||t==='USDT'||t==='USDE')?fee:0,known:fee===0||t==='USDC'||t==='USDT'||t==='USDE',token:t,raw:fee};}
function normFill(f,a){if(!f)return null;var t=n(f.time,0)||tm(f.timestamp),cls=classifyFill(f),ff=feeUsd(f),cp=n(f.closedPnl,0),side=String(f.side||'').toUpperCase(),buy=side==='B'||side==='BUY';return{trade_id:f.tid||f.trade_id||f.oid||(a+'-'+t),timestamp:t?new Date(t).toISOString():String(f.timestamp||''),time:t,symbol:coin(f.coin||f.symbol)+'/USD',coin:coin(f.coin||f.symbol),type:buy?'BUY':'SELL',side:buy?'BUY':'SELL',direction:String(f.dir||cls),volume:Math.abs(n(f.sz!=null?f.sz:f.volume,0)),price:n(f.px!=null?f.px:f.price,0),is_entry:cls==='ENTRY',_fillClass:cls,_hlAccount:a,_hlOid:f.oid==null?null:String(f.oid),_hlTid:f.tid==null?null:String(f.tid),_hlClosedPnl:cp,_hlFee:ff.raw,_hlFeeUsd:ff.usd,_hlFeeKnown:ff.known,_hlFeeToken:ff.token,_hlNetPnl:cp-ff.usd,pnl:cls==='ENTRY'?null:cp};}
async function post(body,ms){var c=new AbortController(),t=setTimeout(function(){c.abort();},ms||10000);try{var r=await fetch(HL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HL '+r.status+' '+body.type);var d=await r.json();if(d&&d.error)throw new Error(String(d.error));return d;}finally{clearTimeout(t);}}
function accounts(){var st=window.__CTL_HISTORY_STABLE__,a=[];(Array.isArray(st&&st.fills)?st.fills:[]).forEach(function(f){if(f&&f._hlAccount)a.push(f._hlAccount);});a.push(window._hlAccountWallet,window._userWallet,window._pagesHlActiveWallet,window._hlActiveWallet,window._hlSelectedWallet);return uniq(a).slice(0,12);}
function fillKey(x){return[x._hlAccount||'',x._hlTid||x.trade_id||'',x._hlOid||'',x.time||tm(x.timestamp),x.coin,x.price,x.volume].join('|');}
function mergeFills(rows){var s={},o=[];(rows||[]).forEach(function(x){if(!x)return;var k=fillKey(x);if(!s[k]){s[k]=1;o.push(x);}});o.sort(function(a,b){return n(a.time)-n(b.time);});if(o.length>MAX_FILLS)o=o.slice(o.length-MAX_FILLS);return o;}
function cacheKey(a){return'ctl_hl_ledger_v32:'+a;}
function loadCache(a){try{var x=JSON.parse(localStorage.getItem(cacheKey(a))||'null');return x&&x.version===VERSION?x:null;}catch(e){return null;}}
function saveCache(a,x){try{localStorage.setItem(cacheKey(a),JSON.stringify(x));}catch(e){}}
async function recent(a){var r=await post({type:'userFills',user:a,aggregateByTime:true},10000);return(Array.isArray(r)?r:[]).map(function(f){return normFill(f,a);}).filter(Boolean);}
async function deep(a){var out=[],cursor=0,end=Date.now()+1000,pages=0;while(out.length<MAX_FILLS&&pages<30&&cursor<=end){pages++;var r=await post({type:'userFillsByTime',user:a,startTime:cursor,endTime:end,aggregateByTime:true},12000);if(!Array.isArray(r)||!r.length)break;var nr=r.map(function(f){return normFill(f,a);}).filter(Boolean),mx=cursor;nr.forEach(function(x){mx=Math.max(mx,n(x.time));});out=mergeFills(out.concat(nr));if(mx<=cursor)break;cursor=mx+1;if(r.length<500&&out.length<RECENT_LIMIT)break;}return{rows:out,pages:pages};}
function isTpSl(o){var txt=(String(o&&o.orderType||'')+' '+String(o&&o.triggerCondition||'')).toUpperCase();return !!(o&&(o.isTrigger||o.isPositionTpsl||o.isPositionTpSl||n(o.triggerPx,0)>0||txt.indexOf('TAKE PROFIT')>=0||txt.indexOf('STOP')>=0||/(^|\W)(TP|SL)(\W|$)/.test(txt)));}
function scanOrder(o,parent,mp,times){if(!o)return;var oid=o.oid==null?'':String(o.oid),ts=n(o.timestamp,0);if(ts)times.push(ts);var kids=Array.isArray(o.children)?o.children:[];if(oid&&kids.some(isTpSl))mp.parents[oid]=1;kids.forEach(function(ch){var co=ch&&ch.oid!=null?String(ch.oid):'';if(co&&oid&&isTpSl(ch)){mp.children[co]=oid;mp.parents[oid]=1;}scanOrder(ch,oid,mp,times);});if(parent&&oid&&isTpSl(o)){mp.children[oid]=parent;mp.parents[parent]=1;}}
async function orderMeta(a,existing){var r=await post({type:'historicalOrders',user:a},10000),rows=Array.isArray(r)?r:[],mp=existing||{parents:{},children:{}},times=[];rows.forEach(function(w){var o=w&&w.order?w.order:w;scanOrder(o,'',mp,times);});var oldest=times.length?Math.min.apply(null,times):0;return{map:mp,count:rows.length,oldest:oldest,complete:rows.length<2000};}
async function funding(a,start){var out=[],cursor=Math.max(0,n(start,0)),end=Date.now()+1000,pages=0;while(pages<40&&cursor<=end){pages++;var r=await post({type:'userFunding',user:a,startTime:cursor,endTime:end},10000);if(!Array.isArray(r)||!r.length)break;var mx=cursor;r.forEach(function(x){var t=n(x&&x.time,0);mx=Math.max(mx,t);out.push({time:t,coin:coin(x&&x.delta&&x.delta.coin),usdc:n(x&&x.delta&&x.delta.usdc,0),account:a});});if(mx<=cursor)break;cursor=mx+1;if(r.length<500)break;}return out;}
function hydrateFromV20(mp){var m=window.__CTL_HISTORY_MODE_V20__,meta=m&&m.meta||{};Object.keys(meta.parentBracket||{}).forEach(function(k){if(k)mp.parents[String(k)]=1;});(meta.triggers||[]).forEach(function(t){var o=t&&t.order||{},c=o.oid||o.order_id||o.cloid,p=t&&t.parentOid;if(c!=null&&p!=null){mp.children[String(c)]=String(p);mp.parents[String(p)]=1;}});}
async function sync(){var st=state();if(!st||st.busy)return false;var accts=accounts();if(!accts.length)return false;st.busy=true;try{var all=[],fund=[],parents={},children={},coverage={},feeUnknown=0,deepPages=0;for(var i=0;i<accts.length;i++){var a=accts[i],c=loadCache(a),r=await recent(a),rows=r,needDeep=r.length>=1900;if(needDeep){if(c&&Date.now()-n(c.at)<CACHE_MS&&Array.isArray(c.fills)&&c.fills.length>=r.length){rows=mergeFills(c.fills.concat(r));}else{var d=await deep(a);deepPages+=d.pages;rows=mergeFills(d.rows.concat(r));}}else if(c&&Array.isArray(c.fills)){rows=mergeFills(c.fills.concat(r));}
 var mp={parents:Object.assign({},c&&c.parents||{}),children:Object.assign({},c&&c.children||{})};hydrateFromV20(mp);var om=await orderMeta(a,mp);Object.assign(parents,om.map.parents);Object.assign(children,om.map.children);var earliest=rows.length?n(rows[0].time):0,fu=[];try{fu=await funding(a,earliest);}catch(e){st.lastFundingError=String(e&&e.message||e);}fund=fund.concat(fu);coverage[a]={recentCount:r.length,fillCount:rows.length,deep:needDeep,orderCount:om.count,orderOldest:om.oldest,orderComplete:om.complete};rows.forEach(function(x){if(!x._hlFeeKnown&&x._hlFee>0)feeUnknown++;});all=all.concat(rows);saveCache(a,{version:VERSION,at:Date.now(),fills:rows,parents:om.map.parents,children:om.map.children,coverage:coverage[a]});}
 all=mergeFills(all);st.fills=all;st.funding=fund;st.parentPending=parents;st.childToParent=children;st.coverage=coverage;st.fillCount=all.length;st.fundingPnl=fund.reduce(function(s,x){return s+n(x.usdc);},0);st.feeUnknown=feeUnknown;st.deepPages=deepPages;st.ready=true;st.lastSync=Date.now();st.lastError='';try{window.dispatchEvent(new CustomEvent('ctl-hl-ledger-v32',{detail:{fillCount:all.length,fundingPnl:st.fundingPnl}}));}catch(e){}return true;}catch(e){st.lastError=String(e&&e.message||e);return false;}finally{st.busy=false;}}
function state(){return window.__CTL_HL_LEDGER_V32__;}
function install(){var old=state();if(old&&old.timer)try{clearInterval(old.timer);}catch(e){}var st={version:VERSION,ready:false,busy:false,source:'userFills+userFillsByTime<=10000+historicalOrders+userFunding;state-producer-no-dom',fills:[],funding:[],parentPending:{},childToParent:{},coverage:{},fillCount:0,fundingPnl:0,feeUnknown:0,deepPages:0,lastSync:0,lastError:'',lastFundingError:'',timer:null,sync:sync};window.__CTL_HL_LEDGER_V32__=st;setTimeout(sync,0);st.timer=setInterval(sync,POLL_MS);return true;}
window.__ctlInstallHlLedgerV32=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
