(function(){
'use strict';
var VERSION=22, PERF_POLL_MS=2500, WALLET_POLL_MS=10000, IDR=17100;
var HL_INFO='https://api.hyperliquid.xyz/info', DEXES=['','xyz','km','vntl'];
var PERF_IDS=['statNetPnl','statGrowth','statMaxDD','statTotalTrades','dGrossProfit','dGrossLoss','dAvgProfit','dAvgLoss','dPayoff','dInitDeposit','dPF','dWinRate','dLossRate','dRR','dRecovery','dMaxProfit','dMaxDDVal','dAbsDD','dLargestProfit','dLargestLoss','dMaxLoss','dConsecLoss','dLongsWon','dShortsWon','dConsecWins','dAvgConsecW','dAvgConsecL','dTotalTrades2'];
var WALLET_IDS=['capital','capitalIDR','perfCapital','perfCapitalIDR','perfIsolated','perfAvailable','hlWalletLabel','pagesHlAudit'];
var TEXT_DESC=Object.getOwnPropertyDescriptor(Node.prototype,'textContent');
var INNER_DESC=(typeof HTMLElement!=='undefined'&&Object.getOwnPropertyDescriptor(HTMLElement.prototype,'innerText'))||null;
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function tm(v){if(typeof v==='number'&&Number.isFinite(v))return v;var x=Date.parse(v||'');return Number.isFinite(x)?x:0;}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function validWallet(v){return /^0x[a-fA-F0-9]{40}$/.test(String(v||'').trim());}
function wallet(){var a=String(window._hlAccountWallet||window._userWallet||'').trim();return validWallet(a)?a.toLowerCase():'';}
function money(v){v=n(v);return(v>=0?'+$':'-$')+Math.abs(v).toFixed(4);}
function plainMoney(v){v=n(v);return(v<0?'-$':'$')+Math.abs(v).toFixed(4);}
function direction(t){var d=String(t&&(t._hlDir||t.direction)||'').toUpperCase();if(d.indexOf('LONG')>=0)return'LONG';if(d.indexOf('SHORT')>=0)return'SHORT';var s=String(t&&(t.side||t.type)||'').toUpperCase();return s.indexOf('SELL')>=0?'SHORT':'LONG';}
function uniqueClosed(st){var seen={},out=[];(Array.isArray(st&&st.fills)?st.fills:[]).forEach(function(x){if(!x||x.is_entry||x.pnl==null||!Number.isFinite(Number(x.pnl)))return;var k=[x._hlAccount||'',x.trade_id||'',x.timestamp||'',coin(x.symbol||x.coin),n(x.price),n(x.volume||x.lot),n(x.pnl)].join('|');if(seen[k])return;seen[k]=1;out.push(x);});out.sort(function(a,b){return tm(a.timestamp)-tm(b.timestamp);});return out;}
function runs(trades){var mw=0,ml=0,cw=0,cl=0,ws=[],ls=[];function ew(){if(cw){ws.push(cw);mw=Math.max(mw,cw);cw=0;}}function el(){if(cl){ls.push(cl);ml=Math.max(ml,cl);cl=0;}}trades.forEach(function(t){var p=n(t.pnl);if(p>0){el();cw++;}else if(p<0){ew();cl++;}else{ew();el();}});ew();el();return{maxW:mw,maxL:ml,avgW:ws.length?ws.reduce(function(a,b){return a+b;},0)/ws.length:0,avgL:ls.length?ls.reduce(function(a,b){return a+b;},0)/ls.length:0};}
function portfolio(){var p=window._hlPortfolio;if(!p||typeof p!=='object')return null;var net=Number(p.netPnl),end=Number(p.endEquity),dd=Number(p.maxDDpct),avh=Array.isArray(p.avh)?p.avh:[];return{net:Number.isFinite(net)?net:null,end:Number.isFinite(end)?end:null,ddPct:Number.isFinite(dd)?dd:null,avh:avh};}
function avhMetrics(avh){var pts=(avh||[]).map(function(r){return n(r&&r[1],NaN);}).filter(Number.isFinite);while(pts.length>2&&pts[0]<=0.01)pts.shift();var peak=-Infinity,maxDD=0,maxPct=0,min=Infinity;pts.forEach(function(v){peak=Math.max(peak,v);min=Math.min(min,v);if(peak>0){var dv=peak-v,dp=dv/peak*100;if(dv>maxDD)maxDD=dv;if(dp>maxPct)maxPct=dp;}});return{points:pts,maxDD:maxDD,maxPct:maxPct,min:min};}
function perfMetrics(){var st=window.__CTL_HISTORY_STABLE__,trades=uniqueClosed(st);if(!trades.length)return null;var wins=trades.filter(function(t){return n(t.pnl)>0;}),losses=trades.filter(function(t){return n(t.pnl)<0;}),zeros=trades.length-wins.length-losses.length;var gp=wins.reduce(function(s,t){return s+n(t.pnl);},0),gl=Math.abs(losses.reduce(function(s,t){return s+n(t.pnl);},0));var fillNet=trades.reduce(function(s,t){return s+n(t.pnl);},0),p=portfolio(),net=p&&p.net!=null?p.net:fillNet;var walletBal=n(window._userWalletDisplayBalance,0),basis=p&&p.end!=null&&p.net!=null?(p.end-p.net):0;if(!(basis>0)&&walletBal>0)basis=walletBal-net;if(!(basis>0))basis=n(window._tradeLogInitialBalance,0);if(!(basis>0))basis=13.40;var growth=basis>0?net/basis*100:0,av=p?avhMetrics(p.avh):{points:[],maxDD:0,maxPct:0,min:Infinity},eq=basis,peak=basis,maxDD=0,maxPct=0,minEq=basis,fillPts=[basis];trades.forEach(function(t){eq+=n(t.pnl);fillPts.push(eq);peak=Math.max(peak,eq);minEq=Math.min(minEq,eq);var dv=peak-eq,dp=peak>0?dv/peak*100:0;maxDD=Math.max(maxDD,dv);maxPct=Math.max(maxPct,dp);});var ddVal=av.points.length>1?av.maxDD:maxDD,ddPct=p&&p.ddPct!=null?p.ddPct:(av.points.length>1?av.maxPct:maxPct),points=av.points.length>1?av.points:fillPts,minPoint=points.length?Math.min.apply(null,points):minEq;var avgW=wins.length?gp/wins.length:0,avgL=losses.length?gl/losses.length:0,pf=gl>1e-12?gp/gl:(gp>0?Infinity:0),rr=avgL>1e-12?avgW/avgL:null,recovery=ddVal>1e-12?net/ddVal:null,payoff=trades.length?net/trades.length:0;var lp=wins.length?Math.max.apply(null,wins.map(function(t){return n(t.pnl);})):0,ll=losses.length?Math.min.apply(null,losses.map(function(t){return n(t.pnl);})):0;var longs=trades.filter(function(t){return direction(t)==='LONG';}),shorts=trades.filter(function(t){return direction(t)==='SHORT';}),lw=longs.filter(function(t){return n(t.pnl)>0;}).length,sw=shorts.filter(function(t){return n(t.pnl)>0;}).length,r=runs(trades),syms={};trades.forEach(function(t){syms[coin(t.symbol||t.coin)]=1;});return{trades:trades,wins:wins,losses:losses,zeros:zeros,gp:gp,gl:gl,net:net,fillNet:fillNet,basis:basis,growth:growth,ddVal:ddVal,ddPct:ddPct,absDD:Math.max(0,basis-minPoint),avgW:avgW,avgL:avgL,pf:pf,rr:rr,recovery:recovery,payoff:payoff,lp:lp,ll:ll,longs:longs,shorts:shorts,lw:lw,sw:sw,r:r,points:points,symbolCount:Object.keys(syms).filter(function(x){return x&&x!=='-';}).length,source:p&&p.net!=null?'HL_PORTFOLIO+USERFILLS':'USERFILLS'};}
function state(){return window.__CTL_HL_UI_ARBITER_V22__;}
function installTextLock(id,group){var s=state(),el=document.getElementById(id);if(!s||!el)return null;if(el.__ctlV22Lock&&el.__ctlV22Lock.group===group)return el;try{Object.defineProperty(el,'textContent',{configurable:true,enumerable:true,get:function(){return TEXT_DESC.get.call(this);},set:function(v){var st=state(),c=st&&st.canonical[id];if(!st||st.allow>0||!c||c.group!==group){TEXT_DESC.set.call(this,String(v));return;}if(String(v)===c.text){TEXT_DESC.set.call(this,c.text);return;}st.blocked[id]=(st.blocked[id]||0)+1;}});if(INNER_DESC){try{Object.defineProperty(el,'innerText',{configurable:true,enumerable:true,get:function(){return INNER_DESC.get.call(this);},set:function(v){var st=state(),c=st&&st.canonical[id];if(!st||st.allow>0||!c||c.group!==group){INNER_DESC.set.call(this,String(v));return;}if(String(v)===c.text)INNER_DESC.set.call(this,c.text);else st.blocked[id]=(st.blocked[id]||0)+1;}});}catch(e){}}el.__ctlV22Lock={group:group};}catch(e){}return el;}
function setCanonical(id,text,color,group){var s=state();if(!s)return;var el=installTextLock(id,group);if(!el)return;s.canonical[id]={text:String(text),color:color||'',group:group};s.allow++;try{TEXT_DESC.set.call(el,String(text));if(color)el.style.setProperty('color',color,'important');}finally{s.allow--;}}
function clearCanonicalGroup(group){var s=state();if(!s)return;Object.keys(s.canonical).forEach(function(k){if(s.canonical[k]&&s.canonical[k].group===group)delete s.canonical[k];});}
function ensureLocks(){var s=state();if(!s)return;PERF_IDS.forEach(function(id){if(s.canonical[id])installTextLock(id,'perf');});WALLET_IDS.forEach(function(id){if(s.canonical[id])installTextLock(id,'wallet');});}
function paintPerf(){var s=state(),m=perfMetrics();if(!s||!m)return false;var sig=[m.net,m.basis,m.ddPct,m.ddVal,m.trades.length,m.wins.length,m.losses.length,m.gp,m.gl,m.points.length,m.points[0],m.points[m.points.length-1]].join('|');if(sig===s.perfSig){ensureLocks();return true;}s.perfSig=sig;var pos=m.net>=0?'var(--green)':'var(--red)';setCanonical('statNetPnl',money(m.net),pos,'perf');setCanonical('statGrowth',(m.growth>=0?'+':'')+m.growth.toFixed(2)+'%',m.growth>=0?'var(--green)':'var(--red)','perf');setCanonical('statMaxDD',m.ddPct.toFixed(2)+'%','var(--red)','perf');setCanonical('statTotalTrades',String(m.trades.length),'var(--gold)','perf');setCanonical('dGrossProfit','$'+m.gp.toFixed(4),'var(--green)','perf');setCanonical('dGrossLoss','-$'+m.gl.toFixed(4),'var(--red)','perf');setCanonical('dAvgProfit','$'+m.avgW.toFixed(4),'','perf');setCanonical('dAvgLoss','$'+m.avgL.toFixed(4),'','perf');setCanonical('dPayoff',plainMoney(m.payoff),'','perf');setCanonical('dInitDeposit','$'+m.basis.toFixed(2),'','perf');setCanonical('dPF',m.pf===Infinity?'∞':m.pf.toFixed(2),'','perf');setCanonical('dWinRate',(m.trades.length?m.wins.length*100/m.trades.length:0).toFixed(2)+'% ('+m.wins.length+')','var(--green)','perf');setCanonical('dLossRate',(m.trades.length?m.losses.length*100/m.trades.length:0).toFixed(2)+'% ('+m.losses.length+')','var(--red)','perf');setCanonical('dRR',m.rr==null?'—':m.rr.toFixed(2),'','perf');setCanonical('dRecovery',m.recovery==null?'—':m.recovery.toFixed(2),'','perf');setCanonical('dMaxProfit','$'+m.lp.toFixed(4),'','perf');setCanonical('dMaxDDVal','$'+m.ddVal.toFixed(4),'var(--red)','perf');setCanonical('dAbsDD','$'+m.absDD.toFixed(2),'','perf');setCanonical('dLargestProfit','$'+m.lp.toFixed(4),'var(--green)','perf');setCanonical('dLargestLoss',plainMoney(m.ll),'var(--red)','perf');setCanonical('dMaxLoss','$'+Math.abs(m.ll).toFixed(4),'','perf');setCanonical('dConsecLoss',String(m.r.maxL),'var(--gold)','perf');setCanonical('dLongsWon',m.lw+'/'+m.longs.length+' ('+(m.longs.length?Math.round(m.lw/m.longs.length*100):0)+'%)','','perf');setCanonical('dShortsWon',m.sw+'/'+m.shorts.length+' ('+(m.shorts.length?Math.round(m.sw/m.shorts.length*100):0)+'%)','','perf');setCanonical('dConsecWins',String(m.r.maxW),'var(--gold)','perf');setCanonical('dAvgConsecW',m.r.avgW.toFixed(1),'','perf');setCanonical('dAvgConsecL',m.r.avgL.toFixed(1),'','perf');setCanonical('dTotalTrades2',String(m.trades.length),'var(--gold)','perf');paintChart(m);s.lastPerf=m;return true;}
function chartOverlay(){var base=document.getElementById('equityChart');if(!base)return null;var o=document.getElementById('ctlEquityChartV22');if(!o){o=document.createElement('canvas');o.id='ctlEquityChartV22';o.setAttribute('aria-hidden','true');o.style.cssText='position:absolute;pointer-events:none;z-index:5;';var wrap=base.parentElement;if(!wrap)return null;if(getComputedStyle(wrap).position==='static')wrap.style.position='relative';wrap.appendChild(o);}var wrap2=base.parentElement,br=base.getBoundingClientRect(),wr=wrap2.getBoundingClientRect();o.style.left=(br.left-wr.left)+'px';o.style.top=(br.top-wr.top)+'px';o.style.width=Math.max(1,base.clientWidth||br.width)+'px';o.style.height=Math.max(1,base.clientHeight||br.height)+'px';return{base:base,canvas:o};}
function paintChart(m){var pair=chartOverlay();if(!pair)return;var canvas=pair.canvas,cssW=Math.max(600,Math.floor(pair.base.clientWidth||1100)),cssH=Math.max(180,Math.floor(pair.base.clientHeight||220)),dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1));canvas.width=cssW*dpr;canvas.height=cssH*dpr;var c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,cssW,cssH);var pts=m.points.length?m.points:[m.basis],lo=Math.min.apply(null,pts),hi=Math.max.apply(null,pts);if(!(hi>lo))hi=lo+1;var pad={l:62,r:22,t:18,b:25},w=cssW-pad.l-pad.r,h=cssH-pad.t-pad.b,range=hi-lo,margin=range*.08;lo-=margin;hi+=margin;range=hi-lo;function X(i){return pad.l+(pts.length<=1?0:i/(pts.length-1))*w;}function Y(v){return pad.t+h-(v-lo)/range*h;}c.font='12px JetBrains Mono, monospace';c.textAlign='right';c.textBaseline='middle';for(var g=0;g<5;g++){var y=pad.t+g*h/4,v=hi-g*range/4;c.strokeStyle='rgba(255,255,255,.07)';c.lineWidth=1;c.beginPath();c.moveTo(pad.l,y);c.lineTo(cssW-pad.r,y);c.stroke();c.fillStyle='rgba(160,180,200,.62)';c.fillText('$'+v.toFixed(2),pad.l-10,y);}var positive=m.net>=0,line=positive?'#00e676':'#ff5252',grad=c.createLinearGradient(0,pad.t,0,pad.t+h);grad.addColorStop(0,positive?'rgba(0,230,118,.34)':'rgba(255,82,82,.30)');grad.addColorStop(1,'rgba(0,0,0,.02)');c.beginPath();c.moveTo(X(0),Y(pts[0]));for(var i=1;i<pts.length;i++)c.lineTo(X(i),Y(pts[i]));c.lineTo(X(pts.length-1),pad.t+h);c.lineTo(X(0),pad.t+h);c.closePath();c.fillStyle=grad;c.fill();c.beginPath();c.moveTo(X(0),Y(pts[0]));for(var j=1;j<pts.length;j++)c.lineTo(X(j),Y(pts[j]));c.strokeStyle=line;c.lineWidth=2.5;c.stroke();var wrap=document.getElementById('equityChartWrap');if(wrap){var h1=wrap.querySelector('div'),title='📈 Grafik Pertumbuhan Equity · HYPERLIQUID · ALL PAIRS · '+m.symbolCount+' SYMBOL · '+m.trades.length+' CLOSED FILLS';if(h1&&h1.textContent!==title){state().allow++;try{TEXT_DESC.set.call(h1,title);}finally{state().allow--;}}}}
async function postInfo(payload,timeout){var c=new AbortController(),t=setTimeout(function(){c.abort();},timeout||8500);try{var r=await fetch(HL_INFO,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HL '+r.status+' '+payload.type);var d=await r.json();if(d&&d.error)throw new Error(String(d.error));return d;}finally{clearTimeout(t);}}
function parseWallet(states,spot){var acct=0,margin=0,withdraw=0,pos=0;(states||[]).forEach(function(st){var ms=(st&&st.marginSummary)||{};acct+=Math.max(0,n(ms.accountValue));margin+=Math.max(0,n(ms.totalMarginUsed));withdraw+=Math.max(0,n(st&&st.withdrawable));((st&&st.assetPositions)||[]).forEach(function(p){var q=p&&p.position?p.position:p;if(q&&Math.abs(n(q.szi))>0)pos++;});});var spotTotal=0,spotHold=0;((spot&&spot.balances)||[]).forEach(function(b){if(String(b&&b.coin||'').toUpperCase()==='USDC'){spotTotal+=Math.max(0,n(b.total));spotHold+=Math.max(0,n(b.hold));}});var spotAvail=Math.max(0,spotTotal-spotHold),perpsAvail=withdraw>0?withdraw:Math.max(0,acct-margin),display=spotTotal>0?spotTotal:Math.max(0,acct);return{display:display,execution:acct,available:spotTotal>0?spotAvail:perpsAvail+spotAvail,perpsAvailable:perpsAvail,margin:spotTotal>0?spotHold:margin,spot:spotTotal,positions:pos};}
function walletCacheKey(w){return'ctl_hl_ui_v22_wallet:'+w;}
function saveWallet(w,b,fills){try{localStorage.setItem(walletCacheKey(w),JSON.stringify({at:Date.now(),balance:b,fills:fills}));}catch(e){}}
function loadWallet(w){try{var x=JSON.parse(localStorage.getItem(walletCacheKey(w))||'null');if(x&&x.at&&Date.now()-x.at<6*60*60*1000&&x.balance)return x;}catch(e){}return null;}
function applyWallet(w,b,fills,source){var s=state();if(!s||!b)return;var sig=[w,b.display,b.available,b.margin,b.positions,fills,source].join('|');if(sig===s.walletSig){ensureLocks();return;}s.walletSig=sig;setCanonical('capital','$'+n(b.display).toFixed(2),'var(--green)','wallet');setCanonical('capitalIDR','Rp '+Math.round(n(b.display)*IDR).toLocaleString(),'','wallet');setCanonical('perfCapital','$'+n(b.display).toFixed(2),'','wallet');setCanonical('perfCapitalIDR','Rp '+Math.round(n(b.display)*IDR).toLocaleString(),'','wallet');setCanonical('perfIsolated','$'+n(b.margin).toFixed(2),'var(--gold)','wallet');setCanonical('perfAvailable','$'+n(b.available).toFixed(2),'var(--green)','wallet');setCanonical('hlWalletLabel',source==='LIVE'?'HL ✓':'HL CACHE',source==='LIVE'?'rgba(0,231,160,.65)':'rgba(251,191,36,.85)','wallet');var audit=document.getElementById('pagesHlAudit');if(audit)setCanonical('pagesHlAudit',(source==='LIVE'?'HL ✓ ':'HL CACHE ')+'ACCOUNT · $'+n(b.display).toFixed(2)+' · '+n(b.positions)+' pos · '+n(fills)+' fills',source==='LIVE'?'#00e676':'#ffd740','wallet');window._userWalletDisplayBalance=n(b.display);window._userWalletBalance=n(b.execution);window._userWalletAvailable=n(b.perpsAvailable);window._userWalletDisplayAvailable=n(b.available);window._userWalletMarginUsed=n(b.margin);window._userWalletSpotUsdc=n(b.spot);s.lastWallet={wallet:w,balance:b,fills:fills,source:source,at:Date.now()};}
async function syncWallet(){var s=state();if(!s||s.walletBusy)return;var w=wallet();if(!w)return;if(s.wallet!==w){s.wallet=w;s.walletSig='';clearCanonicalGroup('wallet');var cached=loadWallet(w);if(cached)applyWallet(w,cached.balance,n(cached.fills),'CACHE');}s.walletBusy=true;try{var reqs=DEXES.map(function(d){var p={type:'clearinghouseState',user:w};if(d)p.dex=d;return postInfo(p,9000);});reqs.push(postInfo({type:'spotClearinghouseState',user:w},9000));reqs.push(postInfo({type:'userFills',user:w,aggregateByTime:true},9000));var res=await Promise.allSettled(reqs),complete=res.every(function(x){return x.status==='fulfilled';});if(!complete){var c=loadWallet(w);if(c)applyWallet(w,c.balance,n(c.fills),'CACHE');return;}var states=res.slice(0,4).map(function(x){return x.value||{};}),spot=res[4].value||{},fills=Array.isArray(res[5].value)?res[5].value.length:0,b=parseWallet(states,spot);saveWallet(w,b,fills);applyWallet(w,b,fills,'LIVE');}catch(e){var c2=loadWallet(w);if(c2)applyWallet(w,c2.balance,n(c2.fills),'CACHE');s.lastError=String(e&&e.message||e);}finally{s.walletBusy=false;}}
function stopLegacyPortfolio(){var p=window.__CTL_HL_PORTFOLIO_V21__;if(!p)return;try{if(p.timer)clearInterval(p.timer);}catch(e){}try{if(p.observer)p.observer.disconnect();}catch(e){}p.disabledBy='v22';}
function install(){var old=window.__CTL_HL_UI_ARBITER_V22__;if(old){try{if(old.perfTimer)clearInterval(old.perfTimer);}catch(e){}try{if(old.walletTimer)clearInterval(old.walletTimer);}catch(e){}try{if(old.lockTimer)clearInterval(old.lockTimer);}catch(e){}try{if(old.observer)old.observer.disconnect();}catch(e){}}var s={ready:true,version:VERSION,source:'HL portfolio+userFills single-writer arbiter',canonical:{},blocked:{},allow:0,perfSig:'',walletSig:'',wallet:'',walletBusy:false,lastPerf:null,lastWallet:null,lastError:'',perfTimer:null,walletTimer:null,lockTimer:null,observer:null};window.__CTL_HL_UI_ARBITER_V22__=s;stopLegacyPortfolio();paintPerf();syncWallet();setTimeout(paintPerf,600);setTimeout(syncWallet,1200);s.perfTimer=setInterval(paintPerf,PERF_POLL_MS);s.walletTimer=setInterval(syncWallet,WALLET_POLL_MS);s.lockTimer=setInterval(ensureLocks,2000);if(window.MutationObserver&&document.body){s.observer=new MutationObserver(function(){ensureLocks();var pair=chartOverlay();if(pair&&s.lastPerf)paintChart(s.lastPerf);});s.observer.observe(document.body,{subtree:true,childList:true});}window.addEventListener('resize',function(){if(s.lastPerf)paintChart(s.lastPerf);});return true;}
window.__ctlInstallHlUiArbiterV22=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
