(function(){
'use strict';
var HL='https://api.hyperliquid.xyz/info', POLL=8000, BACKUP='ctl_hl_pending_archive_v13', PROVEN='ctl_hl_proven_accounts_v10';
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function valid(v){return /^0x[a-fA-F0-9]{40}$/.test(String(v||'').trim());}
function lower(v){return valid(v)?String(v).trim().toLowerCase():'';}
function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return Array.isArray(v)?v.slice():v;}}
function safe(s){try{return JSON.parse(s||'null');}catch(e){return null;}}
function add(a,v){v=lower(v);if(v&&a.indexOf(v)<0)a.push(v);}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function kind(o){var t=(String(o&&o.orderType||'')+' '+String(o&&o.triggerCondition||'')).toUpperCase();if(t.indexOf('TAKE PROFIT')>=0||/(^|\W)TP(\W|$)/.test(t))return'TP';if(t.indexOf('STOP')>=0||/(^|\W)SL(\W|$)/.test(t))return'SL';if(o&&(o.isPositionTpsl||o.isPositionTpSl))return'TP/SL';if(o&&(o.isTrigger||n(o.triggerPx,0)>0))return'TRIGGER';return'LIMIT';}
async function post(body,ms){var c=new AbortController(),to=setTimeout(function(){c.abort();},ms||9000);try{var r=await fetch(HL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HL '+r.status+' '+body.type);var d=await r.json();if(d&&d.error)throw new Error(String(d.error));return d;}finally{clearTimeout(to);}}
function loadBackup(){try{var x=safe(localStorage.getItem(BACKUP));if(x&&Array.isArray(x.rows)&&x.rows.length)return x;}catch(e){}return null;}
function saveBackup(rows,accounts){if(!Array.isArray(rows)||!rows.length)return;try{localStorage.setItem(BACKUP,JSON.stringify({at:Date.now(),rows:clone(rows.slice(0,2400)),accounts:(accounts||[]).slice(0,40)}));}catch(e){}}
function legacyBackup(){var best=null;function scan(store){try{for(var i=0;i<store.length;i++){var k=store.key(i);if(!k)continue;if(k!=='ctl_hl_last_good_open_v10'&&k.indexOf('ctl_hl_open_v7:')!==0&&k!=='ctl_hl_pending_backup_v12')continue;var x=safe(store.getItem(k));if(x&&Array.isArray(x.rows)&&x.rows.length&&(!best||x.rows.length>best.rows.length))best=x;}}catch(e){}}scan(localStorage);scan(sessionStorage);return best;}
function seedAccounts(st){var out=[];[window._hlAccountWallet,window._userWallet,window._pagesHlActiveWallet,window._hlActiveWallet,window._hlSelectedWallet,window._userAddress,window._hlAgentWallet].forEach(function(v){add(out,v);});try{if(typeof window.activeHyperliquidWallet==='function')add(out,window.activeHyperliquidWallet());}catch(e){}if(st&&Array.isArray(st.accounts))st.accounts.forEach(function(v){add(out,v);});if(st&&Array.isArray(st.fills))st.fills.slice(0,200).forEach(function(f){add(out,f&&f._hlAccount);});try{var p=safe(localStorage.getItem(PROVEN));if(p&&Array.isArray(p.accounts))p.accounts.forEach(function(v){add(out,v);});}catch(e){}try{var o=safe(localStorage.getItem('ctl_hl_last_good_open_v10'));if(o&&Array.isArray(o.accounts))o.accounts.forEach(function(v){add(out,v);});}catch(e){}var b=loadBackup()||legacyBackup();if(b&&Array.isArray(b.accounts))b.accounts.forEach(function(v){add(out,v);});return out.slice(0,36);}
async function family(seeds){var out=seeds.slice(),masters=[];await Promise.all(seeds.slice(0,16).map(async function(a){try{var r=await post({type:'userRole',user:a},6500),role=String(r&&r.role||'').toLowerCase();if(role==='agent'&&valid(r&&r.data&&r.data.user)){add(out,r.data.user);add(masters,r.data.user);}else if(role==='subaccount'&&valid(r&&r.data&&r.data.master)){add(out,r.data.master);add(masters,r.data.master);}else if(role==='user')add(masters,a);}catch(e){}}));for(var i=0;i<masters.length&&i<10;i++){try{var s=await post({type:'subAccounts',user:masters[i]},7500);if(Array.isArray(s))s.forEach(function(x){add(out,x&&x.subAccountUser);});}catch(e){}}return out.slice(0,48);}
var dxCache={at:0,list:['']};async function dexes(){if(Date.now()-dxCache.at<300000)return dxCache.list;var list=[''];try{var d=await post({type:'perpDexs'},8000);if(Array.isArray(d))d.forEach(function(x){var nm=typeof x==='string'?x:(x&&typeof x.name==='string'?x.name:(Array.isArray(x)?x[0]:''));nm=String(nm||'').trim();if(nm&&list.indexOf(nm)<0)list.push(nm);});}catch(e){}dxCache={at:Date.now(),list:list.slice(0,20)};return dxCache.list;}
function normalize(raw,acct,dex,wrapper){var o=raw&&raw.order?raw.order:raw;if(!o)return null;wrapper=wrapper||raw||{};var s=String(o.side||'').toUpperCase(),sell=s==='A'||s==='SELL',k=kind(o),t=n(o.timestamp,0)||n(o.time,0)||n(wrapper.statusTimestamp,0)||Date.now(),trigger=n(o.triggerPx,0),limit=n(o.limitPx!=null?o.limitPx:o.px,0),vol=n(o.sz!=null?o.sz:o.origSz,0);return{order_id:o.oid||o.order_id||o.cloid||('hl-'+acct+'-'+coin(o.coin||o.symbol)+'-'+t+'-'+k),oid:o.oid||o.order_id||null,timestamp:new Date(t).toISOString(),created_at:new Date(t).toISOString(),symbol:coin(o.coin||o.symbol)+'/USD',coin:coin(o.coin||o.symbol),type:sell?'SELL':'BUY',side:sell?'SELL':'BUY',direction:k+(o.reduceOnly?' · REDUCE ONLY':''),volume:vol,lot:vol,price:trigger||limit,trigger_price:trigger,limit_price:limit,pnl:null,_pendingKind:k,_pendingSource:'HL_OPEN',_hlAccount:acct,_hlDex:dex||'main',_reduceOnly:!!o.reduceOnly,_orderType:String(o.orderType||''),_triggerCondition:String(o.triggerCondition||'')};}
function collect(raw,acct,dex,out,wrapper){out=out||[];if(!raw)return out;var o=raw&&raw.order?raw.order:raw,x=normalize(raw,acct,dex,wrapper||raw);if(x)out.push(x);(Array.isArray(o&&o.children)?o.children:[]).forEach(function(ch){collect(ch,acct,dex,out,raw);});return out;}
function key(x){var oid=x&&x.oid;if(oid!=null&&oid!=='')return [x._hlAccount||'',x._hlDex||'',String(oid)].join('|');return [x._hlAccount||'',x._hlDex||'',x.symbol||'',x.side||'',x._pendingKind||'',n(x.trigger_price||x.price,0).toPrecision(12),Math.abs(n(x.volume||x.lot,0)).toPrecision(12)].join('|');}
function dedupe(rows){var seen={},out=[];(rows||[]).forEach(function(x){if(!x)return;var k=key(x);if(seen[k])return;seen[k]=1;out.push(x);});out.sort(function(a,b){return Date.parse(b.timestamp||0)-Date.parse(a.timestamp||0);});return out;}
async function queryType(type,accounts,dxs){var tasks=[];accounts.forEach(function(a){dxs.forEach(function(d){var body={type:type,user:a};if(d)body.dex=d;tasks.push({a:a,d:d,p:post(body,9000)});});});var rs=await Promise.allSettled(tasks.map(function(t){return t.p;})),out=[],ok=0;rs.forEach(function(r,i){if(r.status!=='fulfilled'||!Array.isArray(r.value))return;ok++;r.value.forEach(function(raw){if(type==='historicalOrders'){var st=String(raw&&raw.status||'').toLowerCase();if(st!=='open')return;}collect(raw,tasks[i].a,tasks[i].d,out,raw);});});return{ok:ok,rows:out};}
async function fetchPending(accounts,dxs){var a=await queryType('frontendOpenOrders',accounts,dxs),b=await queryType('openOrders',accounts,dxs),all=a.rows.concat(b.rows),h={ok:0,rows:[]};if(!all.length)h=await queryType('historicalOrders',accounts,dxs);return{rows:dedupe(all.concat(h.rows)),ok:a.ok+b.ok+h.ok,source:all.length?'frontendOpenOrders+openOrders':(h.rows.length?'historicalOrders(open)':'empty')};}
function sig(rows){return (rows||[]).slice(0,40).map(key).join('~')+'#'+(rows||[]).length;}
function install(){var prev=window.__CTL_HL_PENDING_V13__;if(prev&&prev.timer)try{clearInterval(prev.timer);}catch(e){}var state={ready:true,version:13,timer:null,polling:false,zeroConfirmed:0,lastSig:''};window.__CTL_HL_PENDING_V13__=state;async function poll(){if(state.polling)return;var st=window.__CTL_HISTORY_STABLE__;if(!st||st.version<10)return;state.polling=true;try{var seeds=seedAccounts(st);if(!seeds.length)return;var accounts=await family(seeds),dx=await dexes(),r=await fetchPending(accounts,dx);if(r.rows.length){state.zeroConfirmed=0;st.exchange=r.rows;st.lastOpenGood=Date.now();st.openSource='pending-v13:'+r.source;saveBackup(r.rows,accounts);}else{var degraded=!!st.lastError;if(r.ok>0&&!degraded)state.zeroConfirmed++;else state.zeroConfirmed=0;if((degraded||r.ok===0||state.zeroConfirmed<3)&&(!Array.isArray(st.exchange)||!st.exchange.length)){var b=loadBackup()||legacyBackup();if(b&&Array.isArray(b.rows)&&b.rows.length){st.exchange=clone(b.rows);st.lastOpenGood=b.at||Date.now();st.openSource='pending-v13:restored';}}if(r.ok>0&&!degraded&&state.zeroConfirmed>=3){st.exchange=[];st.openSource='pending-v13:confirmed-empty';}}
var current=sig(st.exchange);if(current!==state.lastSig){state.lastSig=current;if(typeof st.render==='function'&&!st.rendering)st.render();}else if(st.mode==='pending'&&typeof st.render==='function'&&!st.rendering&&Array.isArray(st.exchange)&&st.exchange.length&&(!Array.isArray(st.pending)||!st.pending.length))st.render();
}catch(e){var st2=window.__CTL_HISTORY_STABLE__,b=loadBackup()||legacyBackup();if(st2&&(!Array.isArray(st2.exchange)||!st2.exchange.length)&&b&&Array.isArray(b.rows)&&b.rows.length){st2.exchange=clone(b.rows);st2.lastOpenGood=b.at||Date.now();st2.openSource='pending-v13:error-restore';if(typeof st2.render==='function'&&!st2.rendering)st2.render();}}finally{state.polling=false;}}
state.poll=poll;state.timer=setInterval(poll,POLL);setTimeout(poll,200);return true;}
window.__ctlInstallHlPendingV13=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
