(function(){
'use strict';
var HL='https://api.hyperliquid.xyz/info',POLL=12000,CACHE='ctl_hl_pending_history_v17';
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function valid(v){return /^0x[a-fA-F0-9]{40}$/.test(String(v||'').trim());}
function lower(v){return valid(v)?String(v).trim().toLowerCase():'';}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function tm(v){if(typeof v==='number'&&Number.isFinite(v))return v;var x=Date.parse(v||'');return Number.isFinite(x)?x:0;}
function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
function uniq(a){var s={},o=[];(a||[]).forEach(function(v){v=lower(v);if(v&&!s[v]){s[v]=1;o.push(v);}});return o;}
function add(a,v){v=lower(v);if(v&&a.indexOf(v)<0)a.push(v);}
function save(x){try{localStorage.setItem(CACHE,JSON.stringify(x));}catch(e){try{sessionStorage.setItem(CACHE,JSON.stringify(x));}catch(_){}}}
function load(){var x=null;try{x=JSON.parse(localStorage.getItem(CACHE)||'null');}catch(e){}if(!x)try{x=JSON.parse(sessionStorage.getItem(CACHE)||'null');}catch(e){}return x;}
async function post(body,ms){var c=new AbortController(),t=setTimeout(function(){c.abort();},ms||9000);try{var r=await fetch(HL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HL '+r.status);var d=await r.json();if(d&&d.error)throw new Error(String(d.error));return d;}finally{clearTimeout(t);}}
function seeds(){var a=[],st=window.__CTL_HISTORY_STABLE__,c=load();add(a,window._hlAccountWallet);add(a,window._userWallet);add(a,window._hlActiveWallet);add(a,window._hlSelectedWallet);add(a,window._pagesHlActiveWallet);if(st&&Array.isArray(st.fills))st.fills.slice(0,500).forEach(function(x){add(a,x&&x._hlAccount);});if(c&&Array.isArray(c.accounts))c.accounts.forEach(function(x){add(a,x);});return uniq(a).slice(0,24);}
async function family(base){var out=uniq(base),masters=[];await Promise.all(out.slice(0,12).map(async function(a){try{var r=await post({type:'userRole',user:a},5500),role=String(r&&r.role||'').toLowerCase();if(role==='agent'&&valid(r&&r.data&&r.data.user)){add(out,r.data.user);add(masters,r.data.user);}else if(role==='subaccount'&&valid(r&&r.data&&r.data.master)){add(out,r.data.master);add(masters,r.data.master);}else if(role==='user')add(masters,a);}catch(e){}}));for(var i=0;i<masters.length&&i<8;i++){try{var s=await post({type:'subAccounts',user:masters[i]},6500);if(Array.isArray(s))s.forEach(function(x){add(out,x&&x.subAccountUser);});}catch(e){}}return uniq(out).slice(0,28);}
function kind(o){var t=(String(o&&o.orderType||'')+' '+String(o&&o.triggerCondition||'')+' '+String(o&&o.tpsl||'')).toUpperCase();if(t.indexOf('TAKE PROFIT')>=0||/(^|\W)TP(\W|$)/.test(t))return'TP';if(t.indexOf('STOP')>=0||/(^|\W)SL(\W|$)/.test(t))return'SL';if(o&&(o.isPositionTpsl||o.isPositionTpSl))return'TPSL';if(o&&(o.isTrigger||n(o.triggerPx,0)>0))return'TRIGGER';return'OTHER';}
function normWrap(w,a){var o=w&&w.order?w.order:w;if(!o)return null;var k=kind(o);if(k==='OTHER')return null;var px=n(o.triggerPx,0)||n(o.limitPx!=null?o.limitPx:o.px,0),sz=Math.abs(n(o.sz!=null?o.sz:o.origSz,0));if(!(px>0&&sz>0))return null;var s=String(o.side||'').toUpperCase(),sell=s==='A'||s==='SELL',t=n(o.timestamp,0)||n(o.time,0)||n(w&&w.statusTimestamp,0)||Date.now();return{order_id:o.oid||o.order_id||o.cloid||('v17-'+a+'-'+coin(o.coin)+'-'+k+'-'+px+'-'+sz+'-'+t),timestamp:new Date(t).toISOString(),symbol:coin(o.coin||o.symbol)+'/USD',coin:coin(o.coin||o.symbol),type:sell?'SELL':'BUY',side:sell?'SELL':'BUY',direction:k+' · SL/TP',volume:sz,lot:sz,price:px,trigger_price:px,pnl:null,_pendingKind:k,_pendingSource:'HL_TRIGGER_HISTORY',_hlAccount:a,_hlDex:'history',_reduceOnly:!!o.reduceOnly,_status:String(w&&w.status||'history'),_rawKind:String(o.orderType||'')};}
function key(x){return [x._hlAccount,x.symbol,x._pendingKind,n(x.trigger_price||x.price).toPrecision(12),Math.abs(n(x.volume)).toPrecision(12),Math.floor(tm(x.timestamp)/1000)].join('|');}
function dedupe(rows){var s={},o=[];(rows||[]).forEach(function(x){if(!x)return;var k=key(x);if(!s[k]){s[k]=1;o.push(x);}});o.sort(function(a,b){return tm(b.timestamp)-tm(a.timestamp);});return o;}
function groupMetrics(rows,fills){var groups={},entries=(fills||[]).filter(function(x){return x&&x.is_entry;});rows.forEach(function(o){var bucket=Math.floor(tm(o.timestamp)/60000),k=[o._hlAccount||'',o.symbol||'',Math.abs(n(o.volume,0)).toFixed(8),bucket].join('|'),g=groups[k]||(groups[k]={account:o._hlAccount||'',symbol:o.symbol,ts:tm(o.timestamp),vol:Math.abs(n(o.volume,0)),tp:[],sl:[]});if(o._pendingKind==='TP')g.tp.push(n(o.trigger_price||o.price,0));else if(o._pendingKind==='SL')g.sl.push(n(o.trigger_price||o.price,0));});var reward=0,risk=0,count=0;Object.keys(groups).forEach(function(k){var g=groups[k],best=null,bd=Infinity;entries.forEach(function(f){if((f._hlAccount||'')!==g.account||f.symbol!==g.symbol)return;var dd=Math.abs(tm(f.timestamp)-g.ts);if(dd<bd){bd=dd;best=f;}});if(!best)return;var ep=n(best.price,0),q=g.vol,dir=String(best.direction||best._hlDir||best.type||'').toUpperCase(),isShort=dir.indexOf('SHORT')>=0||(dir.indexOf('SELL')>=0&&dir.indexOf('LONG')<0);if(!(ep>0&&q>0))return;var rwd=0,rsk=0;g.tp.forEach(function(px){var v=isShort?(ep-px)*q:(px-ep)*q;if(v>rwd)rwd=v;});g.sl.forEach(function(px){var v=isShort?(px-ep)*q:(ep-px)*q;if(v>rsk)rsk=v;});if(rwd>0||rsk>0){count++;reward+=Math.max(0,rwd);risk+=Math.max(0,rsk);}});return{entries:count||Object.keys(groups).length,rr:risk>1e-12?reward/risk:null,reward:reward,risk:risk};}
async function poll(){var st=window.__CTL_HISTORY_STABLE__;if(!st||st.version<10)return false;var ac=await family(seeds());if(!ac.length)return false;var tasks=ac.map(function(a){return{a:a,p:post({type:'historicalOrders',user:a},9000)};}),rs=await Promise.allSettled(tasks.map(function(x){return x.p;})),rows=[],ok=0;rs.forEach(function(r,i){if(r.status!=='fulfilled'||!Array.isArray(r.value))return;ok++;r.value.forEach(function(w){var x=normWrap(w,tasks[i].a);if(x)rows.push(x);});});rows=dedupe(rows);if(rows.length){var m=groupMetrics(rows,Array.isArray(st.fills)?st.fills:[]);window.__CTL_HL_PENDING_HISTORY_METRICS__={entries:m.entries,rr:m.rr,reward:m.reward,risk:m.risk,orders:rows.length,at:Date.now(),source:'historicalOrders'};st.exchange=rows.slice(0,1600);st.pending=st.exchange.slice();save({at:Date.now(),accounts:ac,rows:st.exchange,metrics:window.__CTL_HL_PENDING_HISTORY_METRICS__});if(st.mode==='pending'&&typeof st.render==='function'&&!st.rendering)try{st.render();}catch(e){}return true;}var c=load();if(c&&Array.isArray(c.rows)&&c.rows.length){st.exchange=clone(c.rows);st.pending=st.exchange.slice();window.__CTL_HL_PENDING_HISTORY_METRICS__=c.metrics||null;if(st.mode==='pending'&&typeof st.render==='function'&&!st.rendering)try{st.render();}catch(e){}return true;}return ok>0;}
function install(){var old=window.__CTL_HL_PENDING_V17__;if(old&&old.timer)try{clearInterval(old.timer);}catch(e){}var s={ready:true,version:17,timer:null,poll:poll};window.__CTL_HL_PENDING_V17__=s;poll();s.timer=setInterval(poll,POLL);return true;}
window.__ctlInstallHlPendingV17=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();