(function(){
'use strict';
var VERSION=23,POLL=600;
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function tm(v){if(typeof v==='number'&&Number.isFinite(v))return v;var x=Date.parse(v||'');return Number.isFinite(x)?x:0;}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function px(o){return n(o&&((o.trigger_price!=null?o.trigger_price:(o.triggerPx!=null?o.triggerPx:(o.price!=null?o.price:(o.limitPx!=null?o.limitPx:0))))),0);}
function qty(o){return Math.abs(n(o&&((o.volume!=null?o.volume:(o.lot!=null?o.lot:(o.sz!=null?o.sz:(o.origSz!=null?o.origSz:o.szi))))),0));}
function oid(v){return v==null?'':String(v);}
function rawKind(o){return (String(o&&o._pendingKind||'')+' '+String(o&&o.direction||'')+' '+String(o&&o.pool_status||'')+' '+String(o&&o.order_type||'')+' '+String(o&&o.orderType||'')+' '+String(o&&o.triggerCondition||'')+' '+String(o&&o.tpsl||'')).toUpperCase();}
function kind(o){var t=rawKind(o);if(t.indexOf('TAKE PROFIT')>=0||/(^|\W)TP(\W|$)/.test(t))return'TP';if(t.indexOf('STOP LOSS')>=0||t.indexOf('STOP')>=0||/(^|\W)SL(\W|$)/.test(t))return'SL';return'';}
function livePositions(){var out=[];(Array.isArray(window._hlPosLive)?window._hlPosLive:[]).forEach(function(p){if(!p)return;var c=coin(p.coin||p.displayCoin||p.symbolKey||p.symbol),q=Math.abs(n(p.szi!=null?p.szi:(p.volume!=null?p.volume:p.lot),0)),e=n(p.entry!=null?p.entry:(p.entryPx!=null?p.entryPx:p.entry_price),0);if(c==='-'||!(q>0&&e>0))return;out.push({coin:c,raw:String(p.coin||p.displayCoin||p.symbolKey||p.symbol||''),szi:n(p.szi!=null?p.szi:(String(p.side||'').toUpperCase()==='SHORT'?-q:q),0),qty:q,entry:e,upnl:n(p.upnl,0),account:String(p._hlAccount||window._hlAccountWallet||window._userWallet||'')});});return out;}
function posFor(c){var p=livePositions();for(var i=0;i<p.length;i++)if(p[i].coin===c)return p[i];return null;}
function inferredKind(o){var k=kind(o);if(k)return k;var c=coin(o&&(o.symbol||o.coin||o._coinRaw)),p=posFor(c),v=px(o);if(!p||!(v>0))return'';if(p.szi>=0)return v>p.entry?'TP':(v<p.entry?'SL':'');return v<p.entry?'TP':(v>p.entry?'SL':'');}
function normalize(o,source){if(!o)return null;var c=coin(o.symbol||o.coin||o._coinRaw),v=px(o),q=qty(o),k=inferredKind(o);if(c==='-'||!(v>0&&q>0)||!k)return null;var p=posFor(c),s=String(o.side||o.type||'').toUpperCase(),sell=s==='A'||s==='SELL'||s.indexOf('SHORT')>=0;if(!s&&p)sell=p.szi>=0;return Object.assign({},o,{trade_id:o.trade_id||o.order_id||o.oid||('v23-'+c+'-'+k+'-'+v+'-'+q),timestamp:o.timestamp||o.created_at||new Date().toISOString(),symbol:c+'/USD',coin:c,type:sell?'SELL':'BUY',side:sell?'SELL':'BUY',direction:o.direction||k+' · ACTIVE',volume:q,lot:q,price:v,trigger_price:v,pnl:o.pnl==null?null:n(o.pnl),_pendingKind:k,_status:String(o._status||'OPEN').toUpperCase(),_source:source||o._source||o._pendingSource||'HL_ACTIVE_TPSL'});}
function fallbackRows(){var out=[],pos=livePositions(),map=window._hlSlTpByCoin||{};pos.forEach(function(p){var real=map[p.raw]||map[p.coin]||{},cands=(Array.isArray(window._enginePositions)?window._enginePositions:[]).concat(Array.isArray(window._allPending)?window._allPending:[]).concat(Array.isArray(window._sortedPending)?window._sortedPending:[]).filter(function(x){return coin(x&&(x.symbol||x.coin||x._coinRaw))===p.coin;});var sl=n(real.sl,0),tp=n(real.tp,0);cands.forEach(function(x){if(!(sl>0))sl=n(x&&(x.stop_loss!=null?x.stop_loss:(x.sl!=null?x.sl:x.stopLoss)),0);if(!(tp>0))tp=n(x&&(x.take_profit!=null?x.take_profit:(x.tp!=null?x.tp:x.takeProfit)),0);});function add(k,v){if(!(v>0))return;var sell=p.szi>=0;out.push(normalize({order_id:'fallback-'+p.coin+'-'+k+'-'+v,timestamp:new Date().toISOString(),symbol:p.coin+'/USD',side:sell?'SELL':'BUY',volume:p.qty,trigger_price:v,_pendingKind:k,_hlAccount:p.account},'POSITION_TPSL'));}add('SL',sl);add('TP',tp);});return out;}
function activeRows(st){var src=[];function add(a){if(Array.isArray(a))src=src.concat(a);}add(st&&st.pending);add(window._hlRealPending);add(window._allPending);add(window._sortedPending);add(fallbackRows());return src.map(function(x){return normalize(x,x&&x._pendingSource);}).filter(Boolean);}
function fillMap(st){var m={};(Array.isArray(st&&st.fills)?st.fills:[]).forEach(function(f){var k=oid(f&&f._hlOid);if(!k)return;(m[k]||(m[k]=[])).push(f);});return m;}
function historyRows(st,mode){var meta=mode&&mode.meta,ts=meta&&Array.isArray(meta.triggers)?meta.triggers:[],fm=fillMap(st),rows=[];ts.forEach(function(x){var o=x&&x.order||{},k=kind(o);if(!k)return;var id=oid(o.oid||o.order_id||o.cloid),fills=id?(fm[id]||[]):[],vals=fills.filter(function(f){return f&&f.pnl!=null&&Number.isFinite(Number(f.pnl));}).map(function(f){return n(f.pnl);}),pnl=vals.length?vals.reduce(function(a,b){return a+b;},0):null,v=n(o.triggerPx,0)||n(o.limitPx!=null?o.limitPx:o.px,0),q=Math.abs(n(o.sz!=null?o.sz:o.origSz,0));if(!(v>0&&q>0))return;var s=String(o.side||'').toUpperCase(),sell=s==='A'||s==='SELL',status=String(x&&x.wrap&&x.wrap.status||'UNKNOWN').toUpperCase(),t=n(x&&x.wrap&&x.wrap.statusTimestamp,0)||n(o.timestamp,0)||Date.now();rows.push(normalize({trade_id:id||('hist-'+rows.length),timestamp:new Date(t).toISOString(),symbol:coin(o.coin||o.symbol)+'/USD',type:sell?'SELL':'BUY',side:sell?'SELL':'BUY',direction:k+' · '+status,volume:q,lot:q,price:v,trigger_price:v,pnl:pnl,_pendingKind:k,_status:status,_hlAccount:x.account,_hlOid:id,_parentOid:x.parentOid,_source:'HL_HISTORY_TRIGGER'},'HL_HISTORY_TRIGGER'));});return rows.filter(Boolean);}
function dedupe(rows){var seen={},out=[];(rows||[]).forEach(function(x){if(!x)return;var id=oid(x._hlOid||x.order_id||x.oid||x.trade_id),k=id?('OID|'+id):[coin(x.symbol),x._pendingKind,n(x.trigger_price||x.price).toPrecision(12),qty(x).toPrecision(12),String(x._status||'')].join('|');if(seen[k]){var old=seen[k];if(String(old._status||'').indexOf('OPEN')>=0&&String(x._status||'').indexOf('OPEN')<0){Object.assign(old,x);}return;}seen[k]=x;out.push(x);});out.sort(function(a,b){return tm(b.timestamp)-tm(a.timestamp);});return out;}
function pendingRows(st,mode){return dedupe(activeRows(st).concat(historyRows(st,mode)));}
function fingerprint(rows){return(rows||[]).map(function(x){return[oid(x._hlOid||x.trade_id),coin(x.symbol),x._pendingKind,n(x.trigger_price||x.price),qty(x),x._status].join(':');}).join('|');}
function fmtMoney(v){if(v==null||!Number.isFinite(Number(v)))return'—';v=Number(v);return(v>=0?'+$':'-$')+Math.abs(v).toFixed(4);}
function fmtPct(v){return v!=null&&Number.isFinite(Number(v))?Number(v).toFixed(2)+'%':'—';}
function fmtRR(v){return v!=null&&Number.isFinite(Number(v))&&Number(v)>=0?Number(v).toFixed(2):'—';}
function pendingMetrics(st,mode,rows){var hist=rows.filter(function(r){return String(r._source||'')==='HL_HISTORY_TRIGGER';}),filled=hist.filter(function(r){return r.pnl!=null&&/(FILLED|TRIGGERED|EXECUTED)/.test(String(r._status||''));}),wins=filled.filter(function(r){return n(r.pnl)>1e-12;}),losses=filled.filter(function(r){return n(r.pnl)<-1e-12;}),tp=filled.filter(function(r){return r._pendingKind==='TP';}),sl=filled.filter(function(r){return r._pendingKind==='SL';}),pnl=filled.reduce(function(a,r){return a+n(r.pnl);},0),avgW=wins.length?wins.reduce(function(a,r){return a+n(r.pnl);},0)/wins.length:0,avgL=losses.length?Math.abs(losses.reduce(function(a,r){return a+n(r.pnl);},0)/losses.length):0,parents={};Object.keys(mode&&mode.meta&&mode.meta.parentBracket||{}).forEach(function(k){parents[k]=1;});hist.forEach(function(r){if(r._parentOid)parents[r._parentOid]=1;});var activeSymbols={};rows.filter(function(r){return String(r._source||'')!=='HL_HISTORY_TRIGGER';}).forEach(function(r){activeSymbols[coin(r.symbol)]=1;});var entries=Object.keys(parents).length||Object.keys(activeSymbols).length,dec=tp.length+sl.length;return{pnl:filled.length?pnl:null,entries:entries,prob:dec?tp.length*100/dec:null,rr:avgL>1e-12?avgW/avgL:null};}
function paintSummary(rows,st,mode){var b=document.getElementById('ctlHistoryPnlSummaryV11');if(!b)return;var m=pendingMetrics(st,mode,rows);function sp(l,v,c){return'<span><span style="color:var(--text-muted);font-weight:700">'+l+'</span> <b style="color:'+c+'">'+v+'</b></span>';}b.style.display='flex';b.innerHTML=sp('PNL',fmtMoney(m.pnl),m.pnl==null?'var(--text-muted)':(m.pnl>=0?'var(--green)':'var(--red)'))+sp('TOTAL ENTRY',String(n(m.entries,0)),'var(--accent)')+sp('PROBABILITAS',fmtPct(m.prob),m.prob!=null&&m.prob>=50?'var(--green)':'var(--gold)')+sp('RISK/REWARD',fmtRR(m.rr),m.rr!=null&&m.rr>=1?'var(--green)':'var(--gold)');}
function paintEmpty(rows){var e=document.getElementById('emptyHistory'),t=document.getElementById('historyTable');if(rows.length){if(e)e.style.display='none';if(t)t.style.display='';return;}if(t)t.style.display='none';if(!e)return;e.style.display='';var a=e.querySelector('.text'),b=e.querySelector('.sub');if(a)a.textContent='Belum ada riwayat TP/SL Hyperliquid';if(b)b.textContent='Menunggu historicalOrders Hyperliquid; order aktif akan digabungkan tanpa menghapus history sebelumnya.';}
function pendingDomMatches(rows){var tb=document.getElementById('historyTableBody'),e=document.getElementById('emptyHistory'),t=document.getElementById('historyTable');if(!tb)return true;var want=Math.min(20,rows.length),trs=tb.querySelectorAll('tr');if(trs.length!==want)return false;if(rows.length){if(e&&getComputedStyle(e).display!=='none')return false;if(t&&getComputedStyle(t).display==='none')return false;for(var i=0;i<want;i++){var text=String(trs[i].textContent||'').toUpperCase(),r=rows[i],sym=coin(r.symbol),k=String(r._pendingKind||'').toUpperCase();if(sym!=='-'&&text.indexOf(sym)<0)return false;if(k&&text.indexOf(k)<0)return false;}return true;}return !t||getComputedStyle(t).display==='none';}
function ensureChartSingleWriter(){var base=document.getElementById('equityChart'),overlay=document.getElementById('ctlEquityChartV22');if(!base)return false;var style=document.getElementById('ctlV23ChartSingleWriterStyle');if(!style){style=document.createElement('style');style.id='ctlV23ChartSingleWriterStyle';style.textContent='#equityChart{visibility:hidden!important;opacity:0!important}#ctlEquityChartV22{visibility:visible!important;opacity:1!important}';(document.head||document.documentElement).appendChild(style);}base.style.setProperty('visibility','hidden','important');base.style.setProperty('opacity','0','important');if(overlay){overlay.style.setProperty('visibility','visible','important');overlay.style.setProperty('opacity','1','important');overlay.style.setProperty('z-index','20','important');}return !!overlay;}
function ensureV19(){if(window.__CTL_HL_PENDING_V19__&&window.__CTL_HL_PENDING_V19__.ready)return true;if(typeof window.__ctlInstallHlPendingV19==='function'){try{window.__ctlInstallHlPendingV19();}catch(e){}return !!(window.__CTL_HL_PENDING_V19__&&window.__CTL_HL_PENDING_V19__.ready);}if(document.getElementById('ctlHlPendingV19ForV23'))return false;var s=document.createElement('script');s.id='ctlHlPendingV19ForV23';s.src='history_hl_pending_v19.js?v=20260827-v23-history-active';s.async=false;s.onload=function(){try{window.__ctlInstallHlPendingV19&&window.__ctlInstallHlPendingV19();}catch(e){}};(document.head||document.documentElement).appendChild(s);return false;}
function install(){var st=window.__CTL_HISTORY_STABLE__,m=window.__CTL_HISTORY_MODE_V20__;if(!st||st.version<10||!m||!m.ready){setTimeout(install,120);return false;}var old=window.__CTL_HL_FIX_V23__;if(old){try{if(old.timer)clearInterval(old.timer);}catch(e){}try{if(old.observer)old.observer.disconnect();}catch(e){}}var baseRender=(st.render&&st.render.__ctlV23Base)?st.render.__ctlV23Base:st.render,state={ready:true,version:VERSION,timer:null,lastFp:'',baseRender:baseRender,source:'pending-history-hybrid+active-tpsl+chart-single-writer+dom-arbiter',rendering:false,repairQueued:false,repairs:0};window.__CTL_HL_FIX_V23__=state;
  function render(){var rows=null;if(st.mode==='pending'){rows=pendingRows(st,m);m.triggerRows=rows;}state.rendering=true;try{var r=state.baseRender.apply(st,arguments);if(st.mode==='pending'){paintSummary(rows||[],st,m);paintEmpty(rows||[]);}ensureChartSingleWriter();return r;}finally{state.rendering=false;}}
  render.__ctlV23=true;render.__ctlV23Base=baseRender;st.render=render;
  function repair(){state.repairQueued=false;if(state.rendering||st.mode!=='pending')return;var rows=pendingRows(st,m);if(!pendingDomMatches(rows)){m.triggerRows=rows;state.repairs++;try{st.render();}catch(e){state.lastError=String(e&&e.message||e);}}}
  function queueRepair(){if(state.repairQueued||state.rendering||st.mode!=='pending')return;state.repairQueued=true;Promise.resolve().then(repair);}
  function tick(){ensureV19();ensureChartSingleWriter();if(st.mode==='pending'){var rows=pendingRows(st,m),fp=fingerprint(rows),bad=!pendingDomMatches(rows);if(fp!==state.lastFp||bad){state.lastFp=fp;m.triggerRows=rows;try{st.render();}catch(e){state.lastError=String(e&&e.message||e);}}else{paintSummary(rows,st,m);paintEmpty(rows);}}}
  tick();state.timer=setInterval(tick,POLL);if(window.MutationObserver&&document.body){state.observer=new MutationObserver(function(ms){ensureChartSingleWriter();if(state.rendering||st.mode!=='pending')return;for(var i=0;i<ms.length;i++){var target=ms[i].target;if(target&&((target.id==='historyTableBody')||(target.id==='ctlHistoryPnlSummaryV11')||(target.id==='emptyHistory')||(target.closest&&target.closest('#historyTableBody,#ctlHistoryPnlSummaryV11,#emptyHistory')))){queueRepair();break;}}});state.observer.observe(document.body,{childList:true,subtree:true,characterData:true});}return true;
}
window.__ctlInstallHlFixV23=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
