(function(){
'use strict';
var VERSION=31,EPS=1e-12;
var INNER=Object.getOwnPropertyDescriptor(Element.prototype,'innerHTML');
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function tm(v){if(typeof v==='number'&&Number.isFinite(v))return v;var x=Date.parse(v||'');return Number.isFinite(x)?x:0;}
function oid(v){return v==null?'':String(v);}
function acct(v){return String(v||'').toLowerCase();}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function money(v){if(v==null||!Number.isFinite(Number(v)))return'—';v=Number(v);return(v>=0?'+$':'-$')+Math.abs(v).toFixed(4);}
function pct(v){return v!=null&&Number.isFinite(Number(v))?Number(v).toFixed(2)+'%':'—';}
function rr(v){return v!=null&&Number.isFinite(Number(v))&&Number(v)>=0?Number(v).toFixed(2):'—';}
function maps(){var m=window.__CTL_HISTORY_MODE_V20__||{},meta=m.meta||{},parents={},children={};Object.keys(meta.parentBracket||{}).forEach(function(k){if(k)parents[oid(k)]=1;});(Array.isArray(meta.triggers)?meta.triggers:[]).forEach(function(t){var o=t&&t.order||{},p=oid(t&&t.parentOid),c=oid(o.oid||o.order_id||o.cloid);if(p)parents[p]=1;if(c&&p)children[c]=p;});return{parents:parents,children:children};}
function entryCat(f,mp){var k=oid(f&&f._hlOid);return k&&mp.parents[k]?'pending':'direct';}
function closeCat(f,mp){var k=oid(f&&f._hlOid);return k&&mp.children[k]?'pending':'direct';}
function orderKey(f,idx){var a=acct(f&&f._hlAccount),k=oid(f&&f._hlOid);if(k)return a+'|OID|'+k;var t=oid(f&&f.trade_id);if(t)return a+'|TID|'+t;return a+'|FALLBACK|'+coin(f&&f.symbol)+'|'+tm(f&&f.timestamp)+'|'+n(f&&f.price)+'|'+idx;}
function bucketKey(f){return acct(f&&f._hlAccount)+'|'+coin(f&&f.symbol);}
function build(st){var mp=maps(),fills=(Array.isArray(st&&st.fills)?st.fills:[]).slice().sort(function(a,b){return tm(a&&a.timestamp)-tm(b&&b.timestamp);}),orders={},buckets={},fallback={pending:0,direct:0},rawClosePnl=0,entryMissingOid=0;
 function bucket(f){var k=bucketKey(f);return buckets[k]||(buckets[k]=[]);}
 function addEntry(f,q,idx){q=Math.abs(n(q,0));if(!(q>EPS))return;var k=orderKey(f,idx),cat=entryCat(f,mp),o=orders[k];if(!oid(f&&f._hlOid))entryMissingOid++;if(!o){o=orders[k]={key:k,category:cat,initial:0,remaining:0,realized:0,first:tm(f&&f.timestamp),last:tm(f&&f.timestamp),symbol:coin(f&&f.symbol),account:acct(f&&f._hlAccount),oid:oid(f&&f._hlOid)};bucket(f).push(o);}else if(o.category!==cat&&cat==='pending')o.category='pending';o.initial+=q;o.remaining+=q;o.last=Math.max(o.last,tm(f&&f.timestamp));}
 function activeTotal(arr){return arr.reduce(function(s,o){return s+(o.remaining>EPS?o.remaining:0);},0);}
 function allocClose(f,q,pnl){q=Math.abs(n(q,0));pnl=n(pnl,0);rawClosePnl+=pnl;var arr=bucket(f),total=activeTotal(arr);if(!(total>EPS)){fallback[closeCat(f,mp)]+=pnl;return;}var closeQty=q>EPS?Math.min(q,total):total;if(!(closeQty>EPS)){fallback[closeCat(f,mp)]+=pnl;return;}var alloc=pnl*(q>EPS?Math.min(1,closeQty/q):1),res=pnl-alloc,ratio=Math.min(1,closeQty/total),live=arr.filter(function(o){return o.remaining>EPS;}),used=0;live.forEach(function(o,i){var take=i===live.length-1?Math.max(0,closeQty-used):Math.min(o.remaining,o.remaining*ratio);take=Math.min(take,o.remaining);used+=take;o.realized+=alloc*(closeQty>EPS?take/closeQty:0);o.remaining=Math.max(0,o.remaining-take);o.last=Math.max(o.last,tm(f&&f.timestamp));});if(Math.abs(res)>EPS)fallback[closeCat(f,mp)]+=res;}
 fills.forEach(function(f,idx){if(!f)return;var cls=String(f._fillClass||'').toUpperCase(),q=Math.abs(n(f.volume!=null?f.volume:f.lot,0)),p=f.pnl==null?0:n(f.pnl,0);if(cls==='ENTRY'||f.is_entry===true){addEntry(f,q,idx);return;}if(cls==='FLIP'){var before=activeTotal(bucket(f)),cq=Math.min(q,before);if(cq>EPS)allocClose(f,cq,p);var oq=Math.max(0,q-cq);if(oq>EPS)addEntry(f,oq,idx);return;}if(cls==='CLOSE'||f.pnl!=null)allocClose(f,q,p);});
 function metric(cat){var os=Object.keys(orders).map(function(k){return orders[k];}).filter(function(o){return cat==='all'||o.category===cat;}),real=os.reduce(function(s,o){return s+n(o.realized);},0)+(cat==='all'?fallback.pending+fallback.direct:fallback[cat]),closed=os.filter(function(o){return o.initial>EPS&&o.remaining<=Math.max(EPS,o.initial*1e-9);}),wins=closed.filter(function(o){return o.realized>EPS;}),losses=closed.filter(function(o){return o.realized<-EPS;}),gp=wins.reduce(function(s,o){return s+o.realized;},0),gl=Math.abs(losses.reduce(function(s,o){return s+o.realized;},0)),avgW=wins.length?gp/wins.length:0,avgL=losses.length?gl/losses.length:0,dec=wins.length+losses.length;return{pnl:(os.length||Math.abs(real)>EPS)?real:null,entries:os.length,prob:dec?wins.length*100/dec:null,rr:avgL>EPS?avgW/avgL:null,closed:closed.length,wins:wins.length,losses:losses.length};}
 var pending=metric('pending'),direct=metric('direct'),all=metric('all');all.entries=pending.entries+direct.entries;all.pnl=fills.some(function(f){return f&&f.pnl!=null&&!f.is_entry;})?rawClosePnl:null;var split=n(pending.pnl,0)+n(direct.pnl,0),delta=(all.pnl==null?0:all.pnl)-split;if(Math.abs(delta)>1e-9){direct.pnl=(direct.pnl==null?0:direct.pnl)+delta;}return{all:all,pending:pending,direct:direct,fillCount:fills.length,parentCount:Object.keys(mp.parents).length,rawClosePnl:rawClosePnl,entryMissingOid:entryMissingOid,invariantEntries:all.entries===pending.entries+direct.entries,invariantPnl:all.pnl==null?pending.pnl==null&&direct.pnl==null:Math.abs(all.pnl-(n(pending.pnl,0)+n(direct.pnl,0)))<1e-8};}
function state(){return window.__CTL_REAL_METRICS_V31__;}
function ensureBar(){var filters=document.getElementById('historyTypeFilters');if(!filters)return null;var b=document.getElementById('ctlHistoryPnlSummaryV11');if(!b){b=document.createElement('div');b.id='ctlHistoryPnlSummaryV11';filters.parentNode.insertBefore(b,filters);}b.style.cssText='display:flex;align-items:center;gap:32px;flex-wrap:wrap;margin:0 0 10px 0;padding:13px 16px;border:1px solid var(--border);border-radius:10px;background:rgba(5,14,26,.78);font-family:JetBrains Mono,monospace;font-size:12px;line-height:1.4;';if(!b.__ctlV31Lock&&INNER){try{Object.defineProperty(b,'innerHTML',{configurable:true,enumerable:true,get:function(){return INNER.get.call(this);},set:function(v){var s=state();if(!s||s.allow>0){INNER.set.call(this,String(v));return;}s.blocked++;}});b.__ctlV31Lock=true;}catch(e){}}return b;}
function span(l,v,c){return'<span><span style="color:var(--text-muted);font-weight:700">'+l+'</span> <b style="color:'+c+'">'+v+'</b></span>';}
var cache={sig:'',ledger:null};
function signature(st){var f=Array.isArray(st&&st.fills)?st.fills:[],m=window.__CTL_HISTORY_MODE_V20__,meta=m&&m.meta||{},parents=Object.keys(meta.parentBracket||{}).sort().join(','),triggers=(meta.triggers||[]).map(function(t){var o=t&&t.order||{};return oid(o.oid||o.order_id||o.cloid)+':'+oid(t&&t.parentOid);}).sort().join(',');return[f.length,f[0]&&f[0].trade_id,f[0]&&f[0].timestamp,f[f.length-1]&&f[f.length-1].trade_id,parents,triggers].join('|');}
function ledger(st){var s=signature(st);if(cache.sig!==s||!cache.ledger){cache.sig=s;cache.ledger=build(st);}return cache.ledger;}
function paint(st){if(!st)return false;var mode=['all','pending','direct'].indexOf(st.mode)>=0?st.mode:'all',l=ledger(st),m=l[mode],b=ensureBar(),s=state();if(!b||!s)return false;var html=span('PNL',money(m.pnl),m.pnl==null?'var(--text-muted)':(m.pnl>=0?'var(--green)':'var(--red)'))+span('TOTAL ENTRY',String(n(m.entries,0)),'var(--accent)')+span('PROBABILITAS',pct(m.prob),m.prob!=null&&m.prob>=50?'var(--green)':'var(--gold)')+span('RISK/REWARD',rr(m.rr),m.rr!=null&&m.rr>=1?'var(--green)':'var(--gold)');s.allow++;try{if(INNER)INNER.set.call(b,html);else b.innerHTML=html;b.style.setProperty('display','flex','important');b.dataset.metricVersion=String(VERSION);b.dataset.metricMode=mode;b.dataset.invariantEntries=String(l.invariantEntries);b.dataset.invariantPnl=String(l.invariantPnl);b.title='V31 canonical Hyperliquid ledger. ALL entries = Pending + Langsung Entry; ALL PNL = Pending + Langsung Entry = raw userFills closedPnl. Probability/RR are recomputed from fully closed entry orders in the selected partition.';}finally{s.allow--;}s.lastLedger=l;s.lastMode=mode;return true;}
function install(){var st=window.__CTL_HISTORY_STABLE__;if(!st||st.version<10||typeof st.render!=='function'){setTimeout(install,80);return false;}var old=state();if(old&&old.ready&&st.render&&st.render.__ctlV31){paint(st);return true;}var base=st.render,stateObj={ready:true,version:VERSION,source:'single-summary-writer+real-userfills-oid-ledger+exclusive-partitions',baseRender:base,lastLedger:null,lastMode:'',allow:0,blocked:0,timer:null};window.__CTL_REAL_METRICS_V31__=stateObj;function render(){var r=base.apply(st,arguments);paint(st);return r;}render.__ctlV31=true;render.__ctlV23=base.__ctlV23===true;render.__ctlV23Base=base.__ctlV23Base||null;st.render=render;try{st.render();}catch(e){stateObj.lastError=String(e&&e.message||e);paint(st);}stateObj.timer=setInterval(function(){try{paint(st);}catch(e){stateObj.lastError=String(e&&e.message||e);}},500);return true;}
window.__ctlInstallRealMetricsV31=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
