(function(){
'use strict';
function install(){
  var d=document,old=window.__CTL_HISTORY_V7_GUARD__;
  if(old&&old.timer)try{clearInterval(old.timer);}catch(e){}
  ['__CTL_HL_PENDING_V13__','__CTL_HL_PENDING_BRIDGE_V14__','__CTL_HL_LIVE_PENDING_V16__','__CTL_HL_PENDING_V17__','__CTL_HL_PENDING_V18__','__CTL_HL_PENDING_V19__','__CTL_HL_SUMMARY_V16__','__CTL_HL_SUMMARY_V17__','__CTL_HL_SUMMARY_V18__','__CTL_HL_SUMMARY_V19__','__CTL_HL_MARKET_ONLY_V18__'].forEach(function(k){var x=window[k];if(x&&x.timer)try{clearInterval(x.timer);}catch(e){}if(x&&x.refreshTimer)try{clearInterval(x.refreshTimer);}catch(e){}if(x&&x.balanceTimer)try{clearInterval(x.balanceTimer);}catch(e){}});
  var legacy=window.__CTL_HL_PORTFOLIO_V21__;if(legacy){try{if(legacy.timer)clearInterval(legacy.timer);}catch(e){}try{if(legacy.observer)legacy.observer.disconnect();}catch(e){}legacy.disabledBy='v22';}
  function inject(id,src,onload){try{var prev=d.getElementById(id);if(prev){if(prev.dataset&&prev.dataset.loading==='1')return true;try{prev.remove();}catch(e){}}var s=d.createElement('script');s.id=id;s.src=src;s.async=false;if(s.dataset)s.dataset.loading='1';s.onload=function(){if(s.dataset)s.dataset.loading='0';if(onload)onload();};s.onerror=function(){try{s.remove();}catch(e){}};(d.head||d.documentElement).appendChild(s);return true;}catch(e){return false;}}
  function loadV10(){if(window.__CTL_HISTORY_STABLE__&&window.__CTL_HISTORY_STABLE__.version>=10)return true;if(typeof window.__ctlInstallHlHistoryV10==='function'){try{window.__ctlInstallHlHistoryV10();}catch(e){}return !!(window.__CTL_HISTORY_STABLE__&&window.__CTL_HISTORY_STABLE__.version>=10);}inject('ctlHlHistoryV10Script','history_hl_runtime_v10.js?v=20260827-2',function(){try{window.__ctlInstallHlHistoryV10&&window.__ctlInstallHlHistoryV10();}catch(e){}});return false;}
  function mode20Ok(){var m=window.__CTL_HISTORY_MODE_V20__;return !!(m&&m.ready&&m.renderOwnerAware===true);}
  function loadMode20(){if(!(window.__CTL_HISTORY_STABLE__&&window.__CTL_HISTORY_STABLE__.version>=10))return false;if(mode20Ok())return true;inject('ctlHlModeV20Script','history_hl_mode_v20.js?v=20260827-owner-aware-5',function(){try{window.__ctlInstallHlModeV20&&window.__ctlInstallHlModeV20();}catch(e){}});return false;}
  function loadInfer20(){if(!mode20Ok())return false;if(window.__CTL_HISTORY_MODE_V20_INFER__&&window.__CTL_HISTORY_MODE_V20_INFER__.ready)return true;if(typeof window.__ctlInstallHlModeV20Infer==='function'){try{window.__ctlInstallHlModeV20Infer();}catch(e){}return !!(window.__CTL_HISTORY_MODE_V20_INFER__&&window.__CTL_HISTORY_MODE_V20_INFER__.ready);}inject('ctlHlModeV20InferScript','history_hl_mode_v20_infer.js?v=20260827-real-1',function(){try{window.__ctlInstallHlModeV20Infer&&window.__ctlInstallHlModeV20Infer();}catch(e){}});return false;}
  function loadUi22(){if(!(window.__CTL_HISTORY_STABLE__&&window.__CTL_HISTORY_STABLE__.version>=10))return false;if(window.__CTL_HL_UI_ARBITER_V22__&&window.__CTL_HL_UI_ARBITER_V22__.ready)return true;if(typeof window.__ctlInstallHlUiArbiterV22==='function'){try{window.__ctlInstallHlUiArbiterV22();}catch(e){}return !!(window.__CTL_HL_UI_ARBITER_V22__&&window.__CTL_HL_UI_ARBITER_V22__.ready);}inject('ctlHlUiArbiterV22Script','history_hl_ui_arbiter_v22.js?v=20260827-single-writer-1',function(){try{window.__ctlInstallHlUiArbiterV22&&window.__ctlInstallHlUiArbiterV22();}catch(e){}});return false;}
  function fix23Ok(){var f=window.__CTL_HL_FIX_V23__,st=window.__CTL_HISTORY_STABLE__;return !!(mode20Ok()&&f&&f.ready&&String(f.source||'').indexOf('pending-dom-arbiter')>=0&&st&&st.render&&st.render.__ctlV23===true);}
  function loadFix23(){if(!mode20Ok())return false;if(fix23Ok())return true;if(typeof window.__ctlInstallHlFixV23==='function'){try{window.__ctlInstallHlFixV23();}catch(e){}if(fix23Ok())return true;}inject('ctlHlFixV23Script','history_hl_fix_v23.js?v=20260827-pending-dom-arbiter-4',function(){try{window.__ctlInstallHlFixV23&&window.__ctlInstallHlFixV23();}catch(e){}});return false;}
  var state={ready:true,version:23,source:'persistent-v10+owner-aware-v20+ui-v22+active-tpsl+pending-dom-arbiter-v23',timer:null};window.__CTL_HISTORY_V7_GUARD__=state;
  loadV10();loadMode20();loadInfer20();loadUi22();loadFix23();
  state.timer=setInterval(function(){var a=loadV10(),b=loadMode20(),c=loadInfer20(),u=loadUi22(),f=loadFix23();if(a&&b&&c&&u&&f){clearInterval(state.timer);state.timer=null;}},500);
  return true;
}
window.__ctlInstallHlHistoryV7Guard=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
