(function(){
'use strict';
var TICK=700,CACHE='ctl_hl_live_pending_v16';
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function fmtMoney(v){if(v==null||!Number.isFinite(Number(v)))return'—';v=Number(v);return(v>=0?'+$':'-$')+Math.abs(v).toFixed(4);}
function fmtPct(v){return Number.isFinite(v)?v.toFixed(2)+'%':'—';}
function fmtRR(v){return Number.isFinite(v)&&v>=0?v.toFixed(2):'—';}
function closedMetrics(fills){var vals=(fills||[]).filter(function(x){return x&&!x.is_entry&&x.pnl!=null&&Math.abs(n(x.pnl,0))>1e-12;}).map(function(x){return n(x.pnl,0);}),wins=vals.filter(function(v){return v>0;}),loss=vals.filter(function(v){return v<0;}),sum=vals.reduce(function(a,b){return a+b;},0),avgW=wins.length?wins.reduce(function(a,b){return a+b;},0)/wins.length:0,avgL=loss.length?Math.abs(loss.reduce(function(a,b){return a+b;},0)/loss.length):0;return{pnl:sum,prob:vals.length?wins.length*100/vals.length:null,rr:avgL>0?avgW/avgL:null,total:vals.length};}
function cachedMetrics(){try{var x=JSON.parse(localStorage.getItem(CACHE)||'null');if(x&&x.metrics&&Date.now()-n(x.at,0)<300000)return x.metrics;}catch(e){}return null;}
function pendingMetrics(){var m=window.__CTL_HL_PENDING_LIVE_METRICS__;if(m&&Date.now()-n(m.at,0)<300000&&(n(m.entries,0)>0||n(m.orders,0)>0))return m;return cachedMetrics()||m||{pnl:null,entries:0,rr:null};}
function ensureBar(){var f=document.getElementById('historyTypeFilters');if(!f)return null;var b=document.getElementById('ctlHistoryPnlSummaryV11');if(!b){b=document.createElement('div');b.id='ctlHistoryPnlSummaryV11';f.parentNode.insertBefore(b,f);}b.style.cssText='display:none;align-items:center;gap:28px;flex-wrap:wrap;margin:0 0 10px 0;padding:12px 14px;border:1px solid var(--border);border-radius:10px;background:rgba(5,14,26,.78);font-family:JetBrains Mono,monospace;font-size:11px;line-height:1.4;';return b;}
function span(l,v,c){return'<span><span style="color:var(--text-muted);font-weight:700">'+l+'</span> <b style="color:'+c+'">'+v+'</b></span>';}
function paint(){var st=window.__CTL_HISTORY_STABLE__,bar=ensureBar();if(!st||st.version<10||!bar)return false;var mode=st.mode||window._historyTypeFilter||'all',info=document.getElementById('tradeLogInfo');if(mode!=='pending'&&mode!=='direct'){bar.style.display='none';if(info)info.style.display='';return true;}if(info)info.style.display='none';var c=closedMetrics(Array.isArray(st.fills)?st.fills:[]),html='';if(mode==='direct'){var total=(st.fills||[]).filter(function(x){return x&&x.is_entry;}).length;html+=span('PNL',fmtMoney(c.pnl),c.pnl>=0?'var(--green)':'var(--red)');html+=span('TOTAL ENTRY',String(total),'var(--accent)');html+=span('PROBABILITAS',fmtPct(c.prob),c.prob!=null&&c.prob>=50?'var(--green)':'var(--gold)');html+=span('RISK/REWARD',fmtRR(c.rr),c.rr!=null&&c.rr>=1?'var(--green)':'var(--gold)');}else{var p=pendingMetrics();html+=span('PNL',fmtMoney(p.pnl),p.pnl==null?'var(--text-muted)':(p.pnl>=0?'var(--green)':'var(--red)'));html+=span('TOTAL ENTRY',String(n(p.entries,0)),'var(--accent)');html+=span('PROBABILITAS',fmtPct(c.prob),c.prob!=null&&c.prob>=50?'var(--green)':'var(--gold)');html+=span('RISK/REWARD',fmtRR(p.rr),p.rr!=null&&p.rr>=1?'var(--green)':'var(--gold)');}bar.innerHTML=html;bar.style.display='flex';return true;}
function install(){['__CTL_HL_SUMMARY_V11__','__CTL_HL_SUMMARY_V12__','__CTL_HL_SUMMARY_V15__','__CTL_HL_SUMMARY_V16__'].forEach(function(k){var x=window[k];if(x&&x.timer)try{clearInterval(x.timer);}catch(e){}if(x&&x.balanceTimer)try{clearInterval(x.balanceTimer);}catch(e){}});var s={ready:true,version:16,timer:setInterval(paint,TICK),paint:paint};window.__CTL_HL_SUMMARY_V16__=s;paint();return true;}
window.__ctlInstallHlSummaryV16=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();