(function(){
'use strict';
var TICK=1200;
function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d==null?0:d);}
function tm(v){if(typeof v==='number'&&Number.isFinite(v))return v;var x=Date.parse(v||'');return Number.isFinite(x)?x:0;}
function coin(v){v=String(v||'').toUpperCase().trim();if(v.indexOf(':')>=0)v=v.split(':').pop();return v.replace('/USDC','').replace('/USDT','').replace('/USD','').replace('-USD','')||'-';}
function text(id,v){var e=document.getElementById(id);if(e)e.textContent=v;}
function color(id,v,c){var e=document.getElementById(id);if(e){e.textContent=v;if(c)e.style.color=c;}}
function money(v){v=n(v,0);return(v>=0?'+$':'-$')+Math.abs(v).toFixed(4);}
function plainMoney(v){v=n(v,0);return(v<0?'-$':'$')+Math.abs(v).toFixed(4);}
function direction(t){var d=String(t&&(t._hlDir||t.direction)||'').toUpperCase();if(d.indexOf('LONG')>=0)return'LONG';if(d.indexOf('SHORT')>=0)return'SHORT';var s=String(t&&(t.side||t.type)||'').toUpperCase();return s.indexOf('SELL')>=0?'SHORT':'LONG';}
function uniqueFills(rows){var seen={},out=[];(rows||[]).forEach(function(x){if(!x)return;var k=[x._hlAccount||'',x.trade_id||'',x.timestamp||'',coin(x.symbol||x.coin),n(x.price,0),n(x.volume||x.lot,0),x.is_entry?'E':'C'].join('|');if(seen[k])return;seen[k]=1;out.push(x);});return out;}
function closedFills(st){return uniqueFills(Array.isArray(st&&st.fills)?st.fills:[]).filter(function(x){return x&&!x.is_entry&&x.pnl!=null&&Number.isFinite(Number(x.pnl));}).sort(function(a,b){return tm(a.timestamp)-tm(b.timestamp);});}
function initCapital(){var x=n(window._tradeLogInitialBalance,0);if(x>0)return x;try{x=n(document.getElementById('dInitDeposit')&&String(document.getElementById('dInitDeposit').textContent||'').replace(/[^0-9.-]/g,''),0);}catch(e){}return x>0?x:13.40;}
function streaks(trades){var maxW=0,maxL=0,cw=0,cl=0,wRuns=[],lRuns=[];function endW(){if(cw){wRuns.push(cw);if(cw>maxW)maxW=cw;cw=0;}}function endL(){if(cl){lRuns.push(cl);if(cl>maxL)maxL=cl;cl=0;}}trades.forEach(function(t){var p=n(t.pnl,0);if(p>0){endL();cw++;}else{endW();cl++;}});endW();endL();var aw=wRuns.length?wRuns.reduce(function(a,b){return a+b;},0)/wRuns.length:0,al=lRuns.length?lRuns.reduce(function(a,b){return a+b;},0)/lRuns.length:0;return{maxW:maxW,maxL:maxL,avgW:aw,avgL:al};}
function metrics(st){var trades=closedFills(st),wins=trades.filter(function(t){return n(t.pnl,0)>0;}),losses=trades.filter(function(t){return n(t.pnl,0)<=0;}),positiveLosses=trades.filter(function(t){return n(t.pnl,0)<0;}),grossProfit=wins.reduce(function(s,t){return s+n(t.pnl,0);},0),grossLoss=Math.abs(positiveLosses.reduce(function(s,t){return s+n(t.pnl,0);},0)),total=trades.reduce(function(s,t){return s+n(t.pnl,0);},0),init=initCapital(),eq=init,peak=init,maxDD=0,maxDDpct=0,minEq=init,points=[init];trades.forEach(function(t){eq+=n(t.pnl,0);points.push(eq);if(eq>peak)peak=eq;var dd=peak-eq;if(dd>maxDD)maxDD=dd;var pct=peak>0?dd/peak*100:0;if(pct>maxDDpct)maxDDpct=pct;if(eq<minEq)minEq=eq;});var avgProfit=wins.length?grossProfit/wins.length:0,avgLoss=positiveLosses.length?grossLoss/positiveLosses.length:0,pf=grossLoss>1e-12?grossProfit/grossLoss:(grossProfit>0?Infinity:0),rr=avgLoss>1e-12?avgProfit/avgLoss:null,payoff=trades.length?total/trades.length:0,recovery=maxDD>1e-12?total/maxDD:null,largestProfit=wins.length?Math.max.apply(null,wins.map(function(t){return n(t.pnl,0);})):0,largestLoss=positiveLosses.length?Math.min.apply(null,positiveLosses.map(function(t){return n(t.pnl,0);})):0,longs=trades.filter(function(t){return direction(t)==='LONG';}),shorts=trades.filter(function(t){return direction(t)==='SHORT';}),longWins=longs.filter(function(t){return n(t.pnl,0)>0;}).length,shortWins=shorts.filter(function(t){return n(t.pnl,0)>0;}).length,streak=streaks(trades),symbols={};trades.forEach(function(t){symbols[coin(t.symbol||t.coin)]=1;});return{trades:trades,wins:wins,losses:losses,grossProfit:grossProfit,grossLoss:grossLoss,total:total,init:init,points:points,maxDD:maxDD,maxDDpct:maxDDpct,absDD:Math.max(0,init-minEq),avgProfit:avgProfit,avgLoss:avgLoss,pf:pf,rr:rr,payoff:payoff,recovery:recovery,largestProfit:largestProfit,largestLoss:largestLoss,longs:longs,shorts:shorts,longWins:longWins,shortWins:shortWins,streak:streak,symbolCount:Object.keys(symbols).filter(function(x){return x&&x!=='-';}).length};}
function paintChart(m){var canvas=document.getElementById('equityChart');if(!canvas||!canvas.getContext)return;var wrap=document.getElementById('equityChartWrap');if(wrap){var h=wrap.querySelector('div');if(h)h.textContent='📈 Grafik Pertumbuhan Equity · HYPERLIQUID · ALL PAIRS · '+m.symbolCount+' SYMBOL · '+m.trades.length+' CLOSED FILLS';}var cssW=Math.max(600,Math.floor(canvas.clientWidth||1100)),cssH=Math.max(180,Math.floor(canvas.clientHeight||220)),dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1));if(canvas.width!==cssW*dpr)canvas.width=cssW*dpr;if(canvas.height!==cssH*dpr)canvas.height=cssH*dpr;var c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,cssW,cssH);var pts=m.points.length?m.points:[m.init],lo=Math.min.apply(null,pts),hi=Math.max.apply(null,pts);if(!(hi>lo)){hi=lo+1;}var pad={l:62,r:22,t:18,b:25},w=cssW-pad.l-pad.r,h=cssH-pad.t-pad.b,range=hi-lo,margin=range*.08;lo-=margin;hi+=margin;range=hi-lo;function X(i){return pad.l+(pts.length<=1?0:i/(pts.length-1))*w;}function Y(v){return pad.t+h-(v-lo)/range*h;}c.font='12px JetBrains Mono, monospace';c.textAlign='right';c.textBaseline='middle';for(var g=0;g<5;g++){var y=pad.t+g*h/4,v=hi-g*range/4;c.strokeStyle='rgba(255,255,255,.07)';c.lineWidth=1;c.beginPath();c.moveTo(pad.l,y);c.lineTo(cssW-pad.r,y);c.stroke();c.fillStyle='rgba(160,180,200,.62)';c.fillText('$'+v.toFixed(2),pad.l-10,y);}var positive=m.total>=0,line=positive?'#00e676':'#ff5252',grad=c.createLinearGradient(0,pad.t,0,pad.t+h);grad.addColorStop(0,positive?'rgba(0,230,118,.34)':'rgba(255,82,82,.30)');grad.addColorStop(1,'rgba(0,0,0,.02)');c.beginPath();c.moveTo(X(0),Y(pts[0]));for(var i=1;i<pts.length;i++)c.lineTo(X(i),Y(pts[i]));c.lineTo(X(pts.length-1),pad.t+h);c.lineTo(X(0),pad.t+h);c.closePath();c.fillStyle=grad;c.fill();c.beginPath();c.moveTo(X(0),Y(pts[0]));for(var j=1;j<pts.length;j++)c.lineTo(X(j),Y(pts[j]));c.strokeStyle=line;c.lineWidth=2.5;c.stroke();}
function paint(){var st=window.__CTL_HISTORY_STABLE__;if(!st||st.version<10)return false;var m=metrics(st);if(!m.trades.length)return false;var growth=m.init>0?m.total/m.init*100:0,colorPos=m.total>=0?'var(--green)':'var(--red)';color('statNetPnl',money(m.total),colorPos);color('statGrowth',(growth>=0?'+':'')+growth.toFixed(2)+'%',growth>=0?'var(--green)':'var(--red)');color('statMaxDD',m.maxDDpct.toFixed(2)+'%','var(--red)');color('statTotalTrades',String(m.trades.length),'var(--gold)');color('dGrossProfit','$'+m.grossProfit.toFixed(4),'var(--green)');color('dGrossLoss','-$'+m.grossLoss.toFixed(4),'var(--red)');text('dAvgProfit','$'+m.avgProfit.toFixed(4));text('dAvgLoss','$'+m.avgLoss.toFixed(4));text('dPayoff',plainMoney(m.payoff));text('dInitDeposit','$'+m.init.toFixed(2));text('dPF',m.pf===Infinity?'∞':m.pf.toFixed(2));color('dWinRate',(m.trades.length?m.wins.length*100/m.trades.length:0).toFixed(2)+'% ('+m.wins.length+')','var(--green)');color('dLossRate',(m.trades.length?m.losses.length*100/m.trades.length:0).toFixed(2)+'% ('+m.losses.length+')','var(--red)');text('dRR',m.rr==null?'—':m.rr.toFixed(2));text('dRecovery',m.recovery==null?'—':m.recovery.toFixed(2));text('dMaxProfit','$'+m.largestProfit.toFixed(4));color('dMaxDDVal','$'+m.maxDD.toFixed(4),'var(--red)');text('dAbsDD','$'+m.absDD.toFixed(2));color('dLargestProfit','$'+m.largestProfit.toFixed(4),'var(--green)');color('dLargestLoss',plainMoney(m.largestLoss),'var(--red)');text('dMaxLoss','$'+Math.abs(m.largestLoss).toFixed(4));color('dConsecLoss',String(m.streak.maxL),'var(--gold)');text('dLongsWon',m.longWins+'/'+m.longs.length+' ('+(m.longs.length?Math.round(m.longWins/m.longs.length*100):0)+'%)');text('dShortsWon',m.shortWins+'/'+m.shorts.length+' ('+(m.shorts.length?Math.round(m.shortWins/m.shorts.length*100):0)+'%)');color('dConsecWins',String(m.streak.maxW),'var(--gold)');text('dAvgConsecW',m.streak.avgW.toFixed(1));text('dAvgConsecL',m.streak.avgL.toFixed(1));color('dTotalTrades2',String(m.trades.length),'var(--gold)');paintChart(m);window.__CTL_HL_PORTFOLIO_V21__.last=m;return true;}
function install(){var old=window.__CTL_HL_PORTFOLIO_V21__;if(old&&old.timer)try{clearInterval(old.timer);}catch(e){}var s={ready:true,version:21,timer:null,last:null,paint:paint};window.__CTL_HL_PORTFOLIO_V21__=s;paint();s.timer=setInterval(paint,TICK);window.addEventListener('resize',paint);return true;}
window.__ctlInstallHlPortfolioV21=install;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0);},{once:true});else setTimeout(install,0);
})();
